**The following code has been implemented on Kaggle T4 GPU**

### Installation of STELLAR

In [1]:
!git clone -q https://github.com/microsoft/STELLAR.git
!ls -la /kaggle/working/STELLAR
%cd /kaggle/working/STELLAR

total 84
drwxr-xr-x  8 root root  4096 Sep 12 09:26 .
drwxr-xr-x  4 root root  4096 Sep 12 09:26 ..
drwxr-xr-x 10 root root  4096 Sep 12 09:26 configs
drwxr-xr-x  2 root root  4096 Sep 12 09:26 docs
drwxr-xr-x  2 root root  4096 Sep 12 09:26 examples
drwxr-xr-x  8 root root  4096 Sep 12 09:26 .git
-rw-r--r--  1 root root   136 Sep 12 09:26 .gitignore
drwxr-xr-x  2 root root  4096 Sep 12 09:26 images
-rw-r--r--  1 root root  1066 Sep 12 09:26 LICENSE
-rw-r--r--  1 root root  3409 Sep 12 09:26 load_stellar.py
-rw-r--r--  1 root root 20014 Sep 12 09:26 README.md
-rw-r--r--  1 root root    72 Sep 12 09:26 requirements-eval.txt
-rw-r--r--  1 root root   139 Sep 12 09:26 requirements-inference.txt
-rw-r--r--  1 root root   566 Sep 12 09:26 requirements.txt
-rw-r--r--  1 root root  1329 Sep 12 09:26 run.py
-rw-r--r--  1 root root   542 Sep 12 09:26 SECURITY.md
drwxr-xr-x  7 root root  4096 Sep 12 09:26 src
/kaggle/working/STELLAR

In [2]:
# Installing requirments.txt for STELLAR 
!pip install -q -r requirements.txt

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.7/46.7 kB 2.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.7/91.7 kB 4.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.9/50.9 kB 3.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 kB 3.1 MB/s eta 0:00:00
ERROR: Ignored the following versions that require a different python version: 0.0.0 Requires-Python <3.11,>=3.8; 0.0.10 Requires-Python >=3.8,<3.9; 0.0.11 Requires-Python >=3.8,<3.9; 0.0.12 Requires-Python >=3.8,<3.9; 0.0.14 Requires-Python >=3.8,<3.9; 0.0.15 Requires-Python >=3.8,<3.9; 0.0.16 Requires-Python >=3.8,<3.9; 0.0.17 Requires-Python >=3.8,<3.9; 0.0.18 Requires-Python >=3.8,<3.9; 0.0.19 Requires-Python >=3.8,<3.9; 0.0.20 Requires-Python >=3.8,<3.9; 0.0.21 Requires-Python >=3.8,<3.9; 0.0.22 Requires-Python >=3.8,<3.9; 0.0.23 Requires-Python >=3.8,<3.9; 0.0.24 Requires-Python >=3.8,<3.9; 0.0.25 Requires-Python >=3.8,<3.9; 0.0.26 Requires-Python >=3.8,<3.9; 0.0.27 Requires-Python >=3.8,<3.9; 0.0.28 Requires-Python >=3.8,<3.9; 0.0.29 Requires-Python >=3.8,<3.9; 0.0.30 Requires-Python >=3.8,<3.9; 0.0.31 Requires-Python >=3.8,<3.9; 0.0.32 Requires-Python >=3.8,<3.9; 0.0.33 Requires-Python >=3.8,<3.9; 0.0.34 Requires-Python >=3.8,<3.9; 0.0.35 Requires-Python >=3.8,<3.9; 0.0.36 Requires-Python >=3.8,<3.9; 0.0.37 Requires-Python >=3.8,<3.9; 0.0.38 Requires-Python >=3.8,<3.9; 0.0.40 Requires-Python >=3.8,<3.9; 0.0.41 Requires-Python >=3.8,<3.9; 0.0.42 Requires-Python >=3.8,<3.9; 0.0.43 Requires-Python >=3.8,<3.9; 0.0.44 Requires-Python >=3.8,<3.9; 0.0.45 Requires-Python >=3.8,<3.9; 0.0.46 Requires-Python >=3.8,<3.11; 0.0.46.post1 Requires-Python >=3.8,<3.11; 0.0.46.post2 Requires-Python >=3.8,<3.11; 0.0.46.post3 Requires-Python <3.11,>=3.8; 0.0.48 Requires-Python <3.11,>=3.8; 0.0.48.post1 Requires-Python <3.11,>=3.8; 0.0.50 Requires-Python <3.11,>=3.8; 0.0.51 Requires-Python <3.11,>=3.8; 0.0.51.post1 Requires-Python <3.11,>=3.8; 0.0.52 Requires-Python <3.11,>=3.8; 0.0.52.post1 Requires-Python <3.11,>=3.8; 0.0.52.post2 Requires-Python <3.11,>=3.8; 0.0.53 Requires-Python <3.11,>=3.8; 0.0.54 Requires-Python <3.11,>=3.8; 0.0.55 Requires-Python <3.11,>=3.8; 0.0.56 Requires-Python <3.11,>=3.8; 0.0.57 Requires-Python <3.11,>=3.8; 0.0.58 Requires-Python <3.11,>=3.8; 0.0.59 Requires-Python <3.11,>=3.8; 0.0.6 Requires-Python >=3.8,<3.9; 0.0.6.post1 Requires-Python >=3.8,<3.9; 0.0.60 Requires-Python <3.11,>=3.8; 0.0.61 Requires-Python <3.11,>=3.8; 0.0.62 Requires-Python <3.11,>=3.8; 0.0.63 Requires-Python <3.11,>=3.8; 0.0.64 Requires-Python <3.11,>=3.8; 0.0.65 Requires-Python <3.11,>=3.8; 0.0.66 Requires-Python <3.11,>=3.8; 0.0.67 Requires-Python <3.11,>=3.8; 0.0.69 Requires-Python <3.11,>=3.8; 0.0.7 Requires-Python >=3.8,<3.9; 0.0.70 Requires-Python <3.11,>=3.8; 0.0.71 Requires-Python <3.11,>=3.8; 0.0.72 Requires-Python <3.11,>=3.8; 0.0.73 Requires-Python <3.11,>=3.8; 0.0.74 Requires-Python <3.11,>=3.8; 0.0.75 Requires-Python <3.11,>=3.8; 0.0.76 Requires-Python <3.11,>=3.8; 0.0.77 Requires-Python <3.11,>=3.8; 0.0.78 Requires-Python <3.11,>=3.8; 0.0.79 Requires-Python <3.11,>=3.8; 0.0.8 Requires-Python >=3.8,<3.9; 0.0.80 Requires-Python <3.11,>=3.8; 0.0.81 Requires-Python <3.11,>=3.8; 0.0.82 Requires-Python <3.11,>=3.8; 0.0.83 Requires-Python <3.11,>=3.8; 0.0.84 Requires-Python <3.11,>=3.8; 0.0.85 Requires-Python <3.11,>=3.8; 0.0.86 Requires-Python <3.11,>=3.8; 0.0.87 Requires-Python <3.11,>=3.8; 0.0.88 Requires-Python <3.11,>=3.8; 0.0.89 Requires-Python <3.12,>=3.8; 0.0.9 Requires-Python >=3.8,<3.9; 0.0.90 Requires-Python <3.12,>=3.8; 0.0.91 Requires-Python <3.12,>=3.8; 47.0.0 Requires-Python <3.11,>=3.8
ERROR: Could not find a version that satisfies the requirement azureml-acft-image-components==0.0.79 (from versions: 0.0.0b1)
ERROR: No matching distribution found for azureml-acft-image-components==0.0.79

In [3]:
# Installing safetensors for huggingface_hub for STELLAR working
!pip install -q huggingface_hub safetensors

In [6]:
# Loading baseline STELLAR
import json
import torch
from huggingface_hub import hf_hub_download
from safetensors.torch import load_file
from src.models.stellar_model import STELLARModel # Loading the STELLAR-B16 model

repo = "microsoft/STELLAR" # STELLAR path
config_path = hf_hub_download(repo_id=repo,filename="config.json") # Configuration path

with open(config_path, "r") as f:
    config = json.load(f)
cfg = config["models"]["stellar-b16"] # Loading STELLAR-B16 model (more efficient)

# Loading model with configuration
model = STELLARModel(
    num_sparse_tokens=cfg["num_sparse_tokens"],
    num_decoder_layers=cfg["num_decoder_layers"],
    spatial_temp=cfg["spatial_temp"],
    vit_pretrained=cfg["backbone"],
    do_recon=False,
    do_clustering=False,
    vq_model=None,
)

# Setting up device for evaluation
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)
model.eval()

You are using a model of type vit_mae to instantiate a model of type vit. This is not supported for all configurations of models and can yield errors.

Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]

ViTModel LOAD REPORT from: facebook/vit-mae-base
Key                                                                              | Status     |
---------------------------------------------------------------------------------+------------+-
decoder.decoder_layers.{0, 1, 2, 3, 4, 5, 6, 7}.layernorm_after.weight           | UNEXPECTED |
decoder.decoder_layers.{0, 1, 2, 3, 4, 5, 6, 7}.attention.attention.value.bias   | UNEXPECTED |
decoder.decoder_layers.{0, 1, 2, 3, 4, 5, 6, 7}.attention.attention.query.bias   | UNEXPECTED |
decoder.decoder_layers.{0, 1, 2, 3, 4, 5, 6, 7}.output.dense.weight              | UNEXPECTED |
decoder.decoder_layers.{0, 1, 2, 3, 4, 5, 6, 7}.intermediate.dense.weight        | UNEXPECTED |
decoder.decoder_layers.{0, 1, 2, 3, 4, 5, 6, 7}.attention.output.dense.bias      | UNEXPECTED |
decoder.decoder_layers.{0, 1, 2, 3, 4, 5, 6, 7}.intermediate.dense.bias          | UNEXPECTED |
decoder.decoder_layers.{0, 1, 2, 3, 4, 5, 6, 7}.attention.attention.key.weight   | UNEXPECTED |
decoder.decoder_layers.{0, 1, 2, 3, 4, 5, 6, 7}.layernorm_before.bias            | UNEXPECTED |
decoder.decoder_layers.{0, 1, 2, 3, 4, 5, 6, 7}.output.dense.bias                | UNEXPECTED |
decoder.decoder_layers.{0, 1, 2, 3, 4, 5, 6, 7}.layernorm_after.bias             | UNEXPECTED |
decoder.decoder_layers.{0, 1, 2, 3, 4, 5, 6, 7}.attention.attention.key.bias     | UNEXPECTED |
decoder.decoder_layers.{0, 1, 2, 3, 4, 5, 6, 7}.attention.attention.query.weight | UNEXPECTED |
decoder.decoder_layers.{0, 1, 2, 3, 4, 5, 6, 7}.attention.output.dense.weight    | UNEXPECTED |
decoder.decoder_layers.{0, 1, 2, 3, 4, 5, 6, 7}.layernorm_before.weight          | UNEXPECTED |
decoder.decoder_norm.weight                                                      | UNEXPECTED |
decoder.mask_token                                                               | UNEXPECTED |
decoder.decoder_pos_embed                                                        | UNEXPECTED |
decoder.decoder_pred.weight                                                      | UNEXPECTED |
decoder.decoder_embed.bias                                                       | UNEXPECTED |
decoder.decoder_layers.{0, 1, 2, 3, 4, 5, 6, 7}.attention.attention.value.weight | UNEXPECTED |
decoder.decoder_pred.bias                                                        | UNEXPECTED |
decoder.decoder_norm.bias                                                        | UNEXPECTED |
decoder.decoder_embed.weight                                                     | UNEXPECTED |
pooler.dense.weight                                                              | MISSING    |
pooler.dense.bias                                                                | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

STELLARModel(
  (encoder): ViTModel(
    (embeddings): ViTEmbeddings(
      (patch_embeddings): ViTPatchEmbeddings(
        (projection): Conv2d(3, 768, kernel_size=(16, 16), stride=(16, 16))
      )
      (dropout): Dropout(p=0.0, inplace=False)
    )
    (encoder): ViTEncoder(
      (layer): ModuleList(
        (0-11): 12 x ViTLayer(
          (attention): ViTAttention(
            (attention): ViTSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
            )
            (output): ViTSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.0, inplace=False)
            )
          )
          (intermediate): ViTIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): ViTOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (layernorm_before): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (layernorm_after): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
    (layernorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (pooler): ViTPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (position_embedding): PositionEmbeddingRandom()
  (dense_proj): Linear(in_features=768, out_features=768, bias=True)
  (sparse_proj): Linear(in_features=768, out_features=768, bias=True)
  (matcher): MatcherSinkhorn()
  (koleo_loss): KoLeoLoss(
    (pdist): PairwiseDistance()
  )
)

In [7]:
"""
Sanity test on STELLAR-B16 to check semantic and localization matrix

For device configuration
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
"""
image = torch.rand(1, 3, 224, 224,device=device)
with torch.no_grad():
    out = model.encode(image)

for key, value in out.items():
    if torch.is_tensor(value):
        print(key, value.shape)
"""
sparse torch.Size([]) is semantic matrix
spatial torch.Size([]) is localization matrix
"""

sparse torch.Size([1, 16, 768])
spatial torch.Size([1, 196, 16])
concat torch.Size([1, 16, 964])
lowrank torch.Size([1, 196, 768])
dense torch.Size([1, 196, 768])
cls torch.Size([1, 1, 768])
peak_dist torch.Size([1, 16])

In Glas segmentation dataset, we'll be using a total of 85 images, out of which, 70 are for training and 15 are for testing. For testing purpose, we'll be using 60 TestA and 20 TestB images so far. 

Images in GlaS segmentation dataset are in .bmp (bitmap) format. In .bmp images, pixel values are explicitly stored and it generally lossless/uncompressed and can preserve exact pixel values.

### GlaSSegmentationDataset

In [8]:

import os
import numpy as np
import torch

from PIL import Image
from torch.utils.data import Dataset
from torchvision.transforms import functional as TF
from torchvision.transforms import InterpolationMode


class GlaSSegmentationDataset(Dataset):
    def __init__(self,root,split="train",resolution=224,crop_scale=0.5,augment=False,):
        self.root = root
        self.split = split
        self.resolution = resolution
        self.crop_scale = crop_scale
        self.augment = augment


        # Select images belonging to the official split
        if split == "train":
            image_files = [f for f in os.listdir(root)if f.startswith("train_")
                and f.endswith(".bmp") and not f.endswith("_anno.bmp")]
            
        elif split == "testA":
            image_files = [f for f in os.listdir(root) if f.startswith("testA_")
                and f.endswith(".bmp") and not f.endswith("_anno.bmp")]

        elif split == "testB":
            image_files = [f for f in os.listdir(root) if f.startswith("testB_")
                and f.endswith(".bmp") and not f.endswith("_anno.bmp")]

        else:
            raise ValueError( f"Unknown split: {split}. Expected train, testA or testB.")

        # Build image/mask pairs
        self.samples = []
        for image_file in sorted(image_files):
            mask_file = image_file.replace(".bmp","_anno.bmp")
            image_path = os.path.join(root,image_file)
            mask_path = os.path.join(root,mask_file)
            if not os.path.exists(mask_path):
                raise FileNotFoundError(f"Missing mask for {image_file} | {mask_path}")
            self.samples.append((image_path, mask_path))
        print(f"GlaS {split} | {len(self.samples)} image/mask pairs | augment={self.augment}")
        
    def __len__(self):
        return len(self.samples)


    """
    Instance mask to binary semantic mask
    
    We'll be converting instance mask to binary semantic mask
    In original GlaS dataset, 
    0      = background
    1..32  = individual gland instances

    In binary semantic masking, 
    0 = background
    1 = gland
    """
    def _convert_mask(self, mask):
        mask = np.array(mask)
        mask = (mask > 0).astype(np.uint8)
        return torch.from_numpy(mask).long()


    # Training augmentation
    def _train_transform(self, image, mask):
        width, height = TF.get_image_size(image)
        
        # Random crop scale
        scale = torch.empty(1).uniform_(self.crop_scale,1.0).item()

        crop_h = int(height * scale)
        crop_w = int(width * scale)

        crop_h = max(1, min(crop_h, height))
        crop_w = max(1, min(crop_w, width))

        # Random crop position
        if height == crop_h:
            top = 0
        else:
            top = torch.randint(0,height - crop_h + 1,(1,)).item()
            
        if width == crop_w:
            left = 0
        else:
            left = torch.randint(0,width - crop_w + 1,(1,)).item()

        # Image: bicubic
        image = TF.resized_crop(image,top,left,crop_h,crop_w,
            [self.resolution, self.resolution],
            interpolation=InterpolationMode.BICUBIC,)

        # Mask: nearest-neighbor
        mask = TF.resized_crop(mask.unsqueeze(0).float(),top,left,crop_h,crop_w,
            [self.resolution, self.resolution],
            interpolation=InterpolationMode.NEAREST,).squeeze(0).long()
     
        # Random horizontal flip
        if torch.rand(1).item() < 0.5:
            image = TF.hflip(image)
            mask = TF.hflip(mask)
        return image, mask
   
    # Deterministic validation/test transform
    def _eval_transform(self, image, mask):
        crop_res = int(self.resolution * 256 / 224)

        # Image: bicubic
        image = TF.resize(
            image,
            [crop_res, crop_res],
            interpolation=InterpolationMode.BICUBIC,
        )

        # Mask: nearest
        mask = TF.resize(
            mask.unsqueeze(0).float(),
            [crop_res, crop_res],
            interpolation=InterpolationMode.NEAREST,
        ).squeeze(0).long()

        # Center crop
        image = TF.center_crop(image,[self.resolution, self.resolution])
        mask = TF.center_crop(mask,[self.resolution, self.resolution])
        return image, mask

    # Get item
    def __getitem__(self, idx):
        image_path, mask_path = self.samples[idx]

        # Load image and mask
        image = Image.open(image_path).convert("RGB")
        mask = Image.open(mask_path).convert("L")
        mask = self._convert_mask(mask) # Instance to Semantic conversion

        # Apply transform
        if self.augment:
            image, mask = self._train_transform(image,mask) # For training
        else:
            image, mask = self._eval_transform(image,mask) # For testing/validation
        image = TF.to_tensor(image) # Image to Tensor transform
        return {
            "image": image.clamp(0, 1),
            "labels": mask,
            "filename": idx,
        }

In [9]:
# ROOT path of GlaS dataset
ROOT = "/kaggle/input/datasets/sani84/glasmiccai2015-gland-segmentation/Warwick_QU_Dataset"

# For training during training
glas_train_aug = GlaSSegmentationDataset(root=ROOT,split="train",resolution=224,augment=True,)
# For validation during training
glas_train_eval = GlaSSegmentationDataset(root=ROOT,split="train",resolution=224,augment=False,)

SEED = 42
generator = torch.Generator().manual_seed(SEED)
indices = torch.randperm(len(glas_train_aug),generator=generator).tolist()

train_indices = indices[:70]
val_indices = indices[70:]
print("Train indices:", len(train_indices))
print("Validation indices:", len(val_indices))

print("Train examples:", train_indices[:10])
print("Val examples:", val_indices[:10])

GlaS train | 85 image/mask pairs | augment=True
GlaS train | 85 image/mask pairs | augment=False
Train indices: 70
Validation indices: 15
Train examples: [47, 24, 37, 11, 13, 60, 17, 27, 71, 22]
Val examples: [23, 16, 75, 55, 39, 68, 41, 3, 62, 35]

### Train Loader, Test Loader

In [10]:
from torch.utils.data import Subset
from torch.utils.data import DataLoader

# Training subset
train_subset = Subset(glas_train_aug,train_indices)
# Validation subset
val_subset = Subset(glas_train_eval,val_indices)

# For testing purpose these testA_dataset, testB_dataset will be used
testA_dataset = GlaSSegmentationDataset(root=ROOT,split="testA",resolution=224,augment=False,)
testB_dataset = GlaSSegmentationDataset(root=ROOT,split="testB",resolution=224,augment=False,)

# Training loader
probe_train_loader = DataLoader(train_subset,batch_size=4,shuffle=True,num_workers=2,pin_memory=True,)
# Validation loader
probe_val_loader = DataLoader(val_subset,batch_size=4,shuffle=False,num_workers=2,pin_memory=True,)

# TestA loader
testA_loader = DataLoader(testA_dataset,batch_size=4,shuffle=False,num_workers=2,pin_memory=True,)
# TestB loader
testB_loader = DataLoader(testB_dataset,batch_size=4,shuffle=False,num_workers=2,pin_memory=True,)

GlaS testA | 60 image/mask pairs | augment=False
GlaS testB | 20 image/mask pairs | augment=False

### Segmentation Metrics

In [12]:
# segmentation metrics contain Dice, IoU, Accuracy
"""
Dice, IoU, Accuracy metrics is measured for image segmentation task
Four fundamental things is required for that, 
TP = True Positive = predicted foreground, actually foreground
FP = False Positive = predicted foreground, actually background
TN = True Negative = predicted background, actually background
FN = False Negative = predicted background, actually foreground

So, Dice = 2.TP/(2.TP + FP + FN) or Dice = 2|P intersection G| / |P| + |G|
where, P is the predicted segmentation and G is the ground truth.

IoU = TP/(TP + FP + FN) or IoU = |P intersection G| / |P union G|
mIoU = mean intersection over union (for every classes combined divided by total number of class)
Accuracy = TP+TN/(TP+TN+FP+FN)
"""


import numpy as np

def segmentation_metrics(pred, target, num_classes=2):
    pred = pred.detach().cpu().numpy().reshape(-1)
    target = target.detach().cpu().numpy().reshape(-1)
    metrics = {}
    ious = []

    for cls in range(num_classes):
        pred_cls = pred == cls
        target_cls = target == cls
        intersection = np.logical_and(pred_cls,target_cls).sum()
        union = np.logical_or(pred_cls,target_cls).sum()

        if union == 0:
            iou = np.nan
        else:
            iou = intersection / union
        ious.append(iou)

    # Background IoU and Gland IoU
    metrics["background_iou"] = ious[0]
    metrics["gland_iou"] = ious[1]
    valid_ious = [x for x in ious if not np.isnan(x)]
    metrics["miou"] = np.mean(valid_ious)

    # Gland Dice
    pred_gland = pred == 1
    target_gland = target == 1
    intersection = np.logical_and(pred_gland, target_gland).sum()
    pred_area = pred_gland.sum()
    target_area = target_gland.sum()
    denominator = pred_area + target_area

    if denominator == 0:
        dice = 1.0
    else:
        dice = (2.0 * intersection / denominator)

    metrics["gland_dice"] = dice
    metrics["pixel_accuracy"] = (pred == target).mean()
    return metrics

### Run Epoch Broilerplate Code

In [13]:
# Broiler plate running code for larger epochs
def run_epoch(model,loader,optimizer=None,criterion=None,device="cuda",):
    is_training = optimizer is not None
    if is_training:
        model.train()
    else:
        model.eval()

    total_loss = 0.0
    all_preds = []
    all_labels = []

    for batch in loader:
        images = batch["image"].to(device)
        labels = batch["labels"].to(device)

        if is_training:
            optimizer.zero_grad()

        with torch.set_grad_enabled(is_training):
            outputs = model({"image": images})
            logits = outputs["predictions"]
            loss = criterion(logits,labels)
            if is_training:
                loss.backward()
                optimizer.step()

        total_loss += loss.item() * images.size(0)
        preds = torch.argmax(logits,dim=1)
        all_preds.append(preds.detach().cpu())
        all_labels.append(labels.detach().cpu())

    all_preds = torch.cat(all_preds, dim=0)
    all_labels = torch.cat(all_labels, dim=0)

    metrics = segmentation_metrics(all_preds,all_labels)
    metrics["loss"] = (total_loss / len(loader.dataset))
    return metrics

### Dense Model 3 SEED

In [27]:
from src.models.downstream.segmentation import SegmentationProbing
dense_model = SegmentationProbing(
    model_backbone=model,
    is_baseline=False,
    feature_key="dense",
    feature_dim=768,
    num_classes=2,
    freeze_backbone=True,
    freeze_model=False,
    resize_output=(224, 224),
).to(device)

  # We'll be using Adam with weighted decay optimizer
optimizer = torch.optim.AdamW(
    filter(lambda p: p.requires_grad, dense_model.parameters()),
    lr=1e-3,weight_decay=1e-4,)
# We'll be using cross entropy loss
criterion = torch.nn.CrossEntropyLoss()

In [30]:
# Dense model running for seed 42, 123, 2026
import random

history = []

def train_dense_probe(seed, num_epochs=50):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

    # Best checkpoint in memory
    best_val_dice = -1.0
    best_epoch = -1
    best_state = None

    # Training
    for epoch in range(num_epochs):
        train_metrics = run_epoch(dense_model,probe_train_loader,optimizer=optimizer,
            criterion=criterion,device=device,)
        
        val_metrics = run_epoch(dense_model,probe_val_loader,optimizer=None,
            criterion=criterion,device=device,)

        history.append({
            "epoch": epoch + 1,
            "train_dice": train_metrics["gland_dice"],
            "train_miou": train_metrics["miou"],
            "val_dice": val_metrics["gland_dice"],
            "val_miou": val_metrics["miou"],
        })

        print(
            f"[Seed {seed}] "
            f"Epoch {epoch+1:02d}/{num_epochs} | "
            f"Train Dice: {train_metrics['gland_dice']:.4f} | "
            f"Val Dice: {val_metrics['gland_dice']:.4f}"
        )

        if val_metrics["gland_dice"] > best_val_dice:
            best_val_dice = val_metrics["gland_dice"]
            best_epoch = epoch + 1
            best_state = {
                k: v.detach().cpu().clone()
                for k, v in dense_model.state_dict().items()
            }


    """  
    # Restore best model
    dense_model.load_state_dict(best_state)
    dense_model.eval()

    # TestA
    testA_metrics = run_epoch(dense_model,testA_loader,optimizer=None,
        criterion=criterion,device=device,)

    # TestB
    testB_metrics = run_epoch(dense_model,testB_loader,optimizer=None,
        criterion=criterion,device=device,)
    """
    return {
        "seed": seed,
        "best_epoch": best_epoch,
        "best_val_dice": best_val_dice,
        "history": history,
    }

In [34]:

dense_results = {}
for seed in [42, 123, 2026]:
    print("\n" + "=" * 70)
    print(f"STARTING DENSE PROBE — SEED {seed}")
    print("=" * 70)
    dense_results[seed] = train_dense_probe(seed=seed,num_epochs=50)

======================================================================
STARTING DENSE PROBE — SEED 42
======================================================================
[Seed 42] Epoch 01/50 | Train Dice: 0.8401 | Val Dice: 0.8482
[Seed 42] Epoch 02/50 | Train Dice: 0.8515 | Val Dice: 0.8380
[Seed 42] Epoch 03/50 | Train Dice: 0.8491 | Val Dice: 0.8381
[Seed 42] Epoch 04/50 | Train Dice: 0.8448 | Val Dice: 0.8389
[Seed 42] Epoch 05/50 | Train Dice: 0.8465 | Val Dice: 0.8459
[Seed 42] Epoch 06/50 | Train Dice: 0.8507 | Val Dice: 0.8430
[Seed 42] Epoch 07/50 | Train Dice: 0.8486 | Val Dice: 0.8440
[Seed 42] Epoch 08/50 | Train Dice: 0.8464 | Val Dice: 0.8495
[Seed 42] Epoch 09/50 | Train Dice: 0.8528 | Val Dice: 0.8485
[Seed 42] Epoch 10/50 | Train Dice: 0.8478 | Val Dice: 0.8503
[Seed 42] Epoch 11/50 | Train Dice: 0.8401 | Val Dice: 0.8420
[Seed 42] Epoch 12/50 | Train Dice: 0.8525 | Val Dice: 0.8450
[Seed 42] Epoch 13/50 | Train Dice: 0.8491 | Val Dice: 0.8449
[Seed 42] Epoch 14/50 | Train Dice: 0.8557 | Val Dice: 0.8425
[Seed 42] Epoch 15/50 | Train Dice: 0.8573 | Val Dice: 0.8477
[Seed 42] Epoch 16/50 | Train Dice: 0.8481 | Val Dice: 0.8491
[Seed 42] Epoch 17/50 | Train Dice: 0.8476 | Val Dice: 0.8508
[Seed 42] Epoch 18/50 | Train Dice: 0.8433 | Val Dice: 0.8456
[Seed 42] Epoch 19/50 | Train Dice: 0.8525 | Val Dice: 0.8489
[Seed 42] Epoch 20/50 | Train Dice: 0.8554 | Val Dice: 0.8499
[Seed 42] Epoch 21/50 | Train Dice: 0.8492 | Val Dice: 0.8477
[Seed 42] Epoch 22/50 | Train Dice: 0.8455 | Val Dice: 0.8517
[Seed 42] Epoch 23/50 | Train Dice: 0.8603 | Val Dice: 0.8470
[Seed 42] Epoch 24/50 | Train Dice: 0.8570 | Val Dice: 0.8492
[Seed 42] Epoch 25/50 | Train Dice: 0.8480 | Val Dice: 0.8497
[Seed 42] Epoch 26/50 | Train Dice: 0.8564 | Val Dice: 0.8453
[Seed 42] Epoch 27/50 | Train Dice: 0.8526 | Val Dice: 0.8444
[Seed 42] Epoch 28/50 | Train Dice: 0.8580 | Val Dice: 0.8473
[Seed 42] Epoch 29/50 | Train Dice: 0.8652 | Val Dice: 0.8424
[Seed 42] Epoch 30/50 | Train Dice: 0.8374 | Val Dice: 0.8441
[Seed 42] Epoch 31/50 | Train Dice: 0.8529 | Val Dice: 0.8474
[Seed 42] Epoch 32/50 | Train Dice: 0.8530 | Val Dice: 0.8489
[Seed 42] Epoch 33/50 | Train Dice: 0.8449 | Val Dice: 0.8397
[Seed 42] Epoch 34/50 | Train Dice: 0.8634 | Val Dice: 0.8463
[Seed 42] Epoch 35/50 | Train Dice: 0.8449 | Val Dice: 0.8386
[Seed 42] Epoch 36/50 | Train Dice: 0.8479 | Val Dice: 0.8414
[Seed 42] Epoch 37/50 | Train Dice: 0.8431 | Val Dice: 0.8469
[Seed 42] Epoch 38/50 | Train Dice: 0.8532 | Val Dice: 0.8495
[Seed 42] Epoch 39/50 | Train Dice: 0.8504 | Val Dice: 0.8507
[Seed 42] Epoch 40/50 | Train Dice: 0.8425 | Val Dice: 0.8478
[Seed 42] Epoch 41/50 | Train Dice: 0.8448 | Val Dice: 0.8542
[Seed 42] Epoch 42/50 | Train Dice: 0.8559 | Val Dice: 0.8490
[Seed 42] Epoch 43/50 | Train Dice: 0.8480 | Val Dice: 0.8471
[Seed 42] Epoch 44/50 | Train Dice: 0.8556 | Val Dice: 0.8504
[Seed 42] Epoch 45/50 | Train Dice: 0.8571 | Val Dice: 0.8473
[Seed 42] Epoch 46/50 | Train Dice: 0.8559 | Val Dice: 0.8520
[Seed 42] Epoch 47/50 | Train Dice: 0.8528 | Val Dice: 0.8481
[Seed 42] Epoch 48/50 | Train Dice: 0.8475 | Val Dice: 0.8484
[Seed 42] Epoch 49/50 | Train Dice: 0.8460 | Val Dice: 0.8516
[Seed 42] Epoch 50/50 | Train Dice: 0.8502 | Val Dice: 0.8511

======================================================================
STARTING DENSE PROBE — SEED 123
======================================================================
[Seed 123] Epoch 01/50 | Train Dice: 0.8535 | Val Dice: 0.8538
[Seed 123] Epoch 02/50 | Train Dice: 0.8643 | Val Dice: 0.8493
[Seed 123] Epoch 03/50 | Train Dice: 0.8564 | Val Dice: 0.8512
[Seed 123] Epoch 04/50 | Train Dice: 0.8475 | Val Dice: 0.8437
[Seed 123] Epoch 05/50 | Train Dice: 0.8567 | Val Dice: 0.8537
[Seed 123] Epoch 06/50 | Train Dice: 0.8511 | Val Dice: 0.8552
[Seed 123] Epoch 07/50 | Train Dice: 0.8402 | Val Dice: 0.8507
[Seed 123] Epoch 08/50 | Train Dice: 0.8526 | Val Dice: 0.8495
[Seed 123] Epoch 09/50 | Train Dice: 0.8538 | Val Dice: 0.8516
[Seed 123] Epoch 10/50 | Train Dice: 0.8516 | Val Dice: 0.8460
[Seed 123] Epoch 11/50 | Train Dice: 0.8582 | Val Dice: 0.8525
[Seed 123] Epoch 12/50 | Train Dice: 0.8613 | Val Dice: 0.8517
[Seed 123] Epoch 13/50 | Train Dice: 0.8332 | Val Dice: 0.8341
[Seed 123] Epoch 14/50 | Train Dice: 0.8551 | Val Dice: 0.8514
[Seed 123] Epoch 15/50 | Train Dice: 0.8506 | Val Dice: 0.8522
[Seed 123] Epoch 16/50 | Train Dice: 0.8616 | Val Dice: 0.8535
[Seed 123] Epoch 17/50 | Train Dice: 0.8642 | Val Dice: 0.8477
[Seed 123] Epoch 18/50 | Train Dice: 0.8600 | Val Dice: 0.8451
[Seed 123] Epoch 19/50 | Train Dice: 0.8561 | Val Dice: 0.8442
[Seed 123] Epoch 20/50 | Train Dice: 0.8500 | Val Dice: 0.8471
[Seed 123] Epoch 21/50 | Train Dice: 0.8613 | Val Dice: 0.8467
[Seed 123] Epoch 22/50 | Train Dice: 0.8586 | Val Dice: 0.8406
[Seed 123] Epoch 23/50 | Train Dice: 0.8566 | Val Dice: 0.8513
[Seed 123] Epoch 24/50 | Train Dice: 0.8511 | Val Dice: 0.8456
[Seed 123] Epoch 25/50 | Train Dice: 0.8438 | Val Dice: 0.8455
[Seed 123] Epoch 26/50 | Train Dice: 0.8475 | Val Dice: 0.8468
[Seed 123] Epoch 27/50 | Train Dice: 0.8605 | Val Dice: 0.8531
[Seed 123] Epoch 28/50 | Train Dice: 0.8481 | Val Dice: 0.8525
[Seed 123] Epoch 29/50 | Train Dice: 0.8539 | Val Dice: 0.8500
[Seed 123] Epoch 30/50 | Train Dice: 0.8402 | Val Dice: 0.8499
[Seed 123] Epoch 31/50 | Train Dice: 0.8524 | Val Dice: 0.8513
[Seed 123] Epoch 32/50 | Train Dice: 0.8418 | Val Dice: 0.8553
[Seed 123] Epoch 33/50 | Train Dice: 0.8492 | Val Dice: 0.8520
[Seed 123] Epoch 34/50 | Train Dice: 0.8442 | Val Dice: 0.8441
[Seed 123] Epoch 35/50 | Train Dice: 0.8573 | Val Dice: 0.8466
[Seed 123] Epoch 36/50 | Train Dice: 0.8494 | Val Dice: 0.8494
[Seed 123] Epoch 37/50 | Train Dice: 0.8535 | Val Dice: 0.8527
[Seed 123] Epoch 38/50 | Train Dice: 0.8534 | Val Dice: 0.8492
[Seed 123] Epoch 39/50 | Train Dice: 0.8522 | Val Dice: 0.8520
[Seed 123] Epoch 40/50 | Train Dice: 0.8475 | Val Dice: 0.8468
[Seed 123] Epoch 41/50 | Train Dice: 0.8582 | Val Dice: 0.8447
[Seed 123] Epoch 42/50 | Train Dice: 0.8543 | Val Dice: 0.8529
[Seed 123] Epoch 43/50 | Train Dice: 0.8527 | Val Dice: 0.8489
[Seed 123] Epoch 44/50 | Train Dice: 0.8509 | Val Dice: 0.8501
[Seed 123] Epoch 45/50 | Train Dice: 0.8541 | Val Dice: 0.8530
[Seed 123] Epoch 46/50 | Train Dice: 0.8550 | Val Dice: 0.8510
[Seed 123] Epoch 47/50 | Train Dice: 0.8548 | Val Dice: 0.8463
[Seed 123] Epoch 48/50 | Train Dice: 0.8650 | Val Dice: 0.8511
[Seed 123] Epoch 49/50 | Train Dice: 0.8501 | Val Dice: 0.8514
[Seed 123] Epoch 50/50 | Train Dice: 0.8472 | Val Dice: 0.8520

======================================================================
STARTING DENSE PROBE — SEED 2026
======================================================================
[Seed 2026] Epoch 01/50 | Train Dice: 0.8448 | Val Dice: 0.8488
[Seed 2026] Epoch 02/50 | Train Dice: 0.8554 | Val Dice: 0.8487
[Seed 2026] Epoch 03/50 | Train Dice: 0.8552 | Val Dice: 0.8454
[Seed 2026] Epoch 04/50 | Train Dice: 0.8479 | Val Dice: 0.8452
[Seed 2026] Epoch 05/50 | Train Dice: 0.8541 | Val Dice: 0.8513
[Seed 2026] Epoch 06/50 | Train Dice: 0.8437 | Val Dice: 0.8514
[Seed 2026] Epoch 07/50 | Train Dice: 0.8572 | Val Dice: 0.8539
[Seed 2026] Epoch 08/50 | Train Dice: 0.8518 | Val Dice: 0.8538
[Seed 2026] Epoch 09/50 | Train Dice: 0.8481 | Val Dice: 0.8522
[Seed 2026] Epoch 10/50 | Train Dice: 0.8619 | Val Dice: 0.8533
[Seed 2026] Epoch 11/50 | Train Dice: 0.8572 | Val Dice: 0.8537
[Seed 2026] Epoch 12/50 | Train Dice: 0.8592 | Val Dice: 0.8525
[Seed 2026] Epoch 13/50 | Train Dice: 0.8576 | Val Dice: 0.8523
[Seed 2026] Epoch 14/50 | Train Dice: 0.8573 | Val Dice: 0.8517
[Seed 2026] Epoch 15/50 | Train Dice: 0.8509 | Val Dice: 0.8531
[Seed 2026] Epoch 16/50 | Train Dice: 0.8469 | Val Dice: 0.8489
[Seed 2026] Epoch 17/50 | Train Dice: 0.8558 | Val Dice: 0.8513
[Seed 2026] Epoch 18/50 | Train Dice: 0.8518 | Val Dice: 0.8469
[Seed 2026] Epoch 19/50 | Train Dice: 0.8427 | Val Dice: 0.8531
[Seed 2026] Epoch 20/50 | Train Dice: 0.8479 | Val Dice: 0.8513
[Seed 2026] Epoch 21/50 | Train Dice: 0.8433 | Val Dice: 0.8555
[Seed 2026] Epoch 22/50 | Train Dice: 0.8560 | Val Dice: 0.8533
[Seed 2026] Epoch 23/50 | Train Dice: 0.8502 | Val Dice: 0.8505
[Seed 2026] Epoch 24/50 | Train Dice: 0.8503 | Val Dice: 0.8529
[Seed 2026] Epoch 25/50 | Train Dice: 0.8545 | Val Dice: 0.8509
[Seed 2026] Epoch 26/50 | Train Dice: 0.8594 | Val Dice: 0.8480
[Seed 2026] Epoch 27/50 | Train Dice: 0.8579 | Val Dice: 0.8404
[Seed 2026] Epoch 28/50 | Train Dice: 0.8460 | Val Dice: 0.8438
[Seed 2026] Epoch 29/50 | Train Dice: 0.8483 | Val Dice: 0.8499
[Seed 2026] Epoch 30/50 | Train Dice: 0.8471 | Val Dice: 0.8488
[Seed 2026] Epoch 31/50 | Train Dice: 0.8525 | Val Dice: 0.8529
[Seed 2026] Epoch 32/50 | Train Dice: 0.8569 | Val Dice: 0.8539
[Seed 2026] Epoch 33/50 | Train Dice: 0.8387 | Val Dice: 0.8550
[Seed 2026] Epoch 34/50 | Train Dice: 0.8373 | Val Dice: 0.8527
[Seed 2026] Epoch 35/50 | Train Dice: 0.8559 | Val Dice: 0.8509
[Seed 2026] Epoch 36/50 | Train Dice: 0.8586 | Val Dice: 0.8529
[Seed 2026] Epoch 37/50 | Train Dice: 0.8606 | Val Dice: 0.8483
[Seed 2026] Epoch 38/50 | Train Dice: 0.8485 | Val Dice: 0.8491
[Seed 2026] Epoch 39/50 | Train Dice: 0.8616 | Val Dice: 0.8486
[Seed 2026] Epoch 40/50 | Train Dice: 0.8585 | Val Dice: 0.8511
[Seed 2026] Epoch 41/50 | Train Dice: 0.8611 | Val Dice: 0.8504
[Seed 2026] Epoch 42/50 | Train Dice: 0.8558 | Val Dice: 0.8500
[Seed 2026] Epoch 43/50 | Train Dice: 0.8608 | Val Dice: 0.8460
[Seed 2026] Epoch 44/50 | Train Dice: 0.8416 | Val Dice: 0.8464
[Seed 2026] Epoch 45/50 | Train Dice: 0.8525 | Val Dice: 0.8505
[Seed 2026] Epoch 46/50 | Train Dice: 0.8552 | Val Dice: 0.8461
[Seed 2026] Epoch 47/50 | Train Dice: 0.8509 | Val Dice: 0.8495
[Seed 2026] Epoch 48/50 | Train Dice: 0.8568 | Val Dice: 0.8501
[Seed 2026] Epoch 49/50 | Train Dice: 0.8508 | Val Dice: 0.8429
[Seed 2026] Epoch 50/50 | Train Dice: 0.8567 | Val Dice: 0.8490

In [35]:
# storing values into csv file
import pandas as pd

history_df = pd.DataFrame(history)
csv_path = "/kaggle/working/stellar_dense_glas_probe_3_SEED_history.csv"
history_df.to_csv(csv_path, index=False)
display(history_df.head())

   epoch  train_dice  train_miou  val_dice  val_miou
0      1    0.793804    0.650547  0.808386  0.667846
1      2    0.808756    0.675887  0.812602  0.679120
2      3    0.815047    0.680883  0.819303  0.683343
3      4    0.824592    0.691928  0.818976  0.689919
4      1    0.826252    0.689748  0.834129  0.703021

In [36]:
# Summarizing results of 3 SEEDS for best validation dice
for seed, result in dense_results.items():
    print("\n" + "=" * 60)
    print(f"SEED {seed}")
    print("=" * 60)
    print(f"Best epoch: {result['best_epoch']}")
    print(f"Val Dice | {result['best_val_dice']:.4f}")

============================================================
SEED 42
============================================================
Best epoch: 41
Val Dice | 0.8542

============================================================
SEED 123
============================================================
Best epoch: 32
Val Dice | 0.8553

============================================================
SEED 2026
============================================================
Best epoch: 21
Val Dice | 0.8555

### Low Model 3 SEED

In [37]:
from src.models.downstream.segmentation import SegmentationProbing
lowrank_model = SegmentationProbing(
    model_backbone=model,
    is_baseline=False,
    feature_key="lowrank",
    feature_dim=768,
    num_classes=2,
    freeze_backbone=True,
    freeze_model=False,
    resize_output=(224, 224),
).to(device)


optimizer = torch.optim.AdamW(filter(lambda p: p.requires_grad,lowrank_model.parameters()),
    lr=1e-3,
    weight_decay=1e-4,)
criterion = torch.nn.CrossEntropyLoss()

In [39]:
import random

history=[]
# def train_spatial_probe(feature_key, seed, num_epochs=50):
def train_spatial_probe(seed, num_epochs=50):
    # Training randomness
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

    # Best checkpoint in memory
    best_val_dice = -1.0
    best_epoch = -1
    best_state = None
    
    # Training
    for epoch in range(num_epochs):
        train_metrics = run_epoch(lowrank_model,probe_train_loader,optimizer=optimizer,
            criterion=criterion,
            device=device,)
        
        val_metrics = run_epoch(lowrank_model,probe_val_loader,optimizer=None,
            criterion=criterion,
            device=device,)

        history.append({
            "epoch": epoch + 1,
            "train_dice": train_metrics["gland_dice"],
            "train_miou": train_metrics["miou"],
            "val_dice": val_metrics["gland_dice"],
            "val_miou": val_metrics["miou"],
        })

        print(
            f"[Seed {seed}] "
            f"Epoch {epoch+1:02d}/{num_epochs} | "
            f"Train Dice: {train_metrics['gland_dice']:.4f} | "
            f"Val Dice: {val_metrics['gland_dice']:.4f}"
        )

        if val_metrics["gland_dice"] > best_val_dice:
            best_val_dice = val_metrics["gland_dice"]
            best_epoch = epoch + 1
            best_state = {
                k: v.detach().cpu().clone()
                for k, v in lowrank_model.state_dict().items()
            }

    """ # Restore best model
        lowrank_model.load_state_dict(best_state)
        lowrank_model.eval()
    
    
        # TestA
        testA_metrics = run_epoch(
            lowrank_model,
            testA_loader,
            optimizer=None,
            criterion=criterion,
            device=device,
        )
    
    
        # TestB
        testB_metrics = run_epoch(
            lowrank_model,
            testB_loader,
            optimizer=None,
            criterion=criterion,
            device=device,
        )
    """
    return {
        "seed": seed,
        "best_epoch": best_epoch,
        "best_val_dice": best_val_dice,
        "history": history,
    }

In [40]:
# Running for 3 SEEDS
lowrank_results = {}
for seed in [42, 123, 2026]:
    print("\n" + "=" * 70)
    print(f"STARTING LOWRANK PROBE — SEED {seed}")
    print("=" * 70)
    lowrank_results[seed] = train_spatial_probe(seed=seed,num_epochs=50,)

======================================================================
STARTING LOWRANK PROBE — SEED 42
======================================================================
[Seed 42] Epoch 01/50 | Train Dice: 0.5756 | Val Dice: 0.6853
[Seed 42] Epoch 02/50 | Train Dice: 0.5939 | Val Dice: 0.7033
[Seed 42] Epoch 03/50 | Train Dice: 0.6085 | Val Dice: 0.6850
[Seed 42] Epoch 04/50 | Train Dice: 0.6167 | Val Dice: 0.6671
[Seed 42] Epoch 05/50 | Train Dice: 0.6686 | Val Dice: 0.6691
[Seed 42] Epoch 06/50 | Train Dice: 0.6204 | Val Dice: 0.5891
[Seed 42] Epoch 07/50 | Train Dice: 0.6024 | Val Dice: 0.6232
[Seed 42] Epoch 08/50 | Train Dice: 0.6297 | Val Dice: 0.6143
[Seed 42] Epoch 09/50 | Train Dice: 0.6395 | Val Dice: 0.6414
[Seed 42] Epoch 10/50 | Train Dice: 0.6517 | Val Dice: 0.6461
[Seed 42] Epoch 11/50 | Train Dice: 0.6359 | Val Dice: 0.6138
[Seed 42] Epoch 12/50 | Train Dice: 0.6481 | Val Dice: 0.6585
[Seed 42] Epoch 13/50 | Train Dice: 0.6726 | Val Dice: 0.6495
[Seed 42] Epoch 14/50 | Train Dice: 0.6495 | Val Dice: 0.6173
[Seed 42] Epoch 15/50 | Train Dice: 0.6538 | Val Dice: 0.6566
[Seed 42] Epoch 16/50 | Train Dice: 0.6546 | Val Dice: 0.6703
[Seed 42] Epoch 17/50 | Train Dice: 0.6806 | Val Dice: 0.6413
[Seed 42] Epoch 18/50 | Train Dice: 0.6568 | Val Dice: 0.5994
[Seed 42] Epoch 19/50 | Train Dice: 0.6553 | Val Dice: 0.6404
[Seed 42] Epoch 20/50 | Train Dice: 0.6578 | Val Dice: 0.6943
[Seed 42] Epoch 21/50 | Train Dice: 0.6548 | Val Dice: 0.6547
[Seed 42] Epoch 22/50 | Train Dice: 0.6738 | Val Dice: 0.6102
[Seed 42] Epoch 23/50 | Train Dice: 0.6635 | Val Dice: 0.6067
[Seed 42] Epoch 24/50 | Train Dice: 0.6589 | Val Dice: 0.6496
[Seed 42] Epoch 25/50 | Train Dice: 0.6662 | Val Dice: 0.6558
[Seed 42] Epoch 26/50 | Train Dice: 0.6738 | Val Dice: 0.6585
[Seed 42] Epoch 27/50 | Train Dice: 0.6812 | Val Dice: 0.6509
[Seed 42] Epoch 28/50 | Train Dice: 0.6731 | Val Dice: 0.6589
[Seed 42] Epoch 29/50 | Train Dice: 0.6805 | Val Dice: 0.5615
[Seed 42] Epoch 30/50 | Train Dice: 0.6623 | Val Dice: 0.6663
[Seed 42] Epoch 31/50 | Train Dice: 0.6538 | Val Dice: 0.6722
[Seed 42] Epoch 32/50 | Train Dice: 0.6581 | Val Dice: 0.6525
[Seed 42] Epoch 33/50 | Train Dice: 0.6555 | Val Dice: 0.6299
[Seed 42] Epoch 34/50 | Train Dice: 0.7018 | Val Dice: 0.6523
[Seed 42] Epoch 35/50 | Train Dice: 0.6805 | Val Dice: 0.6502
[Seed 42] Epoch 36/50 | Train Dice: 0.6700 | Val Dice: 0.6738
[Seed 42] Epoch 37/50 | Train Dice: 0.6809 | Val Dice: 0.6638
[Seed 42] Epoch 38/50 | Train Dice: 0.6784 | Val Dice: 0.6320
[Seed 42] Epoch 39/50 | Train Dice: 0.6751 | Val Dice: 0.6456
[Seed 42] Epoch 40/50 | Train Dice: 0.6703 | Val Dice: 0.6382
[Seed 42] Epoch 41/50 | Train Dice: 0.6720 | Val Dice: 0.6895
[Seed 42] Epoch 42/50 | Train Dice: 0.6466 | Val Dice: 0.6371
[Seed 42] Epoch 43/50 | Train Dice: 0.6691 | Val Dice: 0.6429
[Seed 42] Epoch 44/50 | Train Dice: 0.7019 | Val Dice: 0.6733
[Seed 42] Epoch 45/50 | Train Dice: 0.6868 | Val Dice: 0.6943
[Seed 42] Epoch 46/50 | Train Dice: 0.6744 | Val Dice: 0.6963
[Seed 42] Epoch 47/50 | Train Dice: 0.6828 | Val Dice: 0.6444
[Seed 42] Epoch 48/50 | Train Dice: 0.6630 | Val Dice: 0.6512
[Seed 42] Epoch 49/50 | Train Dice: 0.6850 | Val Dice: 0.6637
[Seed 42] Epoch 50/50 | Train Dice: 0.6842 | Val Dice: 0.6225

======================================================================
STARTING LOWRANK PROBE — SEED 123
======================================================================
[Seed 123] Epoch 01/50 | Train Dice: 0.6625 | Val Dice: 0.6406
[Seed 123] Epoch 02/50 | Train Dice: 0.6748 | Val Dice: 0.6508
[Seed 123] Epoch 03/50 | Train Dice: 0.7102 | Val Dice: 0.6428
[Seed 123] Epoch 04/50 | Train Dice: 0.6867 | Val Dice: 0.6636
[Seed 123] Epoch 05/50 | Train Dice: 0.6845 | Val Dice: 0.6340
[Seed 123] Epoch 06/50 | Train Dice: 0.6717 | Val Dice: 0.6540
[Seed 123] Epoch 07/50 | Train Dice: 0.6569 | Val Dice: 0.6823
[Seed 123] Epoch 08/50 | Train Dice: 0.6633 | Val Dice: 0.6730
[Seed 123] Epoch 09/50 | Train Dice: 0.6750 | Val Dice: 0.6485
[Seed 123] Epoch 10/50 | Train Dice: 0.6868 | Val Dice: 0.6598
[Seed 123] Epoch 11/50 | Train Dice: 0.6803 | Val Dice: 0.6409
[Seed 123] Epoch 12/50 | Train Dice: 0.6856 | Val Dice: 0.6578
[Seed 123] Epoch 13/50 | Train Dice: 0.6442 | Val Dice: 0.5751
[Seed 123] Epoch 14/50 | Train Dice: 0.6778 | Val Dice: 0.5891
[Seed 123] Epoch 15/50 | Train Dice: 0.6773 | Val Dice: 0.6262
[Seed 123] Epoch 16/50 | Train Dice: 0.6733 | Val Dice: 0.6790
[Seed 123] Epoch 17/50 | Train Dice: 0.6976 | Val Dice: 0.7063
[Seed 123] Epoch 18/50 | Train Dice: 0.6584 | Val Dice: 0.6546
[Seed 123] Epoch 19/50 | Train Dice: 0.6709 | Val Dice: 0.6042
[Seed 123] Epoch 20/50 | Train Dice: 0.6708 | Val Dice: 0.6486
[Seed 123] Epoch 21/50 | Train Dice: 0.6867 | Val Dice: 0.6813
[Seed 123] Epoch 22/50 | Train Dice: 0.6893 | Val Dice: 0.6743
[Seed 123] Epoch 23/50 | Train Dice: 0.6803 | Val Dice: 0.6153
[Seed 123] Epoch 24/50 | Train Dice: 0.6845 | Val Dice: 0.6480
[Seed 123] Epoch 25/50 | Train Dice: 0.6571 | Val Dice: 0.6882
[Seed 123] Epoch 26/50 | Train Dice: 0.6742 | Val Dice: 0.6966
[Seed 123] Epoch 27/50 | Train Dice: 0.6583 | Val Dice: 0.6563
[Seed 123] Epoch 28/50 | Train Dice: 0.6879 | Val Dice: 0.6944
[Seed 123] Epoch 29/50 | Train Dice: 0.7048 | Val Dice: 0.6732
[Seed 123] Epoch 30/50 | Train Dice: 0.6649 | Val Dice: 0.6927
[Seed 123] Epoch 31/50 | Train Dice: 0.6844 | Val Dice: 0.6998
[Seed 123] Epoch 32/50 | Train Dice: 0.6647 | Val Dice: 0.6629
[Seed 123] Epoch 33/50 | Train Dice: 0.6819 | Val Dice: 0.6637
[Seed 123] Epoch 34/50 | Train Dice: 0.6836 | Val Dice: 0.6748
[Seed 123] Epoch 35/50 | Train Dice: 0.6858 | Val Dice: 0.6814
[Seed 123] Epoch 36/50 | Train Dice: 0.6643 | Val Dice: 0.6743
[Seed 123] Epoch 37/50 | Train Dice: 0.6753 | Val Dice: 0.6546
[Seed 123] Epoch 38/50 | Train Dice: 0.7033 | Val Dice: 0.6722
[Seed 123] Epoch 39/50 | Train Dice: 0.6689 | Val Dice: 0.6639
[Seed 123] Epoch 40/50 | Train Dice: 0.6847 | Val Dice: 0.6886
[Seed 123] Epoch 41/50 | Train Dice: 0.6927 | Val Dice: 0.6800
[Seed 123] Epoch 42/50 | Train Dice: 0.6779 | Val Dice: 0.7004
[Seed 123] Epoch 43/50 | Train Dice: 0.6939 | Val Dice: 0.6826
[Seed 123] Epoch 44/50 | Train Dice: 0.6867 | Val Dice: 0.6829
[Seed 123] Epoch 45/50 | Train Dice: 0.6903 | Val Dice: 0.6806
[Seed 123] Epoch 46/50 | Train Dice: 0.6781 | Val Dice: 0.6701
[Seed 123] Epoch 47/50 | Train Dice: 0.6898 | Val Dice: 0.6861
[Seed 123] Epoch 48/50 | Train Dice: 0.6897 | Val Dice: 0.6757
[Seed 123] Epoch 49/50 | Train Dice: 0.6771 | Val Dice: 0.6863
[Seed 123] Epoch 50/50 | Train Dice: 0.6730 | Val Dice: 0.6884

======================================================================
STARTING LOWRANK PROBE — SEED 2026
======================================================================
[Seed 2026] Epoch 01/50 | Train Dice: 0.6779 | Val Dice: 0.6755
[Seed 2026] Epoch 02/50 | Train Dice: 0.6809 | Val Dice: 0.6696
[Seed 2026] Epoch 03/50 | Train Dice: 0.6861 | Val Dice: 0.6416
[Seed 2026] Epoch 04/50 | Train Dice: 0.6615 | Val Dice: 0.6770
[Seed 2026] Epoch 05/50 | Train Dice: 0.6913 | Val Dice: 0.6812
[Seed 2026] Epoch 06/50 | Train Dice: 0.6489 | Val Dice: 0.6266
[Seed 2026] Epoch 07/50 | Train Dice: 0.6602 | Val Dice: 0.6838
[Seed 2026] Epoch 08/50 | Train Dice: 0.6949 | Val Dice: 0.6845
[Seed 2026] Epoch 09/50 | Train Dice: 0.6835 | Val Dice: 0.6683
[Seed 2026] Epoch 10/50 | Train Dice: 0.6750 | Val Dice: 0.6726
[Seed 2026] Epoch 11/50 | Train Dice: 0.6808 | Val Dice: 0.6550
[Seed 2026] Epoch 12/50 | Train Dice: 0.6881 | Val Dice: 0.6670
[Seed 2026] Epoch 13/50 | Train Dice: 0.7004 | Val Dice: 0.6479
[Seed 2026] Epoch 14/50 | Train Dice: 0.6800 | Val Dice: 0.6689
[Seed 2026] Epoch 15/50 | Train Dice: 0.6882 | Val Dice: 0.6604
[Seed 2026] Epoch 16/50 | Train Dice: 0.6754 | Val Dice: 0.6794
[Seed 2026] Epoch 17/50 | Train Dice: 0.6824 | Val Dice: 0.6503
[Seed 2026] Epoch 18/50 | Train Dice: 0.6887 | Val Dice: 0.6431
[Seed 2026] Epoch 19/50 | Train Dice: 0.6876 | Val Dice: 0.6824
[Seed 2026] Epoch 20/50 | Train Dice: 0.6697 | Val Dice: 0.6693
[Seed 2026] Epoch 21/50 | Train Dice: 0.6608 | Val Dice: 0.6646
[Seed 2026] Epoch 22/50 | Train Dice: 0.6689 | Val Dice: 0.6678
[Seed 2026] Epoch 23/50 | Train Dice: 0.6768 | Val Dice: 0.7080
[Seed 2026] Epoch 24/50 | Train Dice: 0.6687 | Val Dice: 0.6995
[Seed 2026] Epoch 25/50 | Train Dice: 0.7101 | Val Dice: 0.6909
[Seed 2026] Epoch 26/50 | Train Dice: 0.6924 | Val Dice: 0.6841
[Seed 2026] Epoch 27/50 | Train Dice: 0.7011 | Val Dice: 0.6719
[Seed 2026] Epoch 28/50 | Train Dice: 0.6776 | Val Dice: 0.6693
[Seed 2026] Epoch 29/50 | Train Dice: 0.6707 | Val Dice: 0.6645
[Seed 2026] Epoch 30/50 | Train Dice: 0.6929 | Val Dice: 0.6725
[Seed 2026] Epoch 31/50 | Train Dice: 0.6943 | Val Dice: 0.6754
[Seed 2026] Epoch 32/50 | Train Dice: 0.6994 | Val Dice: 0.7108
[Seed 2026] Epoch 33/50 | Train Dice: 0.6707 | Val Dice: 0.7087
[Seed 2026] Epoch 34/50 | Train Dice: 0.6650 | Val Dice: 0.6912
[Seed 2026] Epoch 35/50 | Train Dice: 0.6929 | Val Dice: 0.6693
[Seed 2026] Epoch 36/50 | Train Dice: 0.6830 | Val Dice: 0.6596
[Seed 2026] Epoch 37/50 | Train Dice: 0.7111 | Val Dice: 0.6411
[Seed 2026] Epoch 38/50 | Train Dice: 0.6795 | Val Dice: 0.6977
[Seed 2026] Epoch 39/50 | Train Dice: 0.6680 | Val Dice: 0.6764
[Seed 2026] Epoch 40/50 | Train Dice: 0.6937 | Val Dice: 0.6489
[Seed 2026] Epoch 41/50 | Train Dice: 0.6924 | Val Dice: 0.6541
[Seed 2026] Epoch 42/50 | Train Dice: 0.6846 | Val Dice: 0.6764
[Seed 2026] Epoch 43/50 | Train Dice: 0.6937 | Val Dice: 0.6794
[Seed 2026] Epoch 44/50 | Train Dice: 0.6727 | Val Dice: 0.6248
[Seed 2026] Epoch 45/50 | Train Dice: 0.6541 | Val Dice: 0.6283
[Seed 2026] Epoch 46/50 | Train Dice: 0.6717 | Val Dice: 0.6296
[Seed 2026] Epoch 47/50 | Train Dice: 0.6870 | Val Dice: 0.6619
[Seed 2026] Epoch 48/50 | Train Dice: 0.6690 | Val Dice: 0.6814
[Seed 2026] Epoch 49/50 | Train Dice: 0.6720 | Val Dice: 0.6575
[Seed 2026] Epoch 50/50 | Train Dice: 0.6878 | Val Dice: 0.6669

In [41]:
# storing values in .csv file
import pandas as pd
history_df = pd.DataFrame(history)
csv_path = "/kaggle/working/stellar_lowrank_glas_probe_3_SEED_history.csv"
history_df.to_csv(csv_path, index=False)

display(history_df.head())

   epoch  train_dice  train_miou  val_dice  val_miou
0      1    0.575565    0.376589  0.685261  0.316555
1      2    0.593883    0.407919  0.703326  0.457497
2      3    0.608490    0.418319  0.684990  0.385232
3      4    0.616734    0.426293  0.667081  0.426876
4      5    0.668614    0.460785  0.669109  0.408712

In [42]:
# Summarize results of lowrank
for seed, result in lowrank_results.items():
    print("\n" + "=" * 60)
    print(f"LOWRANK — SEED {seed}")
    print("=" * 60)
    print(f"Best epoch : {result['best_epoch']}")
    print(f"Val Dice   : {result['best_val_dice']:.4f}")

============================================================
LOWRANK — SEED 42
============================================================
Best epoch : 2
Val Dice   : 0.7033

============================================================
LOWRANK — SEED 123
============================================================
Best epoch : 17
Val Dice   : 0.7063

============================================================
LOWRANK — SEED 2026
============================================================
Best epoch : 32
Val Dice   : 0.7108

### Dense vs Low rank model Comparison

In [ ]:
# Comparison of Dense vs Low rank model

### Feature rank and Effective rank Broilerplate Code

In [43]:
# Feature rank
import torch
def feature_spectrum(x):
    x = x - x.mean(dim=0, keepdim=True)
    _, S, _ = torch.linalg.svd(x,full_matrices=False)
    return S

# Effective rank
def effective_rank(x):
    x = x.float()
    x = x - x.mean(dim=0, keepdim=True)
    _, S, _ = torch.linalg.svd(x,full_matrices=False)
    p = S / (S.sum() + 1e-12)
    entropy = -torch.sum(p * torch.log(p + 1e-12))
    return torch.exp(entropy).item()

In [45]:
# Feature rank and Effective rank of Dense and Low rank model
import torch

batch = next(iter(probe_val_loader))
images = batch["image"].to(device)
with torch.no_grad():
    outputs = model.encode({"image": images})

dense = outputs["dense"]
lowrank = outputs["lowrank"]

# Feature rank
x_dense = dense[0].float()
x_lowrank = lowrank[0].float()

S_dense = feature_spectrum(x_dense)
S_lowrank = feature_spectrum(x_lowrank)

print("Dense rank:", (S_dense > 1e-6).sum().item())
print("Lowrank rank:", (S_lowrank > 1e-6).sum().item())

print("Dense effective rank:",effective_rank(dense[0]))
print("Lowrank effective rank:",effective_rank(lowrank[0]))

Dense rank: 196
Lowrank rank: 24
Dense effective rank: 121.05934143066406
Lowrank effective rank: 8.088129997253418

### Rank Truncation Backbone

In [53]:
def truncate_spatial_rank(features, rank):
    """
    features: [B, N, C]
    N = spatial tokens
    C = feature dimension
    """
    B, N, C = features.shape
    output = []
    
    for b in range(B):
        X = features[b].float()
        
        # Center across spatial locations
        X_mean = X.mean(dim=0, keepdim=True)
        X_centered = X - X_mean

        # SVD
        U, S, Vh = torch.linalg.svd(X_centered,full_matrices=False)
        r = min(rank, S.shape[0])
        X_r = (U[:, :r] @ torch.diag(S[:r]) @ Vh[:r, :])

        # Restore mean
        X_r = X_r + X_mean
        output.append(X_r)
        
    return torch.stack(output)

In [54]:
# Rank truncation backbone (we're not directly changing SegmentationProbing)
class RankTruncatedBackbone(torch.nn.Module):
    def __init__(self, backbone, rank):
        super().__init__()
        self.backbone = backbone
        self.rank = rank

    def encode(self, inputs):
        outputs = self.backbone.encode(inputs)
        dense = outputs["dense"]
        dense_rank = truncate_spatial_rank(dense,self.rank)
        outputs = dict(outputs)
        outputs["dense"] = dense_rank
        return outputs

### Rank-32 Model 3 SEED

In [55]:
import torch.nn as nn
rank32_backbone = RankTruncatedBackbone(model,rank=32)

rank32_model = SegmentationProbing(
    model_backbone=rank32_backbone,
    is_baseline=False,
    feature_key="dense",
    feature_dim=768,
    num_classes=2,
    freeze_backbone=True,
    freeze_model=False,
    resize_output=(224, 224),
).to(device)

optimizer = torch.optim.AdamW(filter(lambda p: p.requires_grad,rank32_model.parameters()),
    lr=1e-3,weight_decay=1e-4,)
criterion = nn.CrossEntropyLoss()

In [56]:
import random

history = []
def train_spatial_probe(seed, num_epochs=50):
    # Training randomness
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    
    # Best checkpoint in memory
    best_val_dice = -1.0
    best_epoch = -1
    best_state = None

    # Training
    for epoch in range(num_epochs):
        train_metrics = run_epoch(rank32_model,probe_train_loader,optimizer=optimizer,
            criterion=criterion,device=device,)

        val_metrics = run_epoch(rank32_model,probe_val_loader,optimizer=None,
            criterion=criterion,device=device,)
        
        history.append({
            "epoch": epoch + 1,
            "train_dice": train_metrics["gland_dice"],
            "train_miou": train_metrics["miou"],
            "val_dice": val_metrics["gland_dice"],
            "val_miou": val_metrics["miou"],
        })

        print(
            f"[Seed {seed}] "
            f"Epoch {epoch+1:02d}/{num_epochs} | "
            f"Train Dice: {train_metrics['gland_dice']:.4f} | "
            f"Val Dice: {val_metrics['gland_dice']:.4f}"
        )

        if val_metrics["gland_dice"] > best_val_dice:
            best_val_dice = val_metrics["gland_dice"]
            best_epoch = epoch + 1
            best_state = {
                k: v.detach().cpu().clone()
                for k, v in rank32_model.state_dict().items()
            }

    
    """ # Restore best model
        rank32_model.load_state_dict(best_state)
        rank32_model.eval()
        
        # TestA
        testA_metrics = run_epoch(
            rank32_model,
            testA_loader,
            optimizer=None,
            criterion=criterion,
            device=device,
        )

        # TestB
        testB_metrics = run_epoch(
            rank32_model,
            testB_loader,
            optimizer=None,
            criterion=criterion,
            device=device,
        )
    """
    return {
        "seed": seed,
        "best_epoch": best_epoch,
        "best_val_dice": best_val_dice,
        "history": history,
    }

In [57]:
rank32_results = {}

for seed in [42, 123, 2026]:
    print("\n" + "=" * 70)
    print(f"STARTING RANK-32 PROBE — SEED {seed}")
    print("=" * 70)
    rank32_results[seed] = train_spatial_probe(seed=seed,num_epochs=50,)

======================================================================
STARTING LOWRANK PROBE — SEED 42
======================================================================
[Seed 42] Epoch 01/50 | Train Dice: 0.7267 | Val Dice: 0.7822
[Seed 42] Epoch 02/50 | Train Dice: 0.7974 | Val Dice: 0.7931
[Seed 42] Epoch 03/50 | Train Dice: 0.8011 | Val Dice: 0.8107
[Seed 42] Epoch 04/50 | Train Dice: 0.8169 | Val Dice: 0.8111
[Seed 42] Epoch 05/50 | Train Dice: 0.8168 | Val Dice: 0.8254
[Seed 42] Epoch 06/50 | Train Dice: 0.8306 | Val Dice: 0.8310
[Seed 42] Epoch 07/50 | Train Dice: 0.8274 | Val Dice: 0.8287
[Seed 42] Epoch 08/50 | Train Dice: 0.8251 | Val Dice: 0.8337
[Seed 42] Epoch 09/50 | Train Dice: 0.8318 | Val Dice: 0.8342
[Seed 42] Epoch 10/50 | Train Dice: 0.8314 | Val Dice: 0.8331
[Seed 42] Epoch 11/50 | Train Dice: 0.8275 | Val Dice: 0.8286
[Seed 42] Epoch 12/50 | Train Dice: 0.8370 | Val Dice: 0.8275
[Seed 42] Epoch 13/50 | Train Dice: 0.8333 | Val Dice: 0.8311
[Seed 42] Epoch 14/50 | Train Dice: 0.8417 | Val Dice: 0.8293
[Seed 42] Epoch 15/50 | Train Dice: 0.8467 | Val Dice: 0.8353
[Seed 42] Epoch 16/50 | Train Dice: 0.8402 | Val Dice: 0.8400
[Seed 42] Epoch 17/50 | Train Dice: 0.8390 | Val Dice: 0.8387
[Seed 42] Epoch 18/50 | Train Dice: 0.8308 | Val Dice: 0.8328
[Seed 42] Epoch 19/50 | Train Dice: 0.8387 | Val Dice: 0.8377
[Seed 42] Epoch 20/50 | Train Dice: 0.8467 | Val Dice: 0.8400
[Seed 42] Epoch 21/50 | Train Dice: 0.8423 | Val Dice: 0.8359
[Seed 42] Epoch 22/50 | Train Dice: 0.8399 | Val Dice: 0.8415
[Seed 42] Epoch 23/50 | Train Dice: 0.8512 | Val Dice: 0.8375
[Seed 42] Epoch 24/50 | Train Dice: 0.8500 | Val Dice: 0.8399
[Seed 42] Epoch 25/50 | Train Dice: 0.8399 | Val Dice: 0.8395
[Seed 42] Epoch 26/50 | Train Dice: 0.8475 | Val Dice: 0.8327
[Seed 42] Epoch 27/50 | Train Dice: 0.8428 | Val Dice: 0.8356
[Seed 42] Epoch 28/50 | Train Dice: 0.8533 | Val Dice: 0.8369
[Seed 42] Epoch 29/50 | Train Dice: 0.8554 | Val Dice: 0.8335
[Seed 42] Epoch 30/50 | Train Dice: 0.8329 | Val Dice: 0.8357
[Seed 42] Epoch 31/50 | Train Dice: 0.8452 | Val Dice: 0.8369
[Seed 42] Epoch 32/50 | Train Dice: 0.8443 | Val Dice: 0.8424
[Seed 42] Epoch 33/50 | Train Dice: 0.8392 | Val Dice: 0.8274
[Seed 42] Epoch 34/50 | Train Dice: 0.8581 | Val Dice: 0.8342
[Seed 42] Epoch 35/50 | Train Dice: 0.8387 | Val Dice: 0.8284
[Seed 42] Epoch 36/50 | Train Dice: 0.8422 | Val Dice: 0.8385
[Seed 42] Epoch 37/50 | Train Dice: 0.8406 | Val Dice: 0.8412
[Seed 42] Epoch 38/50 | Train Dice: 0.8445 | Val Dice: 0.8412
[Seed 42] Epoch 39/50 | Train Dice: 0.8423 | Val Dice: 0.8431
[Seed 42] Epoch 40/50 | Train Dice: 0.8368 | Val Dice: 0.8411
[Seed 42] Epoch 41/50 | Train Dice: 0.8397 | Val Dice: 0.8507
[Seed 42] Epoch 42/50 | Train Dice: 0.8494 | Val Dice: 0.8498
[Seed 42] Epoch 43/50 | Train Dice: 0.8419 | Val Dice: 0.8417
[Seed 42] Epoch 44/50 | Train Dice: 0.8487 | Val Dice: 0.8470
[Seed 42] Epoch 45/50 | Train Dice: 0.8527 | Val Dice: 0.8423
[Seed 42] Epoch 46/50 | Train Dice: 0.8505 | Val Dice: 0.8488
[Seed 42] Epoch 47/50 | Train Dice: 0.8464 | Val Dice: 0.8417
[Seed 42] Epoch 48/50 | Train Dice: 0.8426 | Val Dice: 0.8407
[Seed 42] Epoch 49/50 | Train Dice: 0.8371 | Val Dice: 0.8459
[Seed 42] Epoch 50/50 | Train Dice: 0.8427 | Val Dice: 0.8478

======================================================================
STARTING LOWRANK PROBE — SEED 123
======================================================================
[Seed 123] Epoch 01/50 | Train Dice: 0.8478 | Val Dice: 0.8501
[Seed 123] Epoch 02/50 | Train Dice: 0.8567 | Val Dice: 0.8410
[Seed 123] Epoch 03/50 | Train Dice: 0.8466 | Val Dice: 0.8425
[Seed 123] Epoch 04/50 | Train Dice: 0.8403 | Val Dice: 0.8349
[Seed 123] Epoch 05/50 | Train Dice: 0.8510 | Val Dice: 0.8522
[Seed 123] Epoch 06/50 | Train Dice: 0.8460 | Val Dice: 0.8537
[Seed 123] Epoch 07/50 | Train Dice: 0.8355 | Val Dice: 0.8475
[Seed 123] Epoch 08/50 | Train Dice: 0.8460 | Val Dice: 0.8451
[Seed 123] Epoch 09/50 | Train Dice: 0.8488 | Val Dice: 0.8467
[Seed 123] Epoch 10/50 | Train Dice: 0.8486 | Val Dice: 0.8390
[Seed 123] Epoch 11/50 | Train Dice: 0.8540 | Val Dice: 0.8478
[Seed 123] Epoch 12/50 | Train Dice: 0.8528 | Val Dice: 0.8502
[Seed 123] Epoch 13/50 | Train Dice: 0.8262 | Val Dice: 0.8340
[Seed 123] Epoch 14/50 | Train Dice: 0.8481 | Val Dice: 0.8496
[Seed 123] Epoch 15/50 | Train Dice: 0.8464 | Val Dice: 0.8476
[Seed 123] Epoch 16/50 | Train Dice: 0.8548 | Val Dice: 0.8487
[Seed 123] Epoch 17/50 | Train Dice: 0.8574 | Val Dice: 0.8422
[Seed 123] Epoch 18/50 | Train Dice: 0.8551 | Val Dice: 0.8418
[Seed 123] Epoch 19/50 | Train Dice: 0.8538 | Val Dice: 0.8401
[Seed 123] Epoch 20/50 | Train Dice: 0.8459 | Val Dice: 0.8427
[Seed 123] Epoch 21/50 | Train Dice: 0.8557 | Val Dice: 0.8459
[Seed 123] Epoch 22/50 | Train Dice: 0.8501 | Val Dice: 0.8373
[Seed 123] Epoch 23/50 | Train Dice: 0.8517 | Val Dice: 0.8484
[Seed 123] Epoch 24/50 | Train Dice: 0.8488 | Val Dice: 0.8424
[Seed 123] Epoch 25/50 | Train Dice: 0.8407 | Val Dice: 0.8389
[Seed 123] Epoch 26/50 | Train Dice: 0.8427 | Val Dice: 0.8414
[Seed 123] Epoch 27/50 | Train Dice: 0.8538 | Val Dice: 0.8509
[Seed 123] Epoch 28/50 | Train Dice: 0.8457 | Val Dice: 0.8501
[Seed 123] Epoch 29/50 | Train Dice: 0.8505 | Val Dice: 0.8503
[Seed 123] Epoch 30/50 | Train Dice: 0.8363 | Val Dice: 0.8481
[Seed 123] Epoch 31/50 | Train Dice: 0.8443 | Val Dice: 0.8494
[Seed 123] Epoch 32/50 | Train Dice: 0.8375 | Val Dice: 0.8516
[Seed 123] Epoch 33/50 | Train Dice: 0.8479 | Val Dice: 0.8528
[Seed 123] Epoch 34/50 | Train Dice: 0.8379 | Val Dice: 0.8386
[Seed 123] Epoch 35/50 | Train Dice: 0.8509 | Val Dice: 0.8424
[Seed 123] Epoch 36/50 | Train Dice: 0.8442 | Val Dice: 0.8468
[Seed 123] Epoch 37/50 | Train Dice: 0.8493 | Val Dice: 0.8488
[Seed 123] Epoch 38/50 | Train Dice: 0.8502 | Val Dice: 0.8448
[Seed 123] Epoch 39/50 | Train Dice: 0.8501 | Val Dice: 0.8493
[Seed 123] Epoch 40/50 | Train Dice: 0.8474 | Val Dice: 0.8391
[Seed 123] Epoch 41/50 | Train Dice: 0.8541 | Val Dice: 0.8344
[Seed 123] Epoch 42/50 | Train Dice: 0.8483 | Val Dice: 0.8463
[Seed 123] Epoch 43/50 | Train Dice: 0.8468 | Val Dice: 0.8460
[Seed 123] Epoch 44/50 | Train Dice: 0.8473 | Val Dice: 0.8425
[Seed 123] Epoch 45/50 | Train Dice: 0.8499 | Val Dice: 0.8495
[Seed 123] Epoch 46/50 | Train Dice: 0.8511 | Val Dice: 0.8493
[Seed 123] Epoch 47/50 | Train Dice: 0.8499 | Val Dice: 0.8458
[Seed 123] Epoch 48/50 | Train Dice: 0.8596 | Val Dice: 0.8504
[Seed 123] Epoch 49/50 | Train Dice: 0.8463 | Val Dice: 0.8460
[Seed 123] Epoch 50/50 | Train Dice: 0.8416 | Val Dice: 0.8462

======================================================================
STARTING LOWRANK PROBE — SEED 2026
======================================================================
[Seed 2026] Epoch 01/50 | Train Dice: 0.8426 | Val Dice: 0.8424
[Seed 2026] Epoch 02/50 | Train Dice: 0.8498 | Val Dice: 0.8428
[Seed 2026] Epoch 03/50 | Train Dice: 0.8516 | Val Dice: 0.8425
[Seed 2026] Epoch 04/50 | Train Dice: 0.8421 | Val Dice: 0.8392
[Seed 2026] Epoch 05/50 | Train Dice: 0.8480 | Val Dice: 0.8480
[Seed 2026] Epoch 06/50 | Train Dice: 0.8410 | Val Dice: 0.8472
[Seed 2026] Epoch 07/50 | Train Dice: 0.8532 | Val Dice: 0.8518
[Seed 2026] Epoch 08/50 | Train Dice: 0.8519 | Val Dice: 0.8504
[Seed 2026] Epoch 09/50 | Train Dice: 0.8399 | Val Dice: 0.8479
[Seed 2026] Epoch 10/50 | Train Dice: 0.8560 | Val Dice: 0.8489
[Seed 2026] Epoch 11/50 | Train Dice: 0.8525 | Val Dice: 0.8496
[Seed 2026] Epoch 12/50 | Train Dice: 0.8564 | Val Dice: 0.8466
[Seed 2026] Epoch 13/50 | Train Dice: 0.8550 | Val Dice: 0.8493
[Seed 2026] Epoch 14/50 | Train Dice: 0.8513 | Val Dice: 0.8509
[Seed 2026] Epoch 15/50 | Train Dice: 0.8465 | Val Dice: 0.8500
[Seed 2026] Epoch 16/50 | Train Dice: 0.8449 | Val Dice: 0.8399
[Seed 2026] Epoch 17/50 | Train Dice: 0.8518 | Val Dice: 0.8470
[Seed 2026] Epoch 18/50 | Train Dice: 0.8479 | Val Dice: 0.8391
[Seed 2026] Epoch 19/50 | Train Dice: 0.8435 | Val Dice: 0.8499
[Seed 2026] Epoch 20/50 | Train Dice: 0.8417 | Val Dice: 0.8462
[Seed 2026] Epoch 21/50 | Train Dice: 0.8464 | Val Dice: 0.8527
[Seed 2026] Epoch 22/50 | Train Dice: 0.8539 | Val Dice: 0.8502
[Seed 2026] Epoch 23/50 | Train Dice: 0.8426 | Val Dice: 0.8491
[Seed 2026] Epoch 24/50 | Train Dice: 0.8467 | Val Dice: 0.8491
[Seed 2026] Epoch 25/50 | Train Dice: 0.8525 | Val Dice: 0.8471
[Seed 2026] Epoch 26/50 | Train Dice: 0.8549 | Val Dice: 0.8431
[Seed 2026] Epoch 27/50 | Train Dice: 0.8541 | Val Dice: 0.8313
[Seed 2026] Epoch 28/50 | Train Dice: 0.8450 | Val Dice: 0.8315
[Seed 2026] Epoch 29/50 | Train Dice: 0.8447 | Val Dice: 0.8444
[Seed 2026] Epoch 30/50 | Train Dice: 0.8477 | Val Dice: 0.8459
[Seed 2026] Epoch 31/50 | Train Dice: 0.8465 | Val Dice: 0.8455
[Seed 2026] Epoch 32/50 | Train Dice: 0.8515 | Val Dice: 0.8455
[Seed 2026] Epoch 33/50 | Train Dice: 0.8383 | Val Dice: 0.8478
[Seed 2026] Epoch 34/50 | Train Dice: 0.8305 | Val Dice: 0.8461
[Seed 2026] Epoch 35/50 | Train Dice: 0.8530 | Val Dice: 0.8427
[Seed 2026] Epoch 36/50 | Train Dice: 0.8534 | Val Dice: 0.8449
[Seed 2026] Epoch 37/50 | Train Dice: 0.8587 | Val Dice: 0.8418
[Seed 2026] Epoch 38/50 | Train Dice: 0.8443 | Val Dice: 0.8429
[Seed 2026] Epoch 39/50 | Train Dice: 0.8559 | Val Dice: 0.8438
[Seed 2026] Epoch 40/50 | Train Dice: 0.8516 | Val Dice: 0.8439
[Seed 2026] Epoch 41/50 | Train Dice: 0.8538 | Val Dice: 0.8436
[Seed 2026] Epoch 42/50 | Train Dice: 0.8503 | Val Dice: 0.8460
[Seed 2026] Epoch 43/50 | Train Dice: 0.8518 | Val Dice: 0.8412
[Seed 2026] Epoch 44/50 | Train Dice: 0.8376 | Val Dice: 0.8400
[Seed 2026] Epoch 45/50 | Train Dice: 0.8496 | Val Dice: 0.8462
[Seed 2026] Epoch 46/50 | Train Dice: 0.8453 | Val Dice: 0.8392
[Seed 2026] Epoch 47/50 | Train Dice: 0.8477 | Val Dice: 0.8431
[Seed 2026] Epoch 48/50 | Train Dice: 0.8518 | Val Dice: 0.8426
[Seed 2026] Epoch 49/50 | Train Dice: 0.8511 | Val Dice: 0.8346
[Seed 2026] Epoch 50/50 | Train Dice: 0.8512 | Val Dice: 0.8443

In [58]:
# storing values into .csv file
import pandas as pd

history_df = pd.DataFrame(history)
csv_path = "/kaggle/working/stellar_rank32_glas_probe_3_SEED_history.csv"
history_df.to_csv(csv_path, index=False)

display(history_df.head())

   epoch  train_dice  train_miou  val_dice  val_miou
0      1    0.726652    0.549768  0.782203  0.614699
1      2    0.797403    0.656159  0.793134  0.649338
2      3    0.801064    0.658561  0.810676  0.674419
3      4    0.816922    0.680412  0.811122  0.681192
4      5    0.816797    0.680826  0.825370  0.688788

In [59]:
# Summarize results of lowrank
for seed, result in rank32_results.items():
    print("\n" + "=" * 60)
    print(f"RANK-32 — SEED {seed}")
    print("=" * 60)
    print(f"Best epoch : {result['best_epoch']}")
    print(f"Val Dice   : {result['best_val_dice']:.4f}")

============================================================
RANK-32 — SEED 42
============================================================
Best epoch : 41
Val Dice   : 0.8507

============================================================
RANK-32 — SEED 123
============================================================
Best epoch : 6
Val Dice   : 0.8537

============================================================
RANK-32 — SEED 2026
============================================================
Best epoch : 21
Val Dice   : 0.8527

In [62]:
# Feature rank and Effective rank for Rank-32 model
import torch

batch = next(iter(probe_val_loader))
images = batch["image"].to(device)
with torch.no_grad():
    outputs = rank32_backbone.encode({"image": images})

rank32_features = outputs["dense"]
X = rank32_features[0]

# Center exactly as done during truncation
X_centered = X - X.mean(dim=0, keepdim=True)
S = torch.linalg.svdvals(X_centered)
numerical_rank = (S > 1e-5).sum().item()
print("Numerical rank:", numerical_rank)
print("Rank-32 effective rank:",effective_rank(rank32_features[0]))

Numerical rank: 32
Rank-32 effective rank: 26.149513244628906

### Rank-64 Model 3 SEED

In [78]:
import torch.nn as nn
rank64_backbone = RankTruncatedBackbone(model,rank=64)

rank64_model = SegmentationProbing(
    model_backbone=rank64_backbone,
    is_baseline=False,
    feature_key="dense",
    feature_dim=768,
    num_classes=2,
    freeze_backbone=True,
    freeze_model=False,
    resize_output=(224, 224),
).to(device)

optimizer = torch.optim.AdamW(filter(lambda p: p.requires_grad,rank64_model.parameters()),
    lr=1e-3,weight_decay=1e-4,)
criterion = nn.CrossEntropyLoss()

In [79]:
import random

history = []
def train_spatial_probe(seed, num_epochs=50):
    # Training randomness
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    
    # Best checkpoint in memory
    best_val_dice = -1.0
    best_epoch = -1
    best_state = None

    # Training
    for epoch in range(num_epochs):
        train_metrics = run_epoch(rank64_model,probe_train_loader,optimizer=optimizer,
            criterion=criterion,device=device,)

        val_metrics = run_epoch(rank64_model,probe_val_loader,optimizer=None,
            criterion=criterion,device=device,)
        
        history.append({
            "epoch": epoch + 1,
            "train_dice": train_metrics["gland_dice"],
            "train_miou": train_metrics["miou"],
            "val_dice": val_metrics["gland_dice"],
            "val_miou": val_metrics["miou"],
        })

        print(
            f"[Seed {seed}] "
            f"Epoch {epoch+1:02d}/{num_epochs} | "
            f"Train Dice: {train_metrics['gland_dice']:.4f} | "
            f"Val Dice: {val_metrics['gland_dice']:.4f}"
        )

        if val_metrics["gland_dice"] > best_val_dice:
            best_val_dice = val_metrics["gland_dice"]
            best_epoch = epoch + 1
            best_state = {
                k: v.detach().cpu().clone()
                for k, v in rank64_model.state_dict().items()
            }

    
    """ # Restore best model
        rank32_model.load_state_dict(best_state)
        rank32_model.eval()
        
        # TestA
        testA_metrics = run_epoch(
            rank32_model,
            testA_loader,
            optimizer=None,
            criterion=criterion,
            device=device,
        )

        # TestB
        testB_metrics = run_epoch(
            rank32_model,
            testB_loader,
            optimizer=None,
            criterion=criterion,
            device=device,
        )
    """
    return {
        "seed": seed,
        "best_epoch": best_epoch,
        "best_val_dice": best_val_dice,
        "history": history,
    }

In [80]:
rank64_results = {}

for seed in [42, 123, 2026]:
    print("\n" + "=" * 70)
    print(f"STARTING RANK-64 PROBE — SEED {seed}")
    print("=" * 70)
    rank64_results[seed] = train_spatial_probe(seed=seed,num_epochs=50,)

======================================================================
STARTING RANK-64 PROBE — SEED 42
======================================================================
[Seed 42] Epoch 01/50 | Train Dice: 0.7008 | Val Dice: 0.7862
[Seed 42] Epoch 02/50 | Train Dice: 0.7899 | Val Dice: 0.8040
[Seed 42] Epoch 03/50 | Train Dice: 0.7988 | Val Dice: 0.8109
[Seed 42] Epoch 04/50 | Train Dice: 0.8156 | Val Dice: 0.8141
[Seed 42] Epoch 05/50 | Train Dice: 0.8189 | Val Dice: 0.8317
[Seed 42] Epoch 06/50 | Train Dice: 0.8310 | Val Dice: 0.8363
[Seed 42] Epoch 07/50 | Train Dice: 0.8258 | Val Dice: 0.8352
[Seed 42] Epoch 08/50 | Train Dice: 0.8262 | Val Dice: 0.8383
[Seed 42] Epoch 09/50 | Train Dice: 0.8366 | Val Dice: 0.8360
[Seed 42] Epoch 10/50 | Train Dice: 0.8328 | Val Dice: 0.8358
[Seed 42] Epoch 11/50 | Train Dice: 0.8299 | Val Dice: 0.8316
[Seed 42] Epoch 12/50 | Train Dice: 0.8378 | Val Dice: 0.8320
[Seed 42] Epoch 13/50 | Train Dice: 0.8374 | Val Dice: 0.8351
[Seed 42] Epoch 14/50 | Train Dice: 0.8444 | Val Dice: 0.8339
[Seed 42] Epoch 15/50 | Train Dice: 0.8485 | Val Dice: 0.8412
[Seed 42] Epoch 16/50 | Train Dice: 0.8419 | Val Dice: 0.8466
[Seed 42] Epoch 17/50 | Train Dice: 0.8415 | Val Dice: 0.8461
[Seed 42] Epoch 18/50 | Train Dice: 0.8329 | Val Dice: 0.8388
[Seed 42] Epoch 19/50 | Train Dice: 0.8447 | Val Dice: 0.8461
[Seed 42] Epoch 20/50 | Train Dice: 0.8506 | Val Dice: 0.8445
[Seed 42] Epoch 21/50 | Train Dice: 0.8444 | Val Dice: 0.8407
[Seed 42] Epoch 22/50 | Train Dice: 0.8396 | Val Dice: 0.8453
[Seed 42] Epoch 23/50 | Train Dice: 0.8549 | Val Dice: 0.8410
[Seed 42] Epoch 24/50 | Train Dice: 0.8523 | Val Dice: 0.8451
[Seed 42] Epoch 25/50 | Train Dice: 0.8429 | Val Dice: 0.8451
[Seed 42] Epoch 26/50 | Train Dice: 0.8533 | Val Dice: 0.8406
[Seed 42] Epoch 27/50 | Train Dice: 0.8473 | Val Dice: 0.8409
[Seed 42] Epoch 28/50 | Train Dice: 0.8532 | Val Dice: 0.8427
[Seed 42] Epoch 29/50 | Train Dice: 0.8612 | Val Dice: 0.8390
[Seed 42] Epoch 30/50 | Train Dice: 0.8377 | Val Dice: 0.8413
[Seed 42] Epoch 31/50 | Train Dice: 0.8512 | Val Dice: 0.8420
[Seed 42] Epoch 32/50 | Train Dice: 0.8496 | Val Dice: 0.8464
[Seed 42] Epoch 33/50 | Train Dice: 0.8428 | Val Dice: 0.8354
[Seed 42] Epoch 34/50 | Train Dice: 0.8626 | Val Dice: 0.8413
[Seed 42] Epoch 35/50 | Train Dice: 0.8419 | Val Dice: 0.8359
[Seed 42] Epoch 36/50 | Train Dice: 0.8482 | Val Dice: 0.8421
[Seed 42] Epoch 37/50 | Train Dice: 0.8414 | Val Dice: 0.8459
[Seed 42] Epoch 38/50 | Train Dice: 0.8491 | Val Dice: 0.8466
[Seed 42] Epoch 39/50 | Train Dice: 0.8462 | Val Dice: 0.8494
[Seed 42] Epoch 40/50 | Train Dice: 0.8417 | Val Dice: 0.8460
[Seed 42] Epoch 41/50 | Train Dice: 0.8438 | Val Dice: 0.8561
[Seed 42] Epoch 42/50 | Train Dice: 0.8526 | Val Dice: 0.8495
[Seed 42] Epoch 43/50 | Train Dice: 0.8461 | Val Dice: 0.8469
[Seed 42] Epoch 44/50 | Train Dice: 0.8534 | Val Dice: 0.8517
[Seed 42] Epoch 45/50 | Train Dice: 0.8583 | Val Dice: 0.8469
[Seed 42] Epoch 46/50 | Train Dice: 0.8535 | Val Dice: 0.8527
[Seed 42] Epoch 47/50 | Train Dice: 0.8504 | Val Dice: 0.8470
[Seed 42] Epoch 48/50 | Train Dice: 0.8464 | Val Dice: 0.8475
[Seed 42] Epoch 49/50 | Train Dice: 0.8450 | Val Dice: 0.8516
[Seed 42] Epoch 50/50 | Train Dice: 0.8476 | Val Dice: 0.8513

======================================================================
STARTING RANK-64 PROBE — SEED 123
======================================================================
[Seed 123] Epoch 01/50 | Train Dice: 0.8496 | Val Dice: 0.8536
[Seed 123] Epoch 02/50 | Train Dice: 0.8627 | Val Dice: 0.8489
[Seed 123] Epoch 03/50 | Train Dice: 0.8540 | Val Dice: 0.8495
[Seed 123] Epoch 04/50 | Train Dice: 0.8466 | Val Dice: 0.8426
[Seed 123] Epoch 05/50 | Train Dice: 0.8533 | Val Dice: 0.8534
[Seed 123] Epoch 06/50 | Train Dice: 0.8489 | Val Dice: 0.8550
[Seed 123] Epoch 07/50 | Train Dice: 0.8390 | Val Dice: 0.8502
[Seed 123] Epoch 08/50 | Train Dice: 0.8504 | Val Dice: 0.8501
[Seed 123] Epoch 09/50 | Train Dice: 0.8539 | Val Dice: 0.8511
[Seed 123] Epoch 10/50 | Train Dice: 0.8509 | Val Dice: 0.8447
[Seed 123] Epoch 11/50 | Train Dice: 0.8583 | Val Dice: 0.8523
[Seed 123] Epoch 12/50 | Train Dice: 0.8595 | Val Dice: 0.8520
[Seed 123] Epoch 13/50 | Train Dice: 0.8329 | Val Dice: 0.8351
[Seed 123] Epoch 14/50 | Train Dice: 0.8544 | Val Dice: 0.8524
[Seed 123] Epoch 15/50 | Train Dice: 0.8504 | Val Dice: 0.8518
[Seed 123] Epoch 16/50 | Train Dice: 0.8600 | Val Dice: 0.8533
[Seed 123] Epoch 17/50 | Train Dice: 0.8608 | Val Dice: 0.8463
[Seed 123] Epoch 18/50 | Train Dice: 0.8573 | Val Dice: 0.8460
[Seed 123] Epoch 19/50 | Train Dice: 0.8552 | Val Dice: 0.8447
[Seed 123] Epoch 20/50 | Train Dice: 0.8496 | Val Dice: 0.8489
[Seed 123] Epoch 21/50 | Train Dice: 0.8592 | Val Dice: 0.8458
[Seed 123] Epoch 22/50 | Train Dice: 0.8563 | Val Dice: 0.8405
[Seed 123] Epoch 23/50 | Train Dice: 0.8560 | Val Dice: 0.8512
[Seed 123] Epoch 24/50 | Train Dice: 0.8516 | Val Dice: 0.8455
[Seed 123] Epoch 25/50 | Train Dice: 0.8455 | Val Dice: 0.8453
[Seed 123] Epoch 26/50 | Train Dice: 0.8490 | Val Dice: 0.8467
[Seed 123] Epoch 27/50 | Train Dice: 0.8573 | Val Dice: 0.8539
[Seed 123] Epoch 28/50 | Train Dice: 0.8493 | Val Dice: 0.8530
[Seed 123] Epoch 29/50 | Train Dice: 0.8524 | Val Dice: 0.8516
[Seed 123] Epoch 30/50 | Train Dice: 0.8424 | Val Dice: 0.8531
[Seed 123] Epoch 31/50 | Train Dice: 0.8497 | Val Dice: 0.8517
[Seed 123] Epoch 32/50 | Train Dice: 0.8410 | Val Dice: 0.8552
[Seed 123] Epoch 33/50 | Train Dice: 0.8500 | Val Dice: 0.8535
[Seed 123] Epoch 34/50 | Train Dice: 0.8435 | Val Dice: 0.8461
[Seed 123] Epoch 35/50 | Train Dice: 0.8560 | Val Dice: 0.8474
[Seed 123] Epoch 36/50 | Train Dice: 0.8488 | Val Dice: 0.8515
[Seed 123] Epoch 37/50 | Train Dice: 0.8538 | Val Dice: 0.8533
[Seed 123] Epoch 38/50 | Train Dice: 0.8560 | Val Dice: 0.8503
[Seed 123] Epoch 39/50 | Train Dice: 0.8563 | Val Dice: 0.8540
[Seed 123] Epoch 40/50 | Train Dice: 0.8513 | Val Dice: 0.8476
[Seed 123] Epoch 41/50 | Train Dice: 0.8594 | Val Dice: 0.8431
[Seed 123] Epoch 42/50 | Train Dice: 0.8536 | Val Dice: 0.8508
[Seed 123] Epoch 43/50 | Train Dice: 0.8520 | Val Dice: 0.8502
[Seed 123] Epoch 44/50 | Train Dice: 0.8532 | Val Dice: 0.8501
[Seed 123] Epoch 45/50 | Train Dice: 0.8557 | Val Dice: 0.8539
[Seed 123] Epoch 46/50 | Train Dice: 0.8539 | Val Dice: 0.8529
[Seed 123] Epoch 47/50 | Train Dice: 0.8545 | Val Dice: 0.8485
[Seed 123] Epoch 48/50 | Train Dice: 0.8655 | Val Dice: 0.8522
[Seed 123] Epoch 49/50 | Train Dice: 0.8514 | Val Dice: 0.8524
[Seed 123] Epoch 50/50 | Train Dice: 0.8481 | Val Dice: 0.8518

======================================================================
STARTING RANK-64 PROBE — SEED 2026
======================================================================
[Seed 2026] Epoch 01/50 | Train Dice: 0.8481 | Val Dice: 0.8484
[Seed 2026] Epoch 02/50 | Train Dice: 0.8539 | Val Dice: 0.8492
[Seed 2026] Epoch 03/50 | Train Dice: 0.8546 | Val Dice: 0.8454
[Seed 2026] Epoch 04/50 | Train Dice: 0.8472 | Val Dice: 0.8443
[Seed 2026] Epoch 05/50 | Train Dice: 0.8530 | Val Dice: 0.8516
[Seed 2026] Epoch 06/50 | Train Dice: 0.8440 | Val Dice: 0.8525
[Seed 2026] Epoch 07/50 | Train Dice: 0.8591 | Val Dice: 0.8546
[Seed 2026] Epoch 08/50 | Train Dice: 0.8545 | Val Dice: 0.8536
[Seed 2026] Epoch 09/50 | Train Dice: 0.8479 | Val Dice: 0.8523
[Seed 2026] Epoch 10/50 | Train Dice: 0.8597 | Val Dice: 0.8535
[Seed 2026] Epoch 11/50 | Train Dice: 0.8588 | Val Dice: 0.8547
[Seed 2026] Epoch 12/50 | Train Dice: 0.8597 | Val Dice: 0.8525
[Seed 2026] Epoch 13/50 | Train Dice: 0.8608 | Val Dice: 0.8527
[Seed 2026] Epoch 14/50 | Train Dice: 0.8562 | Val Dice: 0.8527
[Seed 2026] Epoch 15/50 | Train Dice: 0.8518 | Val Dice: 0.8542
[Seed 2026] Epoch 16/50 | Train Dice: 0.8481 | Val Dice: 0.8465
[Seed 2026] Epoch 17/50 | Train Dice: 0.8574 | Val Dice: 0.8515
[Seed 2026] Epoch 18/50 | Train Dice: 0.8522 | Val Dice: 0.8472
[Seed 2026] Epoch 19/50 | Train Dice: 0.8454 | Val Dice: 0.8533
[Seed 2026] Epoch 20/50 | Train Dice: 0.8487 | Val Dice: 0.8524
[Seed 2026] Epoch 21/50 | Train Dice: 0.8461 | Val Dice: 0.8558
[Seed 2026] Epoch 22/50 | Train Dice: 0.8577 | Val Dice: 0.8543
[Seed 2026] Epoch 23/50 | Train Dice: 0.8483 | Val Dice: 0.8511
[Seed 2026] Epoch 24/50 | Train Dice: 0.8507 | Val Dice: 0.8536
[Seed 2026] Epoch 25/50 | Train Dice: 0.8566 | Val Dice: 0.8514
[Seed 2026] Epoch 26/50 | Train Dice: 0.8581 | Val Dice: 0.8496
[Seed 2026] Epoch 27/50 | Train Dice: 0.8595 | Val Dice: 0.8384
[Seed 2026] Epoch 28/50 | Train Dice: 0.8459 | Val Dice: 0.8418
[Seed 2026] Epoch 29/50 | Train Dice: 0.8485 | Val Dice: 0.8500
[Seed 2026] Epoch 30/50 | Train Dice: 0.8506 | Val Dice: 0.8494
[Seed 2026] Epoch 31/50 | Train Dice: 0.8519 | Val Dice: 0.8533
[Seed 2026] Epoch 32/50 | Train Dice: 0.8573 | Val Dice: 0.8530
[Seed 2026] Epoch 33/50 | Train Dice: 0.8410 | Val Dice: 0.8546
[Seed 2026] Epoch 34/50 | Train Dice: 0.8364 | Val Dice: 0.8519
[Seed 2026] Epoch 35/50 | Train Dice: 0.8571 | Val Dice: 0.8501
[Seed 2026] Epoch 36/50 | Train Dice: 0.8586 | Val Dice: 0.8520
[Seed 2026] Epoch 37/50 | Train Dice: 0.8619 | Val Dice: 0.8489
[Seed 2026] Epoch 38/50 | Train Dice: 0.8482 | Val Dice: 0.8497
[Seed 2026] Epoch 39/50 | Train Dice: 0.8610 | Val Dice: 0.8489
[Seed 2026] Epoch 40/50 | Train Dice: 0.8561 | Val Dice: 0.8491
[Seed 2026] Epoch 41/50 | Train Dice: 0.8592 | Val Dice: 0.8500
[Seed 2026] Epoch 42/50 | Train Dice: 0.8550 | Val Dice: 0.8506
[Seed 2026] Epoch 43/50 | Train Dice: 0.8583 | Val Dice: 0.8472
[Seed 2026] Epoch 44/50 | Train Dice: 0.8416 | Val Dice: 0.8469
[Seed 2026] Epoch 45/50 | Train Dice: 0.8515 | Val Dice: 0.8508
[Seed 2026] Epoch 46/50 | Train Dice: 0.8512 | Val Dice: 0.8462
[Seed 2026] Epoch 47/50 | Train Dice: 0.8512 | Val Dice: 0.8497
[Seed 2026] Epoch 48/50 | Train Dice: 0.8562 | Val Dice: 0.8486
[Seed 2026] Epoch 49/50 | Train Dice: 0.8532 | Val Dice: 0.8432
[Seed 2026] Epoch 50/50 | Train Dice: 0.8559 | Val Dice: 0.8487

In [81]:
# storing values into .csv file
import pandas as pd

history_df = pd.DataFrame(history)
csv_path = "/kaggle/working/stellar_rank64_glas_probe_3_SEED_history.csv"
history_df.to_csv(csv_path, index=False)

display(history_df.head())

   epoch  train_dice  train_miou  val_dice  val_miou
0      1    0.700831    0.526833  0.786231  0.630493
1      2    0.789943    0.649002  0.804036  0.662026
2      3    0.798801    0.656740  0.810905  0.672013
3      4    0.815564    0.679419  0.814112  0.683732
4      5    0.818853    0.685438  0.831655  0.696935

In [82]:
# Summarize results of lowrank
for seed, result in rank64_results.items():
    print("\n" + "=" * 60)
    print(f"RANK-64 — SEED {seed}")
    print("=" * 60)
    print(f"Best epoch : {result['best_epoch']}")
    print(f"Val Dice   : {result['best_val_dice']:.4f}")

============================================================
RANK-64 — SEED 42
============================================================
Best epoch : 41
Val Dice   : 0.8561

============================================================
RANK-64 — SEED 123
============================================================
Best epoch : 32
Val Dice   : 0.8552

============================================================
RANK-64 — SEED 2026
============================================================
Best epoch : 21
Val Dice   : 0.8558

In [83]:
# Feature rank and Effective rank for Rank-32 model
import torch

batch = next(iter(probe_val_loader))
images = batch["image"].to(device)
with torch.no_grad():
    outputs = rank64_backbone.encode({"image": images})

rank64_features = outputs["dense"]
X = rank64_features[0]

# Center exactly as done during truncation
X_centered = X - X.mean(dim=0, keepdim=True)
S = torch.linalg.svdvals(X_centered)
numerical_rank = (S > 1e-5).sum().item()
print("Numerical rank:", numerical_rank)
print("Rank-64 effective rank:",effective_rank(rank64_features[0]))

Numerical rank: 64
Rank-64 effective rank: 49.597938537597656

### Rank-16 for 3 SEED

In [84]:
import torch.nn as nn
rank16_backbone = RankTruncatedBackbone(model,rank=16)

rank16_model = SegmentationProbing(
    model_backbone=rank16_backbone,
    is_baseline=False,
    feature_key="dense",
    feature_dim=768,
    num_classes=2,
    freeze_backbone=True,
    freeze_model=False,
    resize_output=(224, 224),
).to(device)

optimizer = torch.optim.AdamW(filter(lambda p: p.requires_grad,rank16_model.parameters()),
    lr=1e-3,weight_decay=1e-4,)
criterion = nn.CrossEntropyLoss()

In [85]:
import random

history = []
def train_spatial_probe(seed, num_epochs=50):
    # Training randomness
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    
    # Best checkpoint in memory
    best_val_dice = -1.0
    best_epoch = -1
    best_state = None

    # Training
    for epoch in range(num_epochs):
        train_metrics = run_epoch(rank16_model,probe_train_loader,optimizer=optimizer,
            criterion=criterion,device=device,)

        val_metrics = run_epoch(rank16_model,probe_val_loader,optimizer=None,
            criterion=criterion,device=device,)
        
        history.append({
            "epoch": epoch + 1,
            "train_dice": train_metrics["gland_dice"],
            "train_miou": train_metrics["miou"],
            "val_dice": val_metrics["gland_dice"],
            "val_miou": val_metrics["miou"],
        })

        print(
            f"[Seed {seed}] "
            f"Epoch {epoch+1:02d}/{num_epochs} | "
            f"Train Dice: {train_metrics['gland_dice']:.4f} | "
            f"Val Dice: {val_metrics['gland_dice']:.4f}"
        )

        if val_metrics["gland_dice"] > best_val_dice:
            best_val_dice = val_metrics["gland_dice"]
            best_epoch = epoch + 1
            best_state = {
                k: v.detach().cpu().clone()
                for k, v in rank16_model.state_dict().items()
            }

    
    """ # Restore best model
        rank32_model.load_state_dict(best_state)
        rank32_model.eval()
        
        # TestA
        testA_metrics = run_epoch(
            rank32_model,
            testA_loader,
            optimizer=None,
            criterion=criterion,
            device=device,
        )

        # TestB
        testB_metrics = run_epoch(
            rank32_model,
            testB_loader,
            optimizer=None,
            criterion=criterion,
            device=device,
        )
    """
    return {
        "seed": seed,
        "best_epoch": best_epoch,
        "best_val_dice": best_val_dice,
        "history": history,
    }

In [86]:
rank16_results = {}

for seed in [42, 123, 2026]:
    print("\n" + "=" * 70)
    print(f"STARTING RANK-16 PROBE — SEED {seed}")
    print("=" * 70)
    rank16_results[seed] = train_spatial_probe(
        feature_key="lowrank",seed=seed,num_epochs=50,)

======================================================================
STARTING RANK-16 PROBE — SEED 42
======================================================================
[Seed 42] Epoch 01/50 | Train Dice: 0.7064 | Val Dice: 0.7837
[Seed 42] Epoch 02/50 | Train Dice: 0.7847 | Val Dice: 0.8015
[Seed 42] Epoch 03/50 | Train Dice: 0.7957 | Val Dice: 0.8088
[Seed 42] Epoch 04/50 | Train Dice: 0.8043 | Val Dice: 0.8102
[Seed 42] Epoch 05/50 | Train Dice: 0.8040 | Val Dice: 0.8266
[Seed 42] Epoch 06/50 | Train Dice: 0.8231 | Val Dice: 0.8234
[Seed 42] Epoch 07/50 | Train Dice: 0.8157 | Val Dice: 0.8270
[Seed 42] Epoch 08/50 | Train Dice: 0.8147 | Val Dice: 0.8318
[Seed 42] Epoch 09/50 | Train Dice: 0.8234 | Val Dice: 0.8307
[Seed 42] Epoch 10/50 | Train Dice: 0.8241 | Val Dice: 0.8252
[Seed 42] Epoch 11/50 | Train Dice: 0.8170 | Val Dice: 0.8158
[Seed 42] Epoch 12/50 | Train Dice: 0.8286 | Val Dice: 0.8178
[Seed 42] Epoch 13/50 | Train Dice: 0.8261 | Val Dice: 0.8206
[Seed 42] Epoch 14/50 | Train Dice: 0.8297 | Val Dice: 0.8155
[Seed 42] Epoch 15/50 | Train Dice: 0.8356 | Val Dice: 0.8305
[Seed 42] Epoch 16/50 | Train Dice: 0.8301 | Val Dice: 0.8350
[Seed 42] Epoch 17/50 | Train Dice: 0.8245 | Val Dice: 0.8299
[Seed 42] Epoch 18/50 | Train Dice: 0.8200 | Val Dice: 0.8195
[Seed 42] Epoch 19/50 | Train Dice: 0.8327 | Val Dice: 0.8317
[Seed 42] Epoch 20/50 | Train Dice: 0.8383 | Val Dice: 0.8324
[Seed 42] Epoch 21/50 | Train Dice: 0.8301 | Val Dice: 0.8269
[Seed 42] Epoch 22/50 | Train Dice: 0.8281 | Val Dice: 0.8325
[Seed 42] Epoch 23/50 | Train Dice: 0.8421 | Val Dice: 0.8289
[Seed 42] Epoch 24/50 | Train Dice: 0.8396 | Val Dice: 0.8319
[Seed 42] Epoch 25/50 | Train Dice: 0.8315 | Val Dice: 0.8283
[Seed 42] Epoch 26/50 | Train Dice: 0.8393 | Val Dice: 0.8258
[Seed 42] Epoch 27/50 | Train Dice: 0.8348 | Val Dice: 0.8257
[Seed 42] Epoch 28/50 | Train Dice: 0.8430 | Val Dice: 0.8297
[Seed 42] Epoch 29/50 | Train Dice: 0.8491 | Val Dice: 0.8216
[Seed 42] Epoch 30/50 | Train Dice: 0.8252 | Val Dice: 0.8252
[Seed 42] Epoch 31/50 | Train Dice: 0.8342 | Val Dice: 0.8260
[Seed 42] Epoch 32/50 | Train Dice: 0.8346 | Val Dice: 0.8297
[Seed 42] Epoch 33/50 | Train Dice: 0.8284 | Val Dice: 0.8157
[Seed 42] Epoch 34/50 | Train Dice: 0.8457 | Val Dice: 0.8239
[Seed 42] Epoch 35/50 | Train Dice: 0.8283 | Val Dice: 0.8128
[Seed 42] Epoch 36/50 | Train Dice: 0.8379 | Val Dice: 0.8259
[Seed 42] Epoch 37/50 | Train Dice: 0.8338 | Val Dice: 0.8329
[Seed 42] Epoch 38/50 | Train Dice: 0.8355 | Val Dice: 0.8290
[Seed 42] Epoch 39/50 | Train Dice: 0.8331 | Val Dice: 0.8306
[Seed 42] Epoch 40/50 | Train Dice: 0.8310 | Val Dice: 0.8301
[Seed 42] Epoch 41/50 | Train Dice: 0.8302 | Val Dice: 0.8375
[Seed 42] Epoch 42/50 | Train Dice: 0.8421 | Val Dice: 0.8374
[Seed 42] Epoch 43/50 | Train Dice: 0.8331 | Val Dice: 0.8292
[Seed 42] Epoch 44/50 | Train Dice: 0.8400 | Val Dice: 0.8376
[Seed 42] Epoch 45/50 | Train Dice: 0.8433 | Val Dice: 0.8330
[Seed 42] Epoch 46/50 | Train Dice: 0.8403 | Val Dice: 0.8379
[Seed 42] Epoch 47/50 | Train Dice: 0.8360 | Val Dice: 0.8319
[Seed 42] Epoch 48/50 | Train Dice: 0.8346 | Val Dice: 0.8284
[Seed 42] Epoch 49/50 | Train Dice: 0.8272 | Val Dice: 0.8335
[Seed 42] Epoch 50/50 | Train Dice: 0.8339 | Val Dice: 0.8389

======================================================================
STARTING RANK-16 PROBE — SEED 123
======================================================================
[Seed 123] Epoch 01/50 | Train Dice: 0.8389 | Val Dice: 0.8375
[Seed 123] Epoch 02/50 | Train Dice: 0.8452 | Val Dice: 0.8297
[Seed 123] Epoch 03/50 | Train Dice: 0.8372 | Val Dice: 0.8327
[Seed 123] Epoch 04/50 | Train Dice: 0.8325 | Val Dice: 0.8245
[Seed 123] Epoch 05/50 | Train Dice: 0.8424 | Val Dice: 0.8416
[Seed 123] Epoch 06/50 | Train Dice: 0.8368 | Val Dice: 0.8407
[Seed 123] Epoch 07/50 | Train Dice: 0.8275 | Val Dice: 0.8351
[Seed 123] Epoch 08/50 | Train Dice: 0.8379 | Val Dice: 0.8320
[Seed 123] Epoch 09/50 | Train Dice: 0.8381 | Val Dice: 0.8336
[Seed 123] Epoch 10/50 | Train Dice: 0.8368 | Val Dice: 0.8250
[Seed 123] Epoch 11/50 | Train Dice: 0.8420 | Val Dice: 0.8367
[Seed 123] Epoch 12/50 | Train Dice: 0.8421 | Val Dice: 0.8362
[Seed 123] Epoch 13/50 | Train Dice: 0.8183 | Val Dice: 0.8210
[Seed 123] Epoch 14/50 | Train Dice: 0.8388 | Val Dice: 0.8362
[Seed 123] Epoch 15/50 | Train Dice: 0.8338 | Val Dice: 0.8338
[Seed 123] Epoch 16/50 | Train Dice: 0.8483 | Val Dice: 0.8366
[Seed 123] Epoch 17/50 | Train Dice: 0.8501 | Val Dice: 0.8290
[Seed 123] Epoch 18/50 | Train Dice: 0.8484 | Val Dice: 0.8291
[Seed 123] Epoch 19/50 | Train Dice: 0.8392 | Val Dice: 0.8264
[Seed 123] Epoch 20/50 | Train Dice: 0.8360 | Val Dice: 0.8277
[Seed 123] Epoch 21/50 | Train Dice: 0.8476 | Val Dice: 0.8321
[Seed 123] Epoch 22/50 | Train Dice: 0.8425 | Val Dice: 0.8244
[Seed 123] Epoch 23/50 | Train Dice: 0.8456 | Val Dice: 0.8346
[Seed 123] Epoch 24/50 | Train Dice: 0.8411 | Val Dice: 0.8287
[Seed 123] Epoch 25/50 | Train Dice: 0.8294 | Val Dice: 0.8236
[Seed 123] Epoch 26/50 | Train Dice: 0.8341 | Val Dice: 0.8322
[Seed 123] Epoch 27/50 | Train Dice: 0.8443 | Val Dice: 0.8363
[Seed 123] Epoch 28/50 | Train Dice: 0.8362 | Val Dice: 0.8383
[Seed 123] Epoch 29/50 | Train Dice: 0.8398 | Val Dice: 0.8355
[Seed 123] Epoch 30/50 | Train Dice: 0.8249 | Val Dice: 0.8374
[Seed 123] Epoch 31/50 | Train Dice: 0.8352 | Val Dice: 0.8355
[Seed 123] Epoch 32/50 | Train Dice: 0.8295 | Val Dice: 0.8402
[Seed 123] Epoch 33/50 | Train Dice: 0.8401 | Val Dice: 0.8378
[Seed 123] Epoch 34/50 | Train Dice: 0.8291 | Val Dice: 0.8267
[Seed 123] Epoch 35/50 | Train Dice: 0.8434 | Val Dice: 0.8304
[Seed 123] Epoch 36/50 | Train Dice: 0.8364 | Val Dice: 0.8367
[Seed 123] Epoch 37/50 | Train Dice: 0.8416 | Val Dice: 0.8348
[Seed 123] Epoch 38/50 | Train Dice: 0.8457 | Val Dice: 0.8332
[Seed 123] Epoch 39/50 | Train Dice: 0.8356 | Val Dice: 0.8368
[Seed 123] Epoch 40/50 | Train Dice: 0.8376 | Val Dice: 0.8269
[Seed 123] Epoch 41/50 | Train Dice: 0.8433 | Val Dice: 0.8215
[Seed 123] Epoch 42/50 | Train Dice: 0.8416 | Val Dice: 0.8341
[Seed 123] Epoch 43/50 | Train Dice: 0.8375 | Val Dice: 0.8362
[Seed 123] Epoch 44/50 | Train Dice: 0.8418 | Val Dice: 0.8298
[Seed 123] Epoch 45/50 | Train Dice: 0.8378 | Val Dice: 0.8398
[Seed 123] Epoch 46/50 | Train Dice: 0.8422 | Val Dice: 0.8363
[Seed 123] Epoch 47/50 | Train Dice: 0.8455 | Val Dice: 0.8329
[Seed 123] Epoch 48/50 | Train Dice: 0.8513 | Val Dice: 0.8397
[Seed 123] Epoch 49/50 | Train Dice: 0.8360 | Val Dice: 0.8323
[Seed 123] Epoch 50/50 | Train Dice: 0.8324 | Val Dice: 0.8337

======================================================================
STARTING RANK-16 PROBE — SEED 2026
======================================================================
[Seed 2026] Epoch 01/50 | Train Dice: 0.8341 | Val Dice: 0.8257
[Seed 2026] Epoch 02/50 | Train Dice: 0.8414 | Val Dice: 0.8287
[Seed 2026] Epoch 03/50 | Train Dice: 0.8421 | Val Dice: 0.8284
[Seed 2026] Epoch 04/50 | Train Dice: 0.8346 | Val Dice: 0.8284
[Seed 2026] Epoch 05/50 | Train Dice: 0.8392 | Val Dice: 0.8352
[Seed 2026] Epoch 06/50 | Train Dice: 0.8339 | Val Dice: 0.8317
[Seed 2026] Epoch 07/50 | Train Dice: 0.8422 | Val Dice: 0.8400
[Seed 2026] Epoch 08/50 | Train Dice: 0.8459 | Val Dice: 0.8362
[Seed 2026] Epoch 09/50 | Train Dice: 0.8292 | Val Dice: 0.8345
[Seed 2026] Epoch 10/50 | Train Dice: 0.8487 | Val Dice: 0.8375
[Seed 2026] Epoch 11/50 | Train Dice: 0.8429 | Val Dice: 0.8367
[Seed 2026] Epoch 12/50 | Train Dice: 0.8493 | Val Dice: 0.8339
[Seed 2026] Epoch 13/50 | Train Dice: 0.8478 | Val Dice: 0.8356
[Seed 2026] Epoch 14/50 | Train Dice: 0.8409 | Val Dice: 0.8357
[Seed 2026] Epoch 15/50 | Train Dice: 0.8325 | Val Dice: 0.8367
[Seed 2026] Epoch 16/50 | Train Dice: 0.8347 | Val Dice: 0.8250
[Seed 2026] Epoch 17/50 | Train Dice: 0.8421 | Val Dice: 0.8304
[Seed 2026] Epoch 18/50 | Train Dice: 0.8395 | Val Dice: 0.8239
[Seed 2026] Epoch 19/50 | Train Dice: 0.8344 | Val Dice: 0.8354
[Seed 2026] Epoch 20/50 | Train Dice: 0.8296 | Val Dice: 0.8305
[Seed 2026] Epoch 21/50 | Train Dice: 0.8354 | Val Dice: 0.8415
[Seed 2026] Epoch 22/50 | Train Dice: 0.8500 | Val Dice: 0.8392
[Seed 2026] Epoch 23/50 | Train Dice: 0.8337 | Val Dice: 0.8398
[Seed 2026] Epoch 24/50 | Train Dice: 0.8376 | Val Dice: 0.8332
[Seed 2026] Epoch 25/50 | Train Dice: 0.8452 | Val Dice: 0.8343
[Seed 2026] Epoch 26/50 | Train Dice: 0.8463 | Val Dice: 0.8321
[Seed 2026] Epoch 27/50 | Train Dice: 0.8467 | Val Dice: 0.8160
[Seed 2026] Epoch 28/50 | Train Dice: 0.8376 | Val Dice: 0.8155
[Seed 2026] Epoch 29/50 | Train Dice: 0.8343 | Val Dice: 0.8295
[Seed 2026] Epoch 30/50 | Train Dice: 0.8409 | Val Dice: 0.8326
[Seed 2026] Epoch 31/50 | Train Dice: 0.8388 | Val Dice: 0.8361
[Seed 2026] Epoch 32/50 | Train Dice: 0.8436 | Val Dice: 0.8324
[Seed 2026] Epoch 33/50 | Train Dice: 0.8363 | Val Dice: 0.8342
[Seed 2026] Epoch 34/50 | Train Dice: 0.8198 | Val Dice: 0.8293
[Seed 2026] Epoch 35/50 | Train Dice: 0.8480 | Val Dice: 0.8275
[Seed 2026] Epoch 36/50 | Train Dice: 0.8416 | Val Dice: 0.8310
[Seed 2026] Epoch 37/50 | Train Dice: 0.8512 | Val Dice: 0.8294
[Seed 2026] Epoch 38/50 | Train Dice: 0.8350 | Val Dice: 0.8324
[Seed 2026] Epoch 39/50 | Train Dice: 0.8472 | Val Dice: 0.8304
[Seed 2026] Epoch 40/50 | Train Dice: 0.8442 | Val Dice: 0.8305
[Seed 2026] Epoch 41/50 | Train Dice: 0.8444 | Val Dice: 0.8326
[Seed 2026] Epoch 42/50 | Train Dice: 0.8430 | Val Dice: 0.8339
[Seed 2026] Epoch 43/50 | Train Dice: 0.8401 | Val Dice: 0.8294
[Seed 2026] Epoch 44/50 | Train Dice: 0.8301 | Val Dice: 0.8258
[Seed 2026] Epoch 45/50 | Train Dice: 0.8433 | Val Dice: 0.8349
[Seed 2026] Epoch 46/50 | Train Dice: 0.8378 | Val Dice: 0.8237
[Seed 2026] Epoch 47/50 | Train Dice: 0.8384 | Val Dice: 0.8310
[Seed 2026] Epoch 48/50 | Train Dice: 0.8420 | Val Dice: 0.8290
[Seed 2026] Epoch 49/50 | Train Dice: 0.8408 | Val Dice: 0.8238
[Seed 2026] Epoch 50/50 | Train Dice: 0.8427 | Val Dice: 0.8319

In [87]:
# storing values into .csv file
import pandas as pd

history_df = pd.DataFrame(history)
csv_path = "/kaggle/working/stellar_rank16_glas_probe_3_SEED_history.csv"
history_df.to_csv(csv_path, index=False)

display(history_df.head())

   epoch  train_dice  train_miou  val_dice  val_miou
0      1    0.706395    0.534474  0.783676  0.625083
1      2    0.784676    0.641879  0.801478  0.655178
2      3    0.795725    0.650345  0.808759  0.667786
3      4    0.804342    0.661470  0.810246  0.677146
4      5    0.804013    0.663216  0.826579  0.687656

In [88]:
# Summarize results of lowrank
for seed, result in rank16_results.items():
    print("\n" + "=" * 60)
    print(f"RANK-16 — SEED {seed}")
    print("=" * 60)
    print(f"Best epoch : {result['best_epoch']}")
    print(f"Val Dice   : {result['best_val_dice']:.4f}")

============================================================
RANK-16 — SEED 42
============================================================
Best epoch : 50
Val Dice   : 0.8389

============================================================
RANK-16 — SEED 123
============================================================
Best epoch : 5
Val Dice   : 0.8416

============================================================
RANK-16 — SEED 2026
============================================================
Best epoch : 21
Val Dice   : 0.8415

In [89]:
# Feature rank and Effective rank for Rank-32 model
import torch

batch = next(iter(probe_val_loader))
images = batch["image"].to(device)
with torch.no_grad():
    outputs = rank16_backbone.encode({"image": images})

rank16_features = outputs["dense"]
X = rank16_features[0]

# Center exactly as done during truncation
X_centered = X - X.mean(dim=0, keepdim=True)
S = torch.linalg.svdvals(X_centered)
numerical_rank = (S > 1e-5).sum().item()
print("Numerical rank:", numerical_rank)
print("Rank-16 effective rank:",effective_rank(rank16_features[0]))

Numerical rank: 16
Rank-16 effective rank: 13.63166332244873

### Rank-15 for 3 SEED

In [90]:
import torch.nn as nn
rank15_backbone = RankTruncatedBackbone(model,rank=15)

rank15_model = SegmentationProbing(
    model_backbone=rank15_backbone,
    is_baseline=False,
    feature_key="dense",
    feature_dim=768,
    num_classes=2,
    freeze_backbone=True,
    freeze_model=False,
    resize_output=(224, 224),
).to(device)

optimizer = torch.optim.AdamW(filter(lambda p: p.requires_grad,rank15_model.parameters()),
    lr=1e-3,weight_decay=1e-4,)
criterion = nn.CrossEntropyLoss()

In [91]:
import random

history = []
def train_spatial_probe(seed, num_epochs=50):
    # Training randomness
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    
    # Best checkpoint in memory
    best_val_dice = -1.0
    best_epoch = -1
    best_state = None

    # Training
    for epoch in range(num_epochs):
        train_metrics = run_epoch(rank15_model,probe_train_loader,optimizer=optimizer,
            criterion=criterion,device=device,)

        val_metrics = run_epoch(rank15_model,probe_val_loader,optimizer=None,
            criterion=criterion,device=device,)
        
        history.append({
            "epoch": epoch + 1,
            "train_dice": train_metrics["gland_dice"],
            "train_miou": train_metrics["miou"],
            "val_dice": val_metrics["gland_dice"],
            "val_miou": val_metrics["miou"],
        })

        print(
            f"[Seed {seed}] "
            f"Epoch {epoch+1:02d}/{num_epochs} | "
            f"Train Dice: {train_metrics['gland_dice']:.4f} | "
            f"Val Dice: {val_metrics['gland_dice']:.4f}"
        )

        if val_metrics["gland_dice"] > best_val_dice:
            best_val_dice = val_metrics["gland_dice"]
            best_epoch = epoch + 1
            best_state = {
                k: v.detach().cpu().clone()
                for k, v in rank15_model.state_dict().items()
            }

    
    """ # Restore best model
        rank32_model.load_state_dict(best_state)
        rank32_model.eval()
        
        # TestA
        testA_metrics = run_epoch(
            rank32_model,
            testA_loader,
            optimizer=None,
            criterion=criterion,
            device=device,
        )

        # TestB
        testB_metrics = run_epoch(
            rank32_model,
            testB_loader,
            optimizer=None,
            criterion=criterion,
            device=device,
        )
    """
    return {
        "seed": seed,
        "best_epoch": best_epoch,
        "best_val_dice": best_val_dice,
        "history": history,
    }

In [92]:
rank15_results = {}

for seed in [42, 123, 2026]:
    print("\n" + "=" * 70)
    print(f"STARTING RANK-15 PROBE — SEED {seed}")
    print("=" * 70)
    rank15_results[seed] = train_spatial_probe(
        feature_key="lowrank",seed=seed,num_epochs=50,)

======================================================================
STARTING RANK-15 PROBE — SEED 42
======================================================================
[Seed 42] Epoch 01/50 | Train Dice: 0.7050 | Val Dice: 0.7865
[Seed 42] Epoch 02/50 | Train Dice: 0.7825 | Val Dice: 0.8052
[Seed 42] Epoch 03/50 | Train Dice: 0.7928 | Val Dice: 0.8102
[Seed 42] Epoch 04/50 | Train Dice: 0.8028 | Val Dice: 0.8123
[Seed 42] Epoch 05/50 | Train Dice: 0.8024 | Val Dice: 0.8297
[Seed 42] Epoch 06/50 | Train Dice: 0.8212 | Val Dice: 0.8253
[Seed 42] Epoch 07/50 | Train Dice: 0.8147 | Val Dice: 0.8301
[Seed 42] Epoch 08/50 | Train Dice: 0.8141 | Val Dice: 0.8334
[Seed 42] Epoch 09/50 | Train Dice: 0.8221 | Val Dice: 0.8323
[Seed 42] Epoch 10/50 | Train Dice: 0.8240 | Val Dice: 0.8260
[Seed 42] Epoch 11/50 | Train Dice: 0.8159 | Val Dice: 0.8172
[Seed 42] Epoch 12/50 | Train Dice: 0.8270 | Val Dice: 0.8193
[Seed 42] Epoch 13/50 | Train Dice: 0.8253 | Val Dice: 0.8229
[Seed 42] Epoch 14/50 | Train Dice: 0.8283 | Val Dice: 0.8162
[Seed 42] Epoch 15/50 | Train Dice: 0.8341 | Val Dice: 0.8306
[Seed 42] Epoch 16/50 | Train Dice: 0.8296 | Val Dice: 0.8363
[Seed 42] Epoch 17/50 | Train Dice: 0.8239 | Val Dice: 0.8313
[Seed 42] Epoch 18/50 | Train Dice: 0.8183 | Val Dice: 0.8206
[Seed 42] Epoch 19/50 | Train Dice: 0.8333 | Val Dice: 0.8331
[Seed 42] Epoch 20/50 | Train Dice: 0.8364 | Val Dice: 0.8328
[Seed 42] Epoch 21/50 | Train Dice: 0.8287 | Val Dice: 0.8282
[Seed 42] Epoch 22/50 | Train Dice: 0.8267 | Val Dice: 0.8342
[Seed 42] Epoch 23/50 | Train Dice: 0.8416 | Val Dice: 0.8302
[Seed 42] Epoch 24/50 | Train Dice: 0.8389 | Val Dice: 0.8344
[Seed 42] Epoch 25/50 | Train Dice: 0.8307 | Val Dice: 0.8303
[Seed 42] Epoch 26/50 | Train Dice: 0.8389 | Val Dice: 0.8276
[Seed 42] Epoch 27/50 | Train Dice: 0.8339 | Val Dice: 0.8262
[Seed 42] Epoch 28/50 | Train Dice: 0.8408 | Val Dice: 0.8308
[Seed 42] Epoch 29/50 | Train Dice: 0.8475 | Val Dice: 0.8221
[Seed 42] Epoch 30/50 | Train Dice: 0.8238 | Val Dice: 0.8259
[Seed 42] Epoch 31/50 | Train Dice: 0.8330 | Val Dice: 0.8280
[Seed 42] Epoch 32/50 | Train Dice: 0.8325 | Val Dice: 0.8315
[Seed 42] Epoch 33/50 | Train Dice: 0.8276 | Val Dice: 0.8157
[Seed 42] Epoch 34/50 | Train Dice: 0.8435 | Val Dice: 0.8247
[Seed 42] Epoch 35/50 | Train Dice: 0.8285 | Val Dice: 0.8120
[Seed 42] Epoch 36/50 | Train Dice: 0.8377 | Val Dice: 0.8269
[Seed 42] Epoch 37/50 | Train Dice: 0.8309 | Val Dice: 0.8348
[Seed 42] Epoch 38/50 | Train Dice: 0.8344 | Val Dice: 0.8316
[Seed 42] Epoch 39/50 | Train Dice: 0.8318 | Val Dice: 0.8307
[Seed 42] Epoch 40/50 | Train Dice: 0.8311 | Val Dice: 0.8311
[Seed 42] Epoch 41/50 | Train Dice: 0.8292 | Val Dice: 0.8369
[Seed 42] Epoch 42/50 | Train Dice: 0.8411 | Val Dice: 0.8367
[Seed 42] Epoch 43/50 | Train Dice: 0.8319 | Val Dice: 0.8292
[Seed 42] Epoch 44/50 | Train Dice: 0.8390 | Val Dice: 0.8389
[Seed 42] Epoch 45/50 | Train Dice: 0.8428 | Val Dice: 0.8329
[Seed 42] Epoch 46/50 | Train Dice: 0.8396 | Val Dice: 0.8382
[Seed 42] Epoch 47/50 | Train Dice: 0.8354 | Val Dice: 0.8328
[Seed 42] Epoch 48/50 | Train Dice: 0.8337 | Val Dice: 0.8323
[Seed 42] Epoch 49/50 | Train Dice: 0.8271 | Val Dice: 0.8351
[Seed 42] Epoch 50/50 | Train Dice: 0.8318 | Val Dice: 0.8398

======================================================================
STARTING RANK-15 PROBE — SEED 123
======================================================================
[Seed 123] Epoch 01/50 | Train Dice: 0.8401 | Val Dice: 0.8379
[Seed 123] Epoch 02/50 | Train Dice: 0.8448 | Val Dice: 0.8297
[Seed 123] Epoch 03/50 | Train Dice: 0.8361 | Val Dice: 0.8332
[Seed 123] Epoch 04/50 | Train Dice: 0.8329 | Val Dice: 0.8238
[Seed 123] Epoch 05/50 | Train Dice: 0.8412 | Val Dice: 0.8425
[Seed 123] Epoch 06/50 | Train Dice: 0.8355 | Val Dice: 0.8421
[Seed 123] Epoch 07/50 | Train Dice: 0.8282 | Val Dice: 0.8365
[Seed 123] Epoch 08/50 | Train Dice: 0.8366 | Val Dice: 0.8339
[Seed 123] Epoch 09/50 | Train Dice: 0.8371 | Val Dice: 0.8340
[Seed 123] Epoch 10/50 | Train Dice: 0.8360 | Val Dice: 0.8249
[Seed 123] Epoch 11/50 | Train Dice: 0.8404 | Val Dice: 0.8396
[Seed 123] Epoch 12/50 | Train Dice: 0.8417 | Val Dice: 0.8365
[Seed 123] Epoch 13/50 | Train Dice: 0.8170 | Val Dice: 0.8207
[Seed 123] Epoch 14/50 | Train Dice: 0.8376 | Val Dice: 0.8393
[Seed 123] Epoch 15/50 | Train Dice: 0.8335 | Val Dice: 0.8342
[Seed 123] Epoch 16/50 | Train Dice: 0.8454 | Val Dice: 0.8378
[Seed 123] Epoch 17/50 | Train Dice: 0.8488 | Val Dice: 0.8305
[Seed 123] Epoch 18/50 | Train Dice: 0.8475 | Val Dice: 0.8302
[Seed 123] Epoch 19/50 | Train Dice: 0.8380 | Val Dice: 0.8268
[Seed 123] Epoch 20/50 | Train Dice: 0.8345 | Val Dice: 0.8275
[Seed 123] Epoch 21/50 | Train Dice: 0.8460 | Val Dice: 0.8329
[Seed 123] Epoch 22/50 | Train Dice: 0.8423 | Val Dice: 0.8251
[Seed 123] Epoch 23/50 | Train Dice: 0.8441 | Val Dice: 0.8366
[Seed 123] Epoch 24/50 | Train Dice: 0.8392 | Val Dice: 0.8292
[Seed 123] Epoch 25/50 | Train Dice: 0.8280 | Val Dice: 0.8253
[Seed 123] Epoch 26/50 | Train Dice: 0.8334 | Val Dice: 0.8308
[Seed 123] Epoch 27/50 | Train Dice: 0.8426 | Val Dice: 0.8357
[Seed 123] Epoch 28/50 | Train Dice: 0.8333 | Val Dice: 0.8388
[Seed 123] Epoch 29/50 | Train Dice: 0.8381 | Val Dice: 0.8373
[Seed 123] Epoch 30/50 | Train Dice: 0.8235 | Val Dice: 0.8376
[Seed 123] Epoch 31/50 | Train Dice: 0.8341 | Val Dice: 0.8366
[Seed 123] Epoch 32/50 | Train Dice: 0.8291 | Val Dice: 0.8415
[Seed 123] Epoch 33/50 | Train Dice: 0.8384 | Val Dice: 0.8390
[Seed 123] Epoch 34/50 | Train Dice: 0.8274 | Val Dice: 0.8262
[Seed 123] Epoch 35/50 | Train Dice: 0.8426 | Val Dice: 0.8313
[Seed 123] Epoch 36/50 | Train Dice: 0.8356 | Val Dice: 0.8368
[Seed 123] Epoch 37/50 | Train Dice: 0.8393 | Val Dice: 0.8349
[Seed 123] Epoch 38/50 | Train Dice: 0.8451 | Val Dice: 0.8343
[Seed 123] Epoch 39/50 | Train Dice: 0.8339 | Val Dice: 0.8376
[Seed 123] Epoch 40/50 | Train Dice: 0.8364 | Val Dice: 0.8268
[Seed 123] Epoch 41/50 | Train Dice: 0.8425 | Val Dice: 0.8215
[Seed 123] Epoch 42/50 | Train Dice: 0.8393 | Val Dice: 0.8355
[Seed 123] Epoch 43/50 | Train Dice: 0.8348 | Val Dice: 0.8366
[Seed 123] Epoch 44/50 | Train Dice: 0.8410 | Val Dice: 0.8296
[Seed 123] Epoch 45/50 | Train Dice: 0.8388 | Val Dice: 0.8413
[Seed 123] Epoch 46/50 | Train Dice: 0.8420 | Val Dice: 0.8365
[Seed 123] Epoch 47/50 | Train Dice: 0.8448 | Val Dice: 0.8318
[Seed 123] Epoch 48/50 | Train Dice: 0.8502 | Val Dice: 0.8406
[Seed 123] Epoch 49/50 | Train Dice: 0.8348 | Val Dice: 0.8322
[Seed 123] Epoch 50/50 | Train Dice: 0.8306 | Val Dice: 0.8323

======================================================================
STARTING RANK-15 PROBE — SEED 2026
======================================================================
[Seed 2026] Epoch 01/50 | Train Dice: 0.8324 | Val Dice: 0.8243
[Seed 2026] Epoch 02/50 | Train Dice: 0.8403 | Val Dice: 0.8281
[Seed 2026] Epoch 03/50 | Train Dice: 0.8419 | Val Dice: 0.8283
[Seed 2026] Epoch 04/50 | Train Dice: 0.8341 | Val Dice: 0.8289
[Seed 2026] Epoch 05/50 | Train Dice: 0.8381 | Val Dice: 0.8359
[Seed 2026] Epoch 06/50 | Train Dice: 0.8325 | Val Dice: 0.8320
[Seed 2026] Epoch 07/50 | Train Dice: 0.8418 | Val Dice: 0.8411
[Seed 2026] Epoch 08/50 | Train Dice: 0.8456 | Val Dice: 0.8365
[Seed 2026] Epoch 09/50 | Train Dice: 0.8286 | Val Dice: 0.8335
[Seed 2026] Epoch 10/50 | Train Dice: 0.8482 | Val Dice: 0.8378
[Seed 2026] Epoch 11/50 | Train Dice: 0.8415 | Val Dice: 0.8375
[Seed 2026] Epoch 12/50 | Train Dice: 0.8472 | Val Dice: 0.8337
[Seed 2026] Epoch 13/50 | Train Dice: 0.8461 | Val Dice: 0.8367
[Seed 2026] Epoch 14/50 | Train Dice: 0.8394 | Val Dice: 0.8357
[Seed 2026] Epoch 15/50 | Train Dice: 0.8308 | Val Dice: 0.8366
[Seed 2026] Epoch 16/50 | Train Dice: 0.8345 | Val Dice: 0.8255
[Seed 2026] Epoch 17/50 | Train Dice: 0.8408 | Val Dice: 0.8308
[Seed 2026] Epoch 18/50 | Train Dice: 0.8384 | Val Dice: 0.8223
[Seed 2026] Epoch 19/50 | Train Dice: 0.8330 | Val Dice: 0.8344
[Seed 2026] Epoch 20/50 | Train Dice: 0.8289 | Val Dice: 0.8276
[Seed 2026] Epoch 21/50 | Train Dice: 0.8343 | Val Dice: 0.8413
[Seed 2026] Epoch 22/50 | Train Dice: 0.8493 | Val Dice: 0.8392
[Seed 2026] Epoch 23/50 | Train Dice: 0.8325 | Val Dice: 0.8407
[Seed 2026] Epoch 24/50 | Train Dice: 0.8370 | Val Dice: 0.8322
[Seed 2026] Epoch 25/50 | Train Dice: 0.8446 | Val Dice: 0.8339
[Seed 2026] Epoch 26/50 | Train Dice: 0.8455 | Val Dice: 0.8323
[Seed 2026] Epoch 27/50 | Train Dice: 0.8460 | Val Dice: 0.8153
[Seed 2026] Epoch 28/50 | Train Dice: 0.8359 | Val Dice: 0.8135
[Seed 2026] Epoch 29/50 | Train Dice: 0.8339 | Val Dice: 0.8287
[Seed 2026] Epoch 30/50 | Train Dice: 0.8392 | Val Dice: 0.8339
[Seed 2026] Epoch 31/50 | Train Dice: 0.8366 | Val Dice: 0.8353
[Seed 2026] Epoch 32/50 | Train Dice: 0.8422 | Val Dice: 0.8317
[Seed 2026] Epoch 33/50 | Train Dice: 0.8342 | Val Dice: 0.8336
[Seed 2026] Epoch 34/50 | Train Dice: 0.8169 | Val Dice: 0.8275
[Seed 2026] Epoch 35/50 | Train Dice: 0.8467 | Val Dice: 0.8293
[Seed 2026] Epoch 36/50 | Train Dice: 0.8401 | Val Dice: 0.8323
[Seed 2026] Epoch 37/50 | Train Dice: 0.8510 | Val Dice: 0.8281
[Seed 2026] Epoch 38/50 | Train Dice: 0.8337 | Val Dice: 0.8301
[Seed 2026] Epoch 39/50 | Train Dice: 0.8457 | Val Dice: 0.8300
[Seed 2026] Epoch 40/50 | Train Dice: 0.8424 | Val Dice: 0.8275
[Seed 2026] Epoch 41/50 | Train Dice: 0.8432 | Val Dice: 0.8304
[Seed 2026] Epoch 42/50 | Train Dice: 0.8422 | Val Dice: 0.8332
[Seed 2026] Epoch 43/50 | Train Dice: 0.8396 | Val Dice: 0.8272
[Seed 2026] Epoch 44/50 | Train Dice: 0.8278 | Val Dice: 0.8236
[Seed 2026] Epoch 45/50 | Train Dice: 0.8404 | Val Dice: 0.8335
[Seed 2026] Epoch 46/50 | Train Dice: 0.8368 | Val Dice: 0.8213
[Seed 2026] Epoch 47/50 | Train Dice: 0.8366 | Val Dice: 0.8289
[Seed 2026] Epoch 48/50 | Train Dice: 0.8406 | Val Dice: 0.8292
[Seed 2026] Epoch 49/50 | Train Dice: 0.8395 | Val Dice: 0.8216
[Seed 2026] Epoch 50/50 | Train Dice: 0.8403 | Val Dice: 0.8303

In [93]:
# storing values into .csv file
import pandas as pd

history_df = pd.DataFrame(history)
csv_path = "/kaggle/working/stellar_rank15_glas_probe_3_SEED_history.csv"
history_df.to_csv(csv_path, index=False)

display(history_df.head())

   epoch  train_dice  train_miou  val_dice  val_miou
0      1    0.704986    0.532802  0.786468  0.628757
1      2    0.782537    0.638898  0.805216  0.660283
2      3    0.792794    0.646277  0.810223  0.669091
3      4    0.802837    0.659241  0.812264  0.679602
4      5    0.802405    0.661024  0.829678  0.691689

In [94]:
# Summarize results of lowrank
for seed, result in rank15_results.items():
    print("\n" + "=" * 60)
    print(f"RANK-15 — SEED {seed}")
    print("=" * 60)
    print(f"Best epoch : {result['best_epoch']}")
    print(f"Val Dice   : {result['best_val_dice']:.4f}")

============================================================
RANK-15 — SEED 42
============================================================
Best epoch : 50
Val Dice   : 0.8398

============================================================
RANK-15 — SEED 123
============================================================
Best epoch : 5
Val Dice   : 0.8425

============================================================
RANK-15 — SEED 2026
============================================================
Best epoch : 21
Val Dice   : 0.8413

In [95]:
# Feature rank and Effective rank for Rank-32 model
import torch

batch = next(iter(probe_val_loader))
images = batch["image"].to(device)
with torch.no_grad():
    outputs = rank15_backbone.encode({"image": images})

rank15_features = outputs["dense"]
X = rank15_features[0]

# Center exactly as done during truncation
X_centered = X - X.mean(dim=0, keepdim=True)
S = torch.linalg.svdvals(X_centered)
numerical_rank = (S > 1e-5).sum().item()
print("Numerical rank:", numerical_rank)
print("Rank-15 effective rank:",effective_rank(rank15_features[0]))

Numerical rank: 15
Rank-15 effective rank: 12.839035987854004

### Rank-8 model for 3 SEED

In [96]:
import torch.nn as nn
rank8_backbone = RankTruncatedBackbone(model,rank=8)

rank8_model = SegmentationProbing(
    model_backbone=rank8_backbone,
    is_baseline=False,
    feature_key="dense",
    feature_dim=768,
    num_classes=2,
    freeze_backbone=True,
    freeze_model=False,
    resize_output=(224, 224),
).to(device)

optimizer = torch.optim.AdamW(filter(lambda p: p.requires_grad,rank8_model.parameters()),
    lr=1e-3,weight_decay=1e-4,)
criterion = nn.CrossEntropyLoss()

In [99]:
import random

history = []
def train_spatial_probe(seed, num_epochs=50):
    # Training randomness
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    
    # Best checkpoint in memory
    best_val_dice = -1.0
    best_epoch = -1
    best_state = None

    # Training
    for epoch in range(num_epochs):
        train_metrics = run_epoch(rank8_model,probe_train_loader,optimizer=optimizer,
            criterion=criterion,device=device,)

        val_metrics = run_epoch(rank8_model,probe_val_loader,optimizer=None,
            criterion=criterion,device=device,)
        
        history.append({
            "epoch": epoch + 1,
            "train_dice": train_metrics["gland_dice"],
            "train_miou": train_metrics["miou"],
            "val_dice": val_metrics["gland_dice"],
            "val_miou": val_metrics["miou"],
        })

        print(
            f"[Seed {seed}] "
            f"Epoch {epoch+1:02d}/{num_epochs} | "
            f"Train Dice: {train_metrics['gland_dice']:.4f} | "
            f"Val Dice: {val_metrics['gland_dice']:.4f}"
        )

        if val_metrics["gland_dice"] > best_val_dice:
            best_val_dice = val_metrics["gland_dice"]
            best_epoch = epoch + 1
            best_state = {
                k: v.detach().cpu().clone()
                for k, v in rank8_model.state_dict().items()
            }

    
    """ # Restore best model
        rank32_model.load_state_dict(best_state)
        rank32_model.eval()
        
        # TestA
        testA_metrics = run_epoch(
            rank32_model,
            testA_loader,
            optimizer=None,
            criterion=criterion,
            device=device,
        )

        # TestB
        testB_metrics = run_epoch(
            rank32_model,
            testB_loader,
            optimizer=None,
            criterion=criterion,
            device=device,
        )
    """
    return {
        "seed": seed,
        "best_epoch": best_epoch,
        "best_val_dice": best_val_dice,
        "history": history,
    }

In [101]:
rank8_results = {}

for seed in [42, 123, 2026]:
    print("\n" + "=" * 70)
    print(f"STARTING RANK-8 PROBE — SEED {seed}")
    print("=" * 70)
    rank8_results[seed] = train_spatial_probe(seed=seed,num_epochs=50,)

======================================================================
STARTING RANK-8 PROBE — SEED 42
======================================================================
[Seed 42] Epoch 01/50 | Train Dice: 0.7776 | Val Dice: 0.7892
[Seed 42] Epoch 02/50 | Train Dice: 0.7781 | Val Dice: 0.7980
[Seed 42] Epoch 03/50 | Train Dice: 0.7930 | Val Dice: 0.7921
[Seed 42] Epoch 04/50 | Train Dice: 0.7894 | Val Dice: 0.7952
[Seed 42] Epoch 05/50 | Train Dice: 0.7919 | Val Dice: 0.8067
[Seed 42] Epoch 06/50 | Train Dice: 0.8016 | Val Dice: 0.8069
[Seed 42] Epoch 07/50 | Train Dice: 0.7973 | Val Dice: 0.8070
[Seed 42] Epoch 08/50 | Train Dice: 0.7991 | Val Dice: 0.8173
[Seed 42] Epoch 09/50 | Train Dice: 0.8015 | Val Dice: 0.8115
[Seed 42] Epoch 10/50 | Train Dice: 0.8065 | Val Dice: 0.8091
[Seed 42] Epoch 11/50 | Train Dice: 0.8016 | Val Dice: 0.8069
[Seed 42] Epoch 12/50 | Train Dice: 0.8114 | Val Dice: 0.8088
[Seed 42] Epoch 13/50 | Train Dice: 0.8050 | Val Dice: 0.8059
[Seed 42] Epoch 14/50 | Train Dice: 0.8112 | Val Dice: 0.7926
[Seed 42] Epoch 15/50 | Train Dice: 0.8147 | Val Dice: 0.8115
[Seed 42] Epoch 16/50 | Train Dice: 0.8085 | Val Dice: 0.8200
[Seed 42] Epoch 17/50 | Train Dice: 0.8020 | Val Dice: 0.8192
[Seed 42] Epoch 18/50 | Train Dice: 0.7936 | Val Dice: 0.8009
[Seed 42] Epoch 19/50 | Train Dice: 0.8152 | Val Dice: 0.8174
[Seed 42] Epoch 20/50 | Train Dice: 0.8164 | Val Dice: 0.8202
[Seed 42] Epoch 21/50 | Train Dice: 0.8074 | Val Dice: 0.8144
[Seed 42] Epoch 22/50 | Train Dice: 0.8100 | Val Dice: 0.8186
[Seed 42] Epoch 23/50 | Train Dice: 0.8225 | Val Dice: 0.8144
[Seed 42] Epoch 24/50 | Train Dice: 0.8212 | Val Dice: 0.8216
[Seed 42] Epoch 25/50 | Train Dice: 0.8093 | Val Dice: 0.8138
[Seed 42] Epoch 26/50 | Train Dice: 0.8245 | Val Dice: 0.8090
[Seed 42] Epoch 27/50 | Train Dice: 0.8146 | Val Dice: 0.8078
[Seed 42] Epoch 28/50 | Train Dice: 0.8216 | Val Dice: 0.8167
[Seed 42] Epoch 29/50 | Train Dice: 0.8291 | Val Dice: 0.8113
[Seed 42] Epoch 30/50 | Train Dice: 0.8062 | Val Dice: 0.8184
[Seed 42] Epoch 31/50 | Train Dice: 0.8095 | Val Dice: 0.8150
[Seed 42] Epoch 32/50 | Train Dice: 0.8130 | Val Dice: 0.8153
[Seed 42] Epoch 33/50 | Train Dice: 0.8126 | Val Dice: 0.8009
[Seed 42] Epoch 34/50 | Train Dice: 0.8229 | Val Dice: 0.8127
[Seed 42] Epoch 35/50 | Train Dice: 0.8115 | Val Dice: 0.7998
[Seed 42] Epoch 36/50 | Train Dice: 0.8175 | Val Dice: 0.8182
[Seed 42] Epoch 37/50 | Train Dice: 0.8105 | Val Dice: 0.8154
[Seed 42] Epoch 38/50 | Train Dice: 0.8177 | Val Dice: 0.8199
[Seed 42] Epoch 39/50 | Train Dice: 0.8058 | Val Dice: 0.8155
[Seed 42] Epoch 40/50 | Train Dice: 0.8096 | Val Dice: 0.8122
[Seed 42] Epoch 41/50 | Train Dice: 0.8060 | Val Dice: 0.8213
[Seed 42] Epoch 42/50 | Train Dice: 0.8204 | Val Dice: 0.8145
[Seed 42] Epoch 43/50 | Train Dice: 0.8155 | Val Dice: 0.8191
[Seed 42] Epoch 44/50 | Train Dice: 0.8151 | Val Dice: 0.8229
[Seed 42] Epoch 45/50 | Train Dice: 0.8163 | Val Dice: 0.8208
[Seed 42] Epoch 46/50 | Train Dice: 0.8180 | Val Dice: 0.8195
[Seed 42] Epoch 47/50 | Train Dice: 0.8166 | Val Dice: 0.8221
[Seed 42] Epoch 48/50 | Train Dice: 0.8138 | Val Dice: 0.8210
[Seed 42] Epoch 49/50 | Train Dice: 0.8114 | Val Dice: 0.8224
[Seed 42] Epoch 50/50 | Train Dice: 0.8142 | Val Dice: 0.8263

======================================================================
STARTING RANK-8 PROBE — SEED 123
======================================================================
[Seed 123] Epoch 01/50 | Train Dice: 0.8194 | Val Dice: 0.8171
[Seed 123] Epoch 02/50 | Train Dice: 0.8289 | Val Dice: 0.8126
[Seed 123] Epoch 03/50 | Train Dice: 0.8195 | Val Dice: 0.8162
[Seed 123] Epoch 04/50 | Train Dice: 0.8118 | Val Dice: 0.8072
[Seed 123] Epoch 05/50 | Train Dice: 0.8199 | Val Dice: 0.8196
[Seed 123] Epoch 06/50 | Train Dice: 0.8129 | Val Dice: 0.8236
[Seed 123] Epoch 07/50 | Train Dice: 0.8123 | Val Dice: 0.8181
[Seed 123] Epoch 08/50 | Train Dice: 0.8114 | Val Dice: 0.8208
[Seed 123] Epoch 09/50 | Train Dice: 0.8179 | Val Dice: 0.8216
[Seed 123] Epoch 10/50 | Train Dice: 0.8169 | Val Dice: 0.8155
[Seed 123] Epoch 11/50 | Train Dice: 0.8225 | Val Dice: 0.8216
[Seed 123] Epoch 12/50 | Train Dice: 0.8245 | Val Dice: 0.8207
[Seed 123] Epoch 13/50 | Train Dice: 0.7902 | Val Dice: 0.8029
[Seed 123] Epoch 14/50 | Train Dice: 0.8148 | Val Dice: 0.8209
[Seed 123] Epoch 15/50 | Train Dice: 0.8136 | Val Dice: 0.8226
[Seed 123] Epoch 16/50 | Train Dice: 0.8229 | Val Dice: 0.8234
[Seed 123] Epoch 17/50 | Train Dice: 0.8285 | Val Dice: 0.8182
[Seed 123] Epoch 18/50 | Train Dice: 0.8237 | Val Dice: 0.8183
[Seed 123] Epoch 19/50 | Train Dice: 0.8126 | Val Dice: 0.8157
[Seed 123] Epoch 20/50 | Train Dice: 0.8180 | Val Dice: 0.8165
[Seed 123] Epoch 21/50 | Train Dice: 0.8314 | Val Dice: 0.8207
[Seed 123] Epoch 22/50 | Train Dice: 0.8207 | Val Dice: 0.8156
[Seed 123] Epoch 23/50 | Train Dice: 0.8233 | Val Dice: 0.8238
[Seed 123] Epoch 24/50 | Train Dice: 0.8223 | Val Dice: 0.8238
[Seed 123] Epoch 25/50 | Train Dice: 0.8112 | Val Dice: 0.8155
[Seed 123] Epoch 26/50 | Train Dice: 0.8147 | Val Dice: 0.8198
[Seed 123] Epoch 27/50 | Train Dice: 0.8223 | Val Dice: 0.8249
[Seed 123] Epoch 28/50 | Train Dice: 0.8114 | Val Dice: 0.8238
[Seed 123] Epoch 29/50 | Train Dice: 0.8163 | Val Dice: 0.8220
[Seed 123] Epoch 30/50 | Train Dice: 0.8009 | Val Dice: 0.8211
[Seed 123] Epoch 31/50 | Train Dice: 0.8179 | Val Dice: 0.8300
[Seed 123] Epoch 32/50 | Train Dice: 0.8108 | Val Dice: 0.8265
[Seed 123] Epoch 33/50 | Train Dice: 0.8226 | Val Dice: 0.8268
[Seed 123] Epoch 34/50 | Train Dice: 0.8113 | Val Dice: 0.8131
[Seed 123] Epoch 35/50 | Train Dice: 0.8232 | Val Dice: 0.8256
[Seed 123] Epoch 36/50 | Train Dice: 0.8125 | Val Dice: 0.8237
[Seed 123] Epoch 37/50 | Train Dice: 0.8217 | Val Dice: 0.8268
[Seed 123] Epoch 38/50 | Train Dice: 0.8224 | Val Dice: 0.8307
[Seed 123] Epoch 39/50 | Train Dice: 0.8099 | Val Dice: 0.8249
[Seed 123] Epoch 40/50 | Train Dice: 0.8179 | Val Dice: 0.8166
[Seed 123] Epoch 41/50 | Train Dice: 0.8194 | Val Dice: 0.8120
[Seed 123] Epoch 42/50 | Train Dice: 0.8188 | Val Dice: 0.8179
[Seed 123] Epoch 43/50 | Train Dice: 0.8170 | Val Dice: 0.8227
[Seed 123] Epoch 44/50 | Train Dice: 0.8138 | Val Dice: 0.8148
[Seed 123] Epoch 45/50 | Train Dice: 0.8181 | Val Dice: 0.8250
[Seed 123] Epoch 46/50 | Train Dice: 0.8210 | Val Dice: 0.8222
[Seed 123] Epoch 47/50 | Train Dice: 0.8162 | Val Dice: 0.8225
[Seed 123] Epoch 48/50 | Train Dice: 0.8331 | Val Dice: 0.8284
[Seed 123] Epoch 49/50 | Train Dice: 0.8165 | Val Dice: 0.8103
[Seed 123] Epoch 50/50 | Train Dice: 0.8077 | Val Dice: 0.8235

======================================================================
STARTING RANK-8 PROBE — SEED 2026
======================================================================
[Seed 2026] Epoch 01/50 | Train Dice: 0.8066 | Val Dice: 0.8198
[Seed 2026] Epoch 02/50 | Train Dice: 0.8187 | Val Dice: 0.8126
[Seed 2026] Epoch 03/50 | Train Dice: 0.8249 | Val Dice: 0.8210
[Seed 2026] Epoch 04/50 | Train Dice: 0.8124 | Val Dice: 0.8194
[Seed 2026] Epoch 05/50 | Train Dice: 0.8174 | Val Dice: 0.8212
[Seed 2026] Epoch 06/50 | Train Dice: 0.8115 | Val Dice: 0.8160
[Seed 2026] Epoch 07/50 | Train Dice: 0.8198 | Val Dice: 0.8255
[Seed 2026] Epoch 08/50 | Train Dice: 0.8241 | Val Dice: 0.8194
[Seed 2026] Epoch 09/50 | Train Dice: 0.8085 | Val Dice: 0.8208
[Seed 2026] Epoch 10/50 | Train Dice: 0.8261 | Val Dice: 0.8206
[Seed 2026] Epoch 11/50 | Train Dice: 0.8226 | Val Dice: 0.8261
[Seed 2026] Epoch 12/50 | Train Dice: 0.8283 | Val Dice: 0.8219
[Seed 2026] Epoch 13/50 | Train Dice: 0.8255 | Val Dice: 0.8251
[Seed 2026] Epoch 14/50 | Train Dice: 0.8174 | Val Dice: 0.8215
[Seed 2026] Epoch 15/50 | Train Dice: 0.8112 | Val Dice: 0.8180
[Seed 2026] Epoch 16/50 | Train Dice: 0.8139 | Val Dice: 0.8106
[Seed 2026] Epoch 17/50 | Train Dice: 0.8163 | Val Dice: 0.8172
[Seed 2026] Epoch 18/50 | Train Dice: 0.8156 | Val Dice: 0.8069
[Seed 2026] Epoch 19/50 | Train Dice: 0.8096 | Val Dice: 0.8114
[Seed 2026] Epoch 20/50 | Train Dice: 0.8061 | Val Dice: 0.8070
[Seed 2026] Epoch 21/50 | Train Dice: 0.8194 | Val Dice: 0.8212
[Seed 2026] Epoch 22/50 | Train Dice: 0.8286 | Val Dice: 0.8248
[Seed 2026] Epoch 23/50 | Train Dice: 0.8118 | Val Dice: 0.8185
[Seed 2026] Epoch 24/50 | Train Dice: 0.8218 | Val Dice: 0.8084
[Seed 2026] Epoch 25/50 | Train Dice: 0.8241 | Val Dice: 0.8199
[Seed 2026] Epoch 26/50 | Train Dice: 0.8094 | Val Dice: 0.8167
[Seed 2026] Epoch 27/50 | Train Dice: 0.8287 | Val Dice: 0.7949
[Seed 2026] Epoch 28/50 | Train Dice: 0.8192 | Val Dice: 0.7874
[Seed 2026] Epoch 29/50 | Train Dice: 0.8040 | Val Dice: 0.8055
[Seed 2026] Epoch 30/50 | Train Dice: 0.8158 | Val Dice: 0.8162
[Seed 2026] Epoch 31/50 | Train Dice: 0.8140 | Val Dice: 0.8162
[Seed 2026] Epoch 32/50 | Train Dice: 0.8213 | Val Dice: 0.8224
[Seed 2026] Epoch 33/50 | Train Dice: 0.8156 | Val Dice: 0.8196
[Seed 2026] Epoch 34/50 | Train Dice: 0.7947 | Val Dice: 0.8087
[Seed 2026] Epoch 35/50 | Train Dice: 0.8239 | Val Dice: 0.8161
[Seed 2026] Epoch 36/50 | Train Dice: 0.8201 | Val Dice: 0.8138
[Seed 2026] Epoch 37/50 | Train Dice: 0.8345 | Val Dice: 0.8127
[Seed 2026] Epoch 38/50 | Train Dice: 0.8093 | Val Dice: 0.8182
[Seed 2026] Epoch 39/50 | Train Dice: 0.8253 | Val Dice: 0.8169
[Seed 2026] Epoch 40/50 | Train Dice: 0.8210 | Val Dice: 0.8116
[Seed 2026] Epoch 41/50 | Train Dice: 0.8245 | Val Dice: 0.8142
[Seed 2026] Epoch 42/50 | Train Dice: 0.8235 | Val Dice: 0.8176
[Seed 2026] Epoch 43/50 | Train Dice: 0.8208 | Val Dice: 0.8188
[Seed 2026] Epoch 44/50 | Train Dice: 0.8046 | Val Dice: 0.8106
[Seed 2026] Epoch 45/50 | Train Dice: 0.8204 | Val Dice: 0.8186
[Seed 2026] Epoch 46/50 | Train Dice: 0.8146 | Val Dice: 0.7967
[Seed 2026] Epoch 47/50 | Train Dice: 0.8102 | Val Dice: 0.8117
[Seed 2026] Epoch 48/50 | Train Dice: 0.8191 | Val Dice: 0.8174
[Seed 2026] Epoch 49/50 | Train Dice: 0.8196 | Val Dice: 0.8096
[Seed 2026] Epoch 50/50 | Train Dice: 0.8223 | Val Dice: 0.8154

In [102]:
# storing values into .csv file
import pandas as pd

history_df = pd.DataFrame(history)
csv_path = "/kaggle/working/stellar_rank8_glas_probe_3_SEED_history.csv"
history_df.to_csv(csv_path, index=False)

display(history_df.head())

   epoch  train_dice  train_miou  val_dice  val_miou
0      1    0.698239    0.521126  0.774365  0.608564
1      1    0.777578    0.625968  0.789211  0.637360
2      2    0.778144    0.631434  0.798050  0.647305
3      3    0.792974    0.644506  0.792148  0.634817
4      4    0.789365    0.638857  0.795159  0.649468

In [103]:
# Summarize results of lowrank
for seed, result in rank8_results.items():
    print("\n" + "=" * 60)
    print(f"RANK-15 — SEED {seed}")
    print("=" * 60)
    print(f"Best epoch : {result['best_epoch']}")
    print(f"Val Dice   : {result['best_val_dice']:.4f}")

============================================================
RANK-15 — SEED 42
============================================================
Best epoch : 50
Val Dice   : 0.8263

============================================================
RANK-15 — SEED 123
============================================================
Best epoch : 38
Val Dice   : 0.8307

============================================================
RANK-15 — SEED 2026
============================================================
Best epoch : 11
Val Dice   : 0.8261

In [104]:
# Feature rank and Effective rank for Rank-32 model
import torch

batch = next(iter(probe_val_loader))
images = batch["image"].to(device)
with torch.no_grad():
    outputs = rank8_backbone.encode({"image": images})

rank8_features = outputs["dense"]
X = rank8_features[0]

# Center exactly as done during truncation
X_centered = X - X.mean(dim=0, keepdim=True)
S = torch.linalg.svdvals(X_centered)
numerical_rank = (S > 1e-5).sum().item()
print("Numerical rank:", numerical_rank)
print("Rank-15 effective rank:",effective_rank(rank8_features[0]))

Numerical rank: 8
Rank-15 effective rank: 7.148799896240234

So, we find that, 
After taking average of all 3 SEED best val Dice
For Dense model, average best val Dice = 0.8555 
For Lowrank Mode, average best val Dice = 0.7068
For Rank-64 model, average best val Dice = 0.8557 (better than Dense model)
For Rank-32 model, average best val Dice = 0.8523
For Rank-16 model, average best val Dice = 0.8406
For Rank-15 model, average best val Dice = 0.8412
For Rank-8 model, average best val Dice = 0.8277

So, according to the model rank selection criteria based on val Dice, we can see that, for Rank-64, val Dice is more (0.02337%). So, we choose the Rank-64 model for TestA, TestB tests. 
Dense model rank = 196, Rank-64 model rank = 64, total compression = 67.34%

*Next step: taking Rank-64 model, test on TestA, TestB and compare performance against Dense and Lowrank model*

### Dense Model Testing

In [ ]:
from src.models.downstream.segmentation import SegmentationProbing

dense_model = SegmentationProbing(
    model_backbone=model,
    is_baseline=False,
    feature_key="dense",
    feature_dim=768,
    num_classes=2,
    freeze_backbone=True,
    freeze_model=False,
    resize_output=(224, 224),
).to(device)

  # We'll be using Adam with weighted decay optimizer
optimizer = torch.optim.AdamW(
    filter(lambda p: p.requires_grad, dense_model.parameters()),
    lr=1e-3,weight_decay=1e-4,)
# We'll be using cross entropy loss
criterion = torch.nn.CrossEntropyLoss()

In [105]:
# Dense model running for seed 42, 123, 2026
import random

history = []

def train_dense_probe(seed, num_epochs=50):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

    # Best checkpoint in memory
    best_val_dice = -1.0
    best_epoch = -1
    best_state = None

    # Training
    for epoch in range(num_epochs):
        train_metrics = run_epoch(dense_model,probe_train_loader,optimizer=optimizer,
            criterion=criterion,device=device,)
        
        val_metrics = run_epoch(dense_model,probe_val_loader,optimizer=None,
            criterion=criterion,device=device,)

        history.append({
            "epoch": epoch + 1,
            "train_dice": train_metrics["gland_dice"],
            "train_miou": train_metrics["miou"],
            "val_dice": val_metrics["gland_dice"],
            "val_miou": val_metrics["miou"],
        })

        print(
            f"[Seed {seed}] "
            f"Epoch {epoch+1:02d}/{num_epochs} | "
            f"Train Dice: {train_metrics['gland_dice']:.4f} | "
            f"Val Dice: {val_metrics['gland_dice']:.4f}"
        )

        if val_metrics["gland_dice"] > best_val_dice:
            best_val_dice = val_metrics["gland_dice"]
            best_epoch = epoch + 1
            best_state = {
                k: v.detach().cpu().clone()
                for k, v in dense_model.state_dict().items()
            }



    # Restore best model
    dense_model.load_state_dict(best_state)
    dense_model.eval()

    # TestA
    testA_metrics = run_epoch(dense_model,testA_loader,optimizer=None,
        criterion=criterion,device=device,)

    # TestB
    testB_metrics = run_epoch(dense_model,testB_loader,optimizer=None,
        criterion=criterion,device=device,)
    
    return {
        "seed": seed,
        "best_epoch": best_epoch,
        "best_val_dice": best_val_dice,
        "testA": testA_metrics,
        "testB": testB_metrics,
        "history": history,
    }

In [106]:
dense_results = {}
for seed in [42, 123, 2026]:
    print("\n" + "=" * 70)
    print(f"STARTING DENSE PROBE — SEED {seed}")
    print("=" * 70)
    dense_results[seed] = train_dense_probe(seed=seed,num_epochs=50)

======================================================================
STARTING DENSE PROBE — SEED 42
======================================================================
[Seed 42] Epoch 01/50 | Train Dice: 0.8486 | Val Dice: 0.8512
[Seed 42] Epoch 02/50 | Train Dice: 0.8553 | Val Dice: 0.8491
[Seed 42] Epoch 03/50 | Train Dice: 0.8518 | Val Dice: 0.8507
[Seed 42] Epoch 04/50 | Train Dice: 0.8533 | Val Dice: 0.8485
[Seed 42] Epoch 05/50 | Train Dice: 0.8531 | Val Dice: 0.8514
[Seed 42] Epoch 06/50 | Train Dice: 0.8578 | Val Dice: 0.8449
[Seed 42] Epoch 07/50 | Train Dice: 0.8540 | Val Dice: 0.8483
[Seed 42] Epoch 08/50 | Train Dice: 0.8506 | Val Dice: 0.8473
[Seed 42] Epoch 09/50 | Train Dice: 0.8600 | Val Dice: 0.8496
[Seed 42] Epoch 10/50 | Train Dice: 0.8525 | Val Dice: 0.8518
[Seed 42] Epoch 11/50 | Train Dice: 0.8460 | Val Dice: 0.8492
[Seed 42] Epoch 12/50 | Train Dice: 0.8618 | Val Dice: 0.8503
[Seed 42] Epoch 13/50 | Train Dice: 0.8564 | Val Dice: 0.8493
[Seed 42] Epoch 14/50 | Train Dice: 0.8555 | Val Dice: 0.8466
[Seed 42] Epoch 15/50 | Train Dice: 0.8590 | Val Dice: 0.8491
[Seed 42] Epoch 16/50 | Train Dice: 0.8572 | Val Dice: 0.8521
[Seed 42] Epoch 17/50 | Train Dice: 0.8520 | Val Dice: 0.8520
[Seed 42] Epoch 18/50 | Train Dice: 0.8515 | Val Dice: 0.8483
[Seed 42] Epoch 19/50 | Train Dice: 0.8566 | Val Dice: 0.8495
[Seed 42] Epoch 20/50 | Train Dice: 0.8573 | Val Dice: 0.8516
[Seed 42] Epoch 21/50 | Train Dice: 0.8534 | Val Dice: 0.8474
[Seed 42] Epoch 22/50 | Train Dice: 0.8475 | Val Dice: 0.8482
[Seed 42] Epoch 23/50 | Train Dice: 0.8632 | Val Dice: 0.8497
[Seed 42] Epoch 24/50 | Train Dice: 0.8584 | Val Dice: 0.8506
[Seed 42] Epoch 25/50 | Train Dice: 0.8480 | Val Dice: 0.8525
[Seed 42] Epoch 26/50 | Train Dice: 0.8598 | Val Dice: 0.8484
[Seed 42] Epoch 27/50 | Train Dice: 0.8540 | Val Dice: 0.8488
[Seed 42] Epoch 28/50 | Train Dice: 0.8576 | Val Dice: 0.8493
[Seed 42] Epoch 29/50 | Train Dice: 0.8680 | Val Dice: 0.8473
[Seed 42] Epoch 30/50 | Train Dice: 0.8408 | Val Dice: 0.8523
[Seed 42] Epoch 31/50 | Train Dice: 0.8592 | Val Dice: 0.8511
[Seed 42] Epoch 32/50 | Train Dice: 0.8567 | Val Dice: 0.8510
[Seed 42] Epoch 33/50 | Train Dice: 0.8495 | Val Dice: 0.8455
[Seed 42] Epoch 34/50 | Train Dice: 0.8619 | Val Dice: 0.8491
[Seed 42] Epoch 35/50 | Train Dice: 0.8486 | Val Dice: 0.8485
[Seed 42] Epoch 36/50 | Train Dice: 0.8474 | Val Dice: 0.8484
[Seed 42] Epoch 37/50 | Train Dice: 0.8470 | Val Dice: 0.8487
[Seed 42] Epoch 38/50 | Train Dice: 0.8524 | Val Dice: 0.8491
[Seed 42] Epoch 39/50 | Train Dice: 0.8498 | Val Dice: 0.8516
[Seed 42] Epoch 40/50 | Train Dice: 0.8457 | Val Dice: 0.8491
[Seed 42] Epoch 41/50 | Train Dice: 0.8531 | Val Dice: 0.8511
[Seed 42] Epoch 42/50 | Train Dice: 0.8579 | Val Dice: 0.8490
[Seed 42] Epoch 43/50 | Train Dice: 0.8493 | Val Dice: 0.8489
[Seed 42] Epoch 44/50 | Train Dice: 0.8538 | Val Dice: 0.8518
[Seed 42] Epoch 45/50 | Train Dice: 0.8594 | Val Dice: 0.8522
[Seed 42] Epoch 46/50 | Train Dice: 0.8583 | Val Dice: 0.8523
[Seed 42] Epoch 47/50 | Train Dice: 0.8499 | Val Dice: 0.8505
[Seed 42] Epoch 48/50 | Train Dice: 0.8515 | Val Dice: 0.8512
[Seed 42] Epoch 49/50 | Train Dice: 0.8507 | Val Dice: 0.8521
[Seed 42] Epoch 50/50 | Train Dice: 0.8556 | Val Dice: 0.8510

======================================================================
STARTING DENSE PROBE — SEED 123
======================================================================
[Seed 123] Epoch 01/50 | Train Dice: 0.8533 | Val Dice: 0.8496
[Seed 123] Epoch 02/50 | Train Dice: 0.8596 | Val Dice: 0.8476
[Seed 123] Epoch 03/50 | Train Dice: 0.8581 | Val Dice: 0.8507
[Seed 123] Epoch 04/50 | Train Dice: 0.8514 | Val Dice: 0.8484
[Seed 123] Epoch 05/50 | Train Dice: 0.8556 | Val Dice: 0.8506
[Seed 123] Epoch 06/50 | Train Dice: 0.8505 | Val Dice: 0.8518
[Seed 123] Epoch 07/50 | Train Dice: 0.8445 | Val Dice: 0.8521
[Seed 123] Epoch 08/50 | Train Dice: 0.8561 | Val Dice: 0.8517
[Seed 123] Epoch 09/50 | Train Dice: 0.8587 | Val Dice: 0.8498
[Seed 123] Epoch 10/50 | Train Dice: 0.8508 | Val Dice: 0.8471
[Seed 123] Epoch 11/50 | Train Dice: 0.8602 | Val Dice: 0.8498
[Seed 123] Epoch 12/50 | Train Dice: 0.8604 | Val Dice: 0.8499
[Seed 123] Epoch 13/50 | Train Dice: 0.8386 | Val Dice: 0.8467
[Seed 123] Epoch 14/50 | Train Dice: 0.8570 | Val Dice: 0.8494
[Seed 123] Epoch 15/50 | Train Dice: 0.8476 | Val Dice: 0.8478
[Seed 123] Epoch 16/50 | Train Dice: 0.8588 | Val Dice: 0.8497
[Seed 123] Epoch 17/50 | Train Dice: 0.8624 | Val Dice: 0.8512
[Seed 123] Epoch 18/50 | Train Dice: 0.8604 | Val Dice: 0.8499
[Seed 123] Epoch 19/50 | Train Dice: 0.8548 | Val Dice: 0.8494
[Seed 123] Epoch 20/50 | Train Dice: 0.8489 | Val Dice: 0.8451
[Seed 123] Epoch 21/50 | Train Dice: 0.8602 | Val Dice: 0.8505
[Seed 123] Epoch 22/50 | Train Dice: 0.8614 | Val Dice: 0.8454
[Seed 123] Epoch 23/50 | Train Dice: 0.8536 | Val Dice: 0.8519
[Seed 123] Epoch 24/50 | Train Dice: 0.8491 | Val Dice: 0.8517
[Seed 123] Epoch 25/50 | Train Dice: 0.8519 | Val Dice: 0.8518
[Seed 123] Epoch 26/50 | Train Dice: 0.8513 | Val Dice: 0.8475
[Seed 123] Epoch 27/50 | Train Dice: 0.8600 | Val Dice: 0.8500
[Seed 123] Epoch 28/50 | Train Dice: 0.8477 | Val Dice: 0.8523
[Seed 123] Epoch 29/50 | Train Dice: 0.8512 | Val Dice: 0.8519
[Seed 123] Epoch 30/50 | Train Dice: 0.8435 | Val Dice: 0.8521
[Seed 123] Epoch 31/50 | Train Dice: 0.8579 | Val Dice: 0.8519
[Seed 123] Epoch 32/50 | Train Dice: 0.8468 | Val Dice: 0.8523
[Seed 123] Epoch 33/50 | Train Dice: 0.8518 | Val Dice: 0.8509
[Seed 123] Epoch 34/50 | Train Dice: 0.8492 | Val Dice: 0.8459
[Seed 123] Epoch 35/50 | Train Dice: 0.8566 | Val Dice: 0.8512
[Seed 123] Epoch 36/50 | Train Dice: 0.8522 | Val Dice: 0.8503
[Seed 123] Epoch 37/50 | Train Dice: 0.8534 | Val Dice: 0.8523
[Seed 123] Epoch 38/50 | Train Dice: 0.8534 | Val Dice: 0.8522
[Seed 123] Epoch 39/50 | Train Dice: 0.8560 | Val Dice: 0.8519
[Seed 123] Epoch 40/50 | Train Dice: 0.8453 | Val Dice: 0.8516
[Seed 123] Epoch 41/50 | Train Dice: 0.8599 | Val Dice: 0.8483
[Seed 123] Epoch 42/50 | Train Dice: 0.8529 | Val Dice: 0.8525
[Seed 123] Epoch 43/50 | Train Dice: 0.8559 | Val Dice: 0.8497
[Seed 123] Epoch 44/50 | Train Dice: 0.8506 | Val Dice: 0.8519
[Seed 123] Epoch 45/50 | Train Dice: 0.8550 | Val Dice: 0.8518
[Seed 123] Epoch 46/50 | Train Dice: 0.8543 | Val Dice: 0.8510
[Seed 123] Epoch 47/50 | Train Dice: 0.8591 | Val Dice: 0.8486
[Seed 123] Epoch 48/50 | Train Dice: 0.8665 | Val Dice: 0.8526
[Seed 123] Epoch 49/50 | Train Dice: 0.8531 | Val Dice: 0.8503
[Seed 123] Epoch 50/50 | Train Dice: 0.8482 | Val Dice: 0.8515

======================================================================
STARTING DENSE PROBE — SEED 2026
======================================================================
[Seed 2026] Epoch 01/50 | Train Dice: 0.8480 | Val Dice: 0.8500
[Seed 2026] Epoch 02/50 | Train Dice: 0.8531 | Val Dice: 0.8504
[Seed 2026] Epoch 03/50 | Train Dice: 0.8538 | Val Dice: 0.8486
[Seed 2026] Epoch 04/50 | Train Dice: 0.8513 | Val Dice: 0.8501
[Seed 2026] Epoch 05/50 | Train Dice: 0.8570 | Val Dice: 0.8495
[Seed 2026] Epoch 06/50 | Train Dice: 0.8439 | Val Dice: 0.8486
[Seed 2026] Epoch 07/50 | Train Dice: 0.8564 | Val Dice: 0.8505
[Seed 2026] Epoch 08/50 | Train Dice: 0.8485 | Val Dice: 0.8509
[Seed 2026] Epoch 09/50 | Train Dice: 0.8465 | Val Dice: 0.8479
[Seed 2026] Epoch 10/50 | Train Dice: 0.8618 | Val Dice: 0.8514
[Seed 2026] Epoch 11/50 | Train Dice: 0.8573 | Val Dice: 0.8522
[Seed 2026] Epoch 12/50 | Train Dice: 0.8579 | Val Dice: 0.8494
[Seed 2026] Epoch 13/50 | Train Dice: 0.8524 | Val Dice: 0.8511
[Seed 2026] Epoch 14/50 | Train Dice: 0.8572 | Val Dice: 0.8500
[Seed 2026] Epoch 15/50 | Train Dice: 0.8534 | Val Dice: 0.8504
[Seed 2026] Epoch 16/50 | Train Dice: 0.8491 | Val Dice: 0.8516
[Seed 2026] Epoch 17/50 | Train Dice: 0.8561 | Val Dice: 0.8524
[Seed 2026] Epoch 18/50 | Train Dice: 0.8543 | Val Dice: 0.8484
[Seed 2026] Epoch 19/50 | Train Dice: 0.8459 | Val Dice: 0.8512
[Seed 2026] Epoch 20/50 | Train Dice: 0.8459 | Val Dice: 0.8466
[Seed 2026] Epoch 21/50 | Train Dice: 0.8384 | Val Dice: 0.8500
[Seed 2026] Epoch 22/50 | Train Dice: 0.8564 | Val Dice: 0.8522
[Seed 2026] Epoch 23/50 | Train Dice: 0.8522 | Val Dice: 0.8522
[Seed 2026] Epoch 24/50 | Train Dice: 0.8525 | Val Dice: 0.8491
[Seed 2026] Epoch 25/50 | Train Dice: 0.8512 | Val Dice: 0.8517
[Seed 2026] Epoch 26/50 | Train Dice: 0.8588 | Val Dice: 0.8463
[Seed 2026] Epoch 27/50 | Train Dice: 0.8561 | Val Dice: 0.8485
[Seed 2026] Epoch 28/50 | Train Dice: 0.8498 | Val Dice: 0.8499
[Seed 2026] Epoch 29/50 | Train Dice: 0.8522 | Val Dice: 0.8513
[Seed 2026] Epoch 30/50 | Train Dice: 0.8477 | Val Dice: 0.8522
[Seed 2026] Epoch 31/50 | Train Dice: 0.8565 | Val Dice: 0.8522
[Seed 2026] Epoch 32/50 | Train Dice: 0.8546 | Val Dice: 0.8523
[Seed 2026] Epoch 33/50 | Train Dice: 0.8439 | Val Dice: 0.8512
[Seed 2026] Epoch 34/50 | Train Dice: 0.8388 | Val Dice: 0.8480
[Seed 2026] Epoch 35/50 | Train Dice: 0.8543 | Val Dice: 0.8491
[Seed 2026] Epoch 36/50 | Train Dice: 0.8584 | Val Dice: 0.8501
[Seed 2026] Epoch 37/50 | Train Dice: 0.8612 | Val Dice: 0.8517
[Seed 2026] Epoch 38/50 | Train Dice: 0.8518 | Val Dice: 0.8510
[Seed 2026] Epoch 39/50 | Train Dice: 0.8637 | Val Dice: 0.8511
[Seed 2026] Epoch 40/50 | Train Dice: 0.8623 | Val Dice: 0.8503
[Seed 2026] Epoch 41/50 | Train Dice: 0.8595 | Val Dice: 0.8495
[Seed 2026] Epoch 42/50 | Train Dice: 0.8582 | Val Dice: 0.8515
[Seed 2026] Epoch 43/50 | Train Dice: 0.8634 | Val Dice: 0.8507
[Seed 2026] Epoch 44/50 | Train Dice: 0.8474 | Val Dice: 0.8475
[Seed 2026] Epoch 45/50 | Train Dice: 0.8542 | Val Dice: 0.8523
[Seed 2026] Epoch 46/50 | Train Dice: 0.8573 | Val Dice: 0.8502
[Seed 2026] Epoch 47/50 | Train Dice: 0.8545 | Val Dice: 0.8496
[Seed 2026] Epoch 48/50 | Train Dice: 0.8577 | Val Dice: 0.8504
[Seed 2026] Epoch 49/50 | Train Dice: 0.8549 | Val Dice: 0.8481
[Seed 2026] Epoch 50/50 | Train Dice: 0.8628 | Val Dice: 0.8490

In [107]:
# Summary of Dense model result
def get_summary(results, split, metric):

    values = np.array([result[split][metric]for result in results.values()])
    return (values.mean(),values.std(ddof=1),)


for split in ["testA", "testB"]:
    print(f"\n===== {split.upper()} =====")
    for metric in ["gland_dice","gland_iou","miou",]:
        mean, std = get_summary( dense_results,split,metric,)
        print(f"{metric:15s} | {mean:.4f} ± {std:.4f}")

===== TESTA =====
gland_dice      | 0.8473 ± 0.0002
gland_iou       | 0.7351 ± 0.0002
miou            | 0.7296 ± 0.0008

===== TESTB =====
gland_dice      | 0.8483 ± 0.0001
gland_iou       | 0.7366 ± 0.0001
miou            | 0.6779 ± 0.0007

### Lowrank Model Testing

In [108]:
from src.models.downstream.segmentation import SegmentationProbing
lowrank_model = SegmentationProbing(
    model_backbone=model,
    is_baseline=False,
    feature_key="lowrank",
    feature_dim=768,
    num_classes=2,
    freeze_backbone=True,
    freeze_model=False,
    resize_output=(224, 224),
).to(device)


optimizer = torch.optim.AdamW(filter(lambda p: p.requires_grad,lowrank_model.parameters()),
    lr=1e-3,
    weight_decay=1e-4,)
criterion = torch.nn.CrossEntropyLoss()

In [109]:
import random

history=[]
# def train_spatial_probe(feature_key, seed, num_epochs=50):
def train_spatial_probe(seed, num_epochs=50):
    # Training randomness
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

    # Best checkpoint in memory
    best_val_dice = -1.0
    best_epoch = -1
    best_state = None
    
    # Training
    for epoch in range(num_epochs):
        train_metrics = run_epoch(lowrank_model,probe_train_loader,optimizer=optimizer,
            criterion=criterion,
            device=device,)
        
        val_metrics = run_epoch(lowrank_model,probe_val_loader,optimizer=None,
            criterion=criterion,
            device=device,)

        history.append({
            "epoch": epoch + 1,
            "train_dice": train_metrics["gland_dice"],
            "train_miou": train_metrics["miou"],
            "val_dice": val_metrics["gland_dice"],
            "val_miou": val_metrics["miou"],
        })

        print(
            f"[Seed {seed}] "
            f"Epoch {epoch+1:02d}/{num_epochs} | "
            f"Train Dice: {train_metrics['gland_dice']:.4f} | "
            f"Val Dice: {val_metrics['gland_dice']:.4f}"
        )

        if val_metrics["gland_dice"] > best_val_dice:
            best_val_dice = val_metrics["gland_dice"]
            best_epoch = epoch + 1
            best_state = {
                k: v.detach().cpu().clone()
                for k, v in lowrank_model.state_dict().items()
            }

    # Restore best model
    lowrank_model.load_state_dict(best_state)
    lowrank_model.eval()
    
    # TestA
    testA_metrics = run_epoch(lowrank_model,testA_loader,optimizer=None,
        criterion=criterion,device=device,)

    # TestB
    testB_metrics = run_epoch(lowrank_model,testB_loader,optimizer=None,
        criterion=criterion,device=device,)
    
    return {
        "seed": seed,
        "best_epoch": best_epoch,
        "best_val_dice": best_val_dice,
        "testA": testA_metrics,
        "testB": testB_metrics,
        "history": history,
    }

In [110]:
# Running for 3 SEEDS
lowrank_results = {}
for seed in [42, 123, 2026]:
    print("\n" + "=" * 70)
    print(f"STARTING LOWRANK PROBE — SEED {seed}")
    print("=" * 70)
    lowrank_results[seed] = train_spatial_probe(seed=seed,num_epochs=50,)

======================================================================
STARTING LOWRANK PROBE — SEED 42
======================================================================
[Seed 42] Epoch 01/50 | Train Dice: 0.5567 | Val Dice: 0.6679
[Seed 42] Epoch 02/50 | Train Dice: 0.5959 | Val Dice: 0.6810
[Seed 42] Epoch 03/50 | Train Dice: 0.6009 | Val Dice: 0.6386
[Seed 42] Epoch 04/50 | Train Dice: 0.6184 | Val Dice: 0.6559
[Seed 42] Epoch 05/50 | Train Dice: 0.6523 | Val Dice: 0.6890
[Seed 42] Epoch 06/50 | Train Dice: 0.6187 | Val Dice: 0.6410
[Seed 42] Epoch 07/50 | Train Dice: 0.6206 | Val Dice: 0.6487
[Seed 42] Epoch 08/50 | Train Dice: 0.6048 | Val Dice: 0.6043
[Seed 42] Epoch 09/50 | Train Dice: 0.6517 | Val Dice: 0.6352
[Seed 42] Epoch 10/50 | Train Dice: 0.6639 | Val Dice: 0.6168
[Seed 42] Epoch 11/50 | Train Dice: 0.6562 | Val Dice: 0.5693
[Seed 42] Epoch 12/50 | Train Dice: 0.6572 | Val Dice: 0.6292
[Seed 42] Epoch 13/50 | Train Dice: 0.6718 | Val Dice: 0.6413
[Seed 42] Epoch 14/50 | Train Dice: 0.6566 | Val Dice: 0.5945
[Seed 42] Epoch 15/50 | Train Dice: 0.6645 | Val Dice: 0.6484
[Seed 42] Epoch 16/50 | Train Dice: 0.6580 | Val Dice: 0.7044
[Seed 42] Epoch 17/50 | Train Dice: 0.6816 | Val Dice: 0.6537
[Seed 42] Epoch 18/50 | Train Dice: 0.6630 | Val Dice: 0.6624
[Seed 42] Epoch 19/50 | Train Dice: 0.6613 | Val Dice: 0.6515
[Seed 42] Epoch 20/50 | Train Dice: 0.6501 | Val Dice: 0.6983
[Seed 42] Epoch 21/50 | Train Dice: 0.6557 | Val Dice: 0.6412
[Seed 42] Epoch 22/50 | Train Dice: 0.6714 | Val Dice: 0.5628
[Seed 42] Epoch 23/50 | Train Dice: 0.6577 | Val Dice: 0.6118
[Seed 42] Epoch 24/50 | Train Dice: 0.6527 | Val Dice: 0.6249
[Seed 42] Epoch 25/50 | Train Dice: 0.6625 | Val Dice: 0.6675
[Seed 42] Epoch 26/50 | Train Dice: 0.6785 | Val Dice: 0.6060
[Seed 42] Epoch 27/50 | Train Dice: 0.6781 | Val Dice: 0.5659
[Seed 42] Epoch 28/50 | Train Dice: 0.6725 | Val Dice: 0.6531
[Seed 42] Epoch 29/50 | Train Dice: 0.6886 | Val Dice: 0.5340
[Seed 42] Epoch 30/50 | Train Dice: 0.6445 | Val Dice: 0.6562
[Seed 42] Epoch 31/50 | Train Dice: 0.6628 | Val Dice: 0.6521
[Seed 42] Epoch 32/50 | Train Dice: 0.6512 | Val Dice: 0.6060
[Seed 42] Epoch 33/50 | Train Dice: 0.6529 | Val Dice: 0.6199
[Seed 42] Epoch 34/50 | Train Dice: 0.6998 | Val Dice: 0.6130
[Seed 42] Epoch 35/50 | Train Dice: 0.6842 | Val Dice: 0.6008
[Seed 42] Epoch 36/50 | Train Dice: 0.6789 | Val Dice: 0.6663
[Seed 42] Epoch 37/50 | Train Dice: 0.6748 | Val Dice: 0.6310
[Seed 42] Epoch 38/50 | Train Dice: 0.6715 | Val Dice: 0.6146
[Seed 42] Epoch 39/50 | Train Dice: 0.6731 | Val Dice: 0.6612
[Seed 42] Epoch 40/50 | Train Dice: 0.6622 | Val Dice: 0.6428
[Seed 42] Epoch 41/50 | Train Dice: 0.6724 | Val Dice: 0.6911
[Seed 42] Epoch 42/50 | Train Dice: 0.6415 | Val Dice: 0.6402
[Seed 42] Epoch 43/50 | Train Dice: 0.6631 | Val Dice: 0.6461
[Seed 42] Epoch 44/50 | Train Dice: 0.6971 | Val Dice: 0.6816
[Seed 42] Epoch 45/50 | Train Dice: 0.6826 | Val Dice: 0.6957
[Seed 42] Epoch 46/50 | Train Dice: 0.6815 | Val Dice: 0.7069
[Seed 42] Epoch 47/50 | Train Dice: 0.6857 | Val Dice: 0.6660
[Seed 42] Epoch 48/50 | Train Dice: 0.6697 | Val Dice: 0.6525
[Seed 42] Epoch 49/50 | Train Dice: 0.6841 | Val Dice: 0.6768
[Seed 42] Epoch 50/50 | Train Dice: 0.6705 | Val Dice: 0.5971

======================================================================
STARTING LOWRANK PROBE — SEED 123
======================================================================
[Seed 123] Epoch 01/50 | Train Dice: 0.6755 | Val Dice: 0.6368
[Seed 123] Epoch 02/50 | Train Dice: 0.6697 | Val Dice: 0.6534
[Seed 123] Epoch 03/50 | Train Dice: 0.7002 | Val Dice: 0.6610
[Seed 123] Epoch 04/50 | Train Dice: 0.6796 | Val Dice: 0.6614
[Seed 123] Epoch 05/50 | Train Dice: 0.6821 | Val Dice: 0.6371
[Seed 123] Epoch 06/50 | Train Dice: 0.6582 | Val Dice: 0.6391
[Seed 123] Epoch 07/50 | Train Dice: 0.6478 | Val Dice: 0.6935
[Seed 123] Epoch 08/50 | Train Dice: 0.6550 | Val Dice: 0.6483
[Seed 123] Epoch 09/50 | Train Dice: 0.6777 | Val Dice: 0.6672
[Seed 123] Epoch 10/50 | Train Dice: 0.6889 | Val Dice: 0.6666
[Seed 123] Epoch 11/50 | Train Dice: 0.6737 | Val Dice: 0.6594
[Seed 123] Epoch 12/50 | Train Dice: 0.6794 | Val Dice: 0.6514
[Seed 123] Epoch 13/50 | Train Dice: 0.6343 | Val Dice: 0.5786
[Seed 123] Epoch 14/50 | Train Dice: 0.6865 | Val Dice: 0.6429
[Seed 123] Epoch 15/50 | Train Dice: 0.6818 | Val Dice: 0.6249
[Seed 123] Epoch 16/50 | Train Dice: 0.6795 | Val Dice: 0.6791
[Seed 123] Epoch 17/50 | Train Dice: 0.6965 | Val Dice: 0.7133
[Seed 123] Epoch 18/50 | Train Dice: 0.6599 | Val Dice: 0.6573
[Seed 123] Epoch 19/50 | Train Dice: 0.6747 | Val Dice: 0.6200
[Seed 123] Epoch 20/50 | Train Dice: 0.6709 | Val Dice: 0.6398
[Seed 123] Epoch 21/50 | Train Dice: 0.6830 | Val Dice: 0.6488
[Seed 123] Epoch 22/50 | Train Dice: 0.6878 | Val Dice: 0.6508
[Seed 123] Epoch 23/50 | Train Dice: 0.6792 | Val Dice: 0.6214
[Seed 123] Epoch 24/50 | Train Dice: 0.6848 | Val Dice: 0.6651
[Seed 123] Epoch 25/50 | Train Dice: 0.6692 | Val Dice: 0.6768
[Seed 123] Epoch 26/50 | Train Dice: 0.6720 | Val Dice: 0.6993
[Seed 123] Epoch 27/50 | Train Dice: 0.6717 | Val Dice: 0.6571
[Seed 123] Epoch 28/50 | Train Dice: 0.6911 | Val Dice: 0.6959
[Seed 123] Epoch 29/50 | Train Dice: 0.6977 | Val Dice: 0.6739
[Seed 123] Epoch 30/50 | Train Dice: 0.6652 | Val Dice: 0.6843
[Seed 123] Epoch 31/50 | Train Dice: 0.6855 | Val Dice: 0.6862
[Seed 123] Epoch 32/50 | Train Dice: 0.6544 | Val Dice: 0.6551
[Seed 123] Epoch 33/50 | Train Dice: 0.6769 | Val Dice: 0.6453
[Seed 123] Epoch 34/50 | Train Dice: 0.6854 | Val Dice: 0.6621
[Seed 123] Epoch 35/50 | Train Dice: 0.6910 | Val Dice: 0.6748
[Seed 123] Epoch 36/50 | Train Dice: 0.6705 | Val Dice: 0.6753
[Seed 123] Epoch 37/50 | Train Dice: 0.6723 | Val Dice: 0.6403
[Seed 123] Epoch 38/50 | Train Dice: 0.6970 | Val Dice: 0.6423
[Seed 123] Epoch 39/50 | Train Dice: 0.6680 | Val Dice: 0.6574
[Seed 123] Epoch 40/50 | Train Dice: 0.6806 | Val Dice: 0.6700
[Seed 123] Epoch 41/50 | Train Dice: 0.6912 | Val Dice: 0.6581
[Seed 123] Epoch 42/50 | Train Dice: 0.6919 | Val Dice: 0.6962
[Seed 123] Epoch 43/50 | Train Dice: 0.6857 | Val Dice: 0.6798
[Seed 123] Epoch 44/50 | Train Dice: 0.6799 | Val Dice: 0.6450
[Seed 123] Epoch 45/50 | Train Dice: 0.6911 | Val Dice: 0.6510
[Seed 123] Epoch 46/50 | Train Dice: 0.6772 | Val Dice: 0.6681
[Seed 123] Epoch 47/50 | Train Dice: 0.6935 | Val Dice: 0.6840
[Seed 123] Epoch 48/50 | Train Dice: 0.6899 | Val Dice: 0.6773
[Seed 123] Epoch 49/50 | Train Dice: 0.6785 | Val Dice: 0.6814
[Seed 123] Epoch 50/50 | Train Dice: 0.6754 | Val Dice: 0.6741

======================================================================
STARTING LOWRANK PROBE — SEED 2026
======================================================================
[Seed 2026] Epoch 01/50 | Train Dice: 0.6757 | Val Dice: 0.6784
[Seed 2026] Epoch 02/50 | Train Dice: 0.6862 | Val Dice: 0.6618
[Seed 2026] Epoch 03/50 | Train Dice: 0.6821 | Val Dice: 0.6393
[Seed 2026] Epoch 04/50 | Train Dice: 0.6538 | Val Dice: 0.6483
[Seed 2026] Epoch 05/50 | Train Dice: 0.6901 | Val Dice: 0.6760
[Seed 2026] Epoch 06/50 | Train Dice: 0.6357 | Val Dice: 0.6427
[Seed 2026] Epoch 07/50 | Train Dice: 0.6617 | Val Dice: 0.6751
[Seed 2026] Epoch 08/50 | Train Dice: 0.6997 | Val Dice: 0.6485
[Seed 2026] Epoch 09/50 | Train Dice: 0.6833 | Val Dice: 0.6165
[Seed 2026] Epoch 10/50 | Train Dice: 0.6673 | Val Dice: 0.6703
[Seed 2026] Epoch 11/50 | Train Dice: 0.6826 | Val Dice: 0.6719
[Seed 2026] Epoch 12/50 | Train Dice: 0.6817 | Val Dice: 0.6560
[Seed 2026] Epoch 13/50 | Train Dice: 0.6898 | Val Dice: 0.6214
[Seed 2026] Epoch 14/50 | Train Dice: 0.6690 | Val Dice: 0.6777
[Seed 2026] Epoch 15/50 | Train Dice: 0.6811 | Val Dice: 0.6851
[Seed 2026] Epoch 16/50 | Train Dice: 0.6724 | Val Dice: 0.6699
[Seed 2026] Epoch 17/50 | Train Dice: 0.6706 | Val Dice: 0.6141
[Seed 2026] Epoch 18/50 | Train Dice: 0.6911 | Val Dice: 0.6298
[Seed 2026] Epoch 19/50 | Train Dice: 0.6849 | Val Dice: 0.6669
[Seed 2026] Epoch 20/50 | Train Dice: 0.6585 | Val Dice: 0.6680
[Seed 2026] Epoch 21/50 | Train Dice: 0.6594 | Val Dice: 0.6753
[Seed 2026] Epoch 22/50 | Train Dice: 0.6702 | Val Dice: 0.6675
[Seed 2026] Epoch 23/50 | Train Dice: 0.6693 | Val Dice: 0.6962
[Seed 2026] Epoch 24/50 | Train Dice: 0.6660 | Val Dice: 0.7113
[Seed 2026] Epoch 25/50 | Train Dice: 0.6980 | Val Dice: 0.7073
[Seed 2026] Epoch 26/50 | Train Dice: 0.6887 | Val Dice: 0.6971
[Seed 2026] Epoch 27/50 | Train Dice: 0.6994 | Val Dice: 0.6735
[Seed 2026] Epoch 28/50 | Train Dice: 0.6734 | Val Dice: 0.6654
[Seed 2026] Epoch 29/50 | Train Dice: 0.6634 | Val Dice: 0.6543
[Seed 2026] Epoch 30/50 | Train Dice: 0.6947 | Val Dice: 0.6484
[Seed 2026] Epoch 31/50 | Train Dice: 0.6909 | Val Dice: 0.6656
[Seed 2026] Epoch 32/50 | Train Dice: 0.6902 | Val Dice: 0.6998
[Seed 2026] Epoch 33/50 | Train Dice: 0.6563 | Val Dice: 0.6918
[Seed 2026] Epoch 34/50 | Train Dice: 0.6638 | Val Dice: 0.6798
[Seed 2026] Epoch 35/50 | Train Dice: 0.6901 | Val Dice: 0.6804
[Seed 2026] Epoch 36/50 | Train Dice: 0.6783 | Val Dice: 0.6478
[Seed 2026] Epoch 37/50 | Train Dice: 0.7113 | Val Dice: 0.6099
[Seed 2026] Epoch 38/50 | Train Dice: 0.6818 | Val Dice: 0.6923
[Seed 2026] Epoch 39/50 | Train Dice: 0.6767 | Val Dice: 0.6554
[Seed 2026] Epoch 40/50 | Train Dice: 0.6909 | Val Dice: 0.6521
[Seed 2026] Epoch 41/50 | Train Dice: 0.6840 | Val Dice: 0.6433
[Seed 2026] Epoch 42/50 | Train Dice: 0.6819 | Val Dice: 0.6767
[Seed 2026] Epoch 43/50 | Train Dice: 0.6962 | Val Dice: 0.6779
[Seed 2026] Epoch 44/50 | Train Dice: 0.6730 | Val Dice: 0.6149
[Seed 2026] Epoch 45/50 | Train Dice: 0.6532 | Val Dice: 0.6142
[Seed 2026] Epoch 46/50 | Train Dice: 0.6767 | Val Dice: 0.6127
[Seed 2026] Epoch 47/50 | Train Dice: 0.6850 | Val Dice: 0.6650
[Seed 2026] Epoch 48/50 | Train Dice: 0.6678 | Val Dice: 0.6796
[Seed 2026] Epoch 49/50 | Train Dice: 0.6764 | Val Dice: 0.6603
[Seed 2026] Epoch 50/50 | Train Dice: 0.6893 | Val Dice: 0.6689

In [111]:
# Summary of Lowrank model result
def get_summary(results, split, metric):

    values = np.array([result[split][metric]for result in results.values()])
    return (values.mean(),values.std(ddof=1),)


for split in ["testA", "testB"]:
    print(f"\n===== {split.upper()} =====")
    for metric in ["gland_dice","gland_iou","miou",]:
        mean, std = get_summary( lowrank_results,split,metric,)
        print(f"{metric:15s} | {mean:.4f} ± {std:.4f}")

===== TESTA =====
gland_dice      | 0.6154 ± 0.0184
gland_iou       | 0.4446 ± 0.0193
miou            | 0.3964 ± 0.0408

===== TESTB =====
gland_dice      | 0.7115 ± 0.0082
gland_iou       | 0.5523 ± 0.0098
miou            | 0.3987 ± 0.0453

### Rank-64 Model Testing

In [112]:
import torch.nn as nn
rank64_backbone = RankTruncatedBackbone(model,rank=64)

rank64_model = SegmentationProbing(
    model_backbone=rank64_backbone,
    is_baseline=False,
    feature_key="dense",
    feature_dim=768,
    num_classes=2,
    freeze_backbone=True,
    freeze_model=False,
    resize_output=(224, 224),
).to(device)

optimizer = torch.optim.AdamW(filter(lambda p: p.requires_grad,rank64_model.parameters()),
    lr=1e-3,weight_decay=1e-4,)
criterion = nn.CrossEntropyLoss()

In [113]:
import random

history = []
def train_spatial_probe(seed, num_epochs=50):
    # Training randomness
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    
    # Best checkpoint in memory
    best_val_dice = -1.0
    best_epoch = -1
    best_state = None

    # Training
    for epoch in range(num_epochs):
        train_metrics = run_epoch(rank64_model,probe_train_loader,optimizer=optimizer,
            criterion=criterion,device=device,)

        val_metrics = run_epoch(rank64_model,probe_val_loader,optimizer=None,
            criterion=criterion,device=device,)
        
        history.append({
            "epoch": epoch + 1,
            "train_dice": train_metrics["gland_dice"],
            "train_miou": train_metrics["miou"],
            "val_dice": val_metrics["gland_dice"],
            "val_miou": val_metrics["miou"],
        })

        print(
            f"[Seed {seed}] "
            f"Epoch {epoch+1:02d}/{num_epochs} | "
            f"Train Dice: {train_metrics['gland_dice']:.4f} | "
            f"Val Dice: {val_metrics['gland_dice']:.4f}"
        )

        if val_metrics["gland_dice"] > best_val_dice:
            best_val_dice = val_metrics["gland_dice"]
            best_epoch = epoch + 1
            best_state = {
                k: v.detach().cpu().clone()
                for k, v in rank64_model.state_dict().items()
            }

    
    # Restore best model
    rank64_model.load_state_dict(best_state)
    rank64_model.eval()
    
    # TestA
    testA_metrics = run_epoch(rank64_model,testA_loader,optimizer=None,
        criterion=criterion,device=device,)

    # TestB
    testB_metrics = run_epoch(rank64_model,testB_loader,optimizer=None,
        criterion=criterion,device=device,)

    return {
        "seed": seed,
        "best_epoch": best_epoch,
        "best_val_dice": best_val_dice,
        "testA": testA_metrics,
        "testB": testB_metrics,
        "history": history,
    }

In [114]:
# Running for 3 SEEDS
rank64_results = {}
for seed in [42, 123, 2026]:
    print("\n" + "=" * 70)
    print(f"STARTING RANK-64 PROBE — SEED {seed}")
    print("=" * 70)
    rank64_results[seed] = train_spatial_probe(seed=seed,num_epochs=50,)

======================================================================
STARTING RANK-64 PROBE — SEED 42
======================================================================
[Seed 42] Epoch 01/50 | Train Dice: 0.7187 | Val Dice: 0.7819
[Seed 42] Epoch 02/50 | Train Dice: 0.7926 | Val Dice: 0.7962
[Seed 42] Epoch 03/50 | Train Dice: 0.8026 | Val Dice: 0.8103
[Seed 42] Epoch 04/50 | Train Dice: 0.8194 | Val Dice: 0.8103
[Seed 42] Epoch 05/50 | Train Dice: 0.8198 | Val Dice: 0.8243
[Seed 42] Epoch 06/50 | Train Dice: 0.8347 | Val Dice: 0.8297
[Seed 42] Epoch 07/50 | Train Dice: 0.8270 | Val Dice: 0.8273
[Seed 42] Epoch 08/50 | Train Dice: 0.8288 | Val Dice: 0.8320
[Seed 42] Epoch 09/50 | Train Dice: 0.8386 | Val Dice: 0.8322
[Seed 42] Epoch 10/50 | Train Dice: 0.8338 | Val Dice: 0.8334
[Seed 42] Epoch 11/50 | Train Dice: 0.8300 | Val Dice: 0.8292
[Seed 42] Epoch 12/50 | Train Dice: 0.8382 | Val Dice: 0.8306
[Seed 42] Epoch 13/50 | Train Dice: 0.8386 | Val Dice: 0.8343
[Seed 42] Epoch 14/50 | Train Dice: 0.8456 | Val Dice: 0.8322
[Seed 42] Epoch 15/50 | Train Dice: 0.8500 | Val Dice: 0.8394
[Seed 42] Epoch 16/50 | Train Dice: 0.8430 | Val Dice: 0.8429
[Seed 42] Epoch 17/50 | Train Dice: 0.8412 | Val Dice: 0.8430
[Seed 42] Epoch 18/50 | Train Dice: 0.8354 | Val Dice: 0.8388
[Seed 42] Epoch 19/50 | Train Dice: 0.8454 | Val Dice: 0.8420
[Seed 42] Epoch 20/50 | Train Dice: 0.8512 | Val Dice: 0.8428
[Seed 42] Epoch 21/50 | Train Dice: 0.8440 | Val Dice: 0.8388
[Seed 42] Epoch 22/50 | Train Dice: 0.8408 | Val Dice: 0.8434
[Seed 42] Epoch 23/50 | Train Dice: 0.8561 | Val Dice: 0.8416
[Seed 42] Epoch 24/50 | Train Dice: 0.8533 | Val Dice: 0.8440
[Seed 42] Epoch 25/50 | Train Dice: 0.8432 | Val Dice: 0.8432
[Seed 42] Epoch 26/50 | Train Dice: 0.8540 | Val Dice: 0.8409
[Seed 42] Epoch 27/50 | Train Dice: 0.8465 | Val Dice: 0.8398
[Seed 42] Epoch 28/50 | Train Dice: 0.8543 | Val Dice: 0.8423
[Seed 42] Epoch 29/50 | Train Dice: 0.8607 | Val Dice: 0.8386
[Seed 42] Epoch 30/50 | Train Dice: 0.8371 | Val Dice: 0.8402
[Seed 42] Epoch 31/50 | Train Dice: 0.8514 | Val Dice: 0.8426
[Seed 42] Epoch 32/50 | Train Dice: 0.8504 | Val Dice: 0.8463
[Seed 42] Epoch 33/50 | Train Dice: 0.8428 | Val Dice: 0.8364
[Seed 42] Epoch 34/50 | Train Dice: 0.8634 | Val Dice: 0.8415
[Seed 42] Epoch 35/50 | Train Dice: 0.8425 | Val Dice: 0.8364
[Seed 42] Epoch 36/50 | Train Dice: 0.8486 | Val Dice: 0.8418
[Seed 42] Epoch 37/50 | Train Dice: 0.8407 | Val Dice: 0.8462
[Seed 42] Epoch 38/50 | Train Dice: 0.8503 | Val Dice: 0.8469
[Seed 42] Epoch 39/50 | Train Dice: 0.8476 | Val Dice: 0.8480
[Seed 42] Epoch 40/50 | Train Dice: 0.8416 | Val Dice: 0.8463
[Seed 42] Epoch 41/50 | Train Dice: 0.8433 | Val Dice: 0.8563
[Seed 42] Epoch 42/50 | Train Dice: 0.8525 | Val Dice: 0.8500
[Seed 42] Epoch 43/50 | Train Dice: 0.8451 | Val Dice: 0.8470
[Seed 42] Epoch 44/50 | Train Dice: 0.8534 | Val Dice: 0.8511
[Seed 42] Epoch 45/50 | Train Dice: 0.8574 | Val Dice: 0.8477
[Seed 42] Epoch 46/50 | Train Dice: 0.8529 | Val Dice: 0.8514
[Seed 42] Epoch 47/50 | Train Dice: 0.8508 | Val Dice: 0.8471
[Seed 42] Epoch 48/50 | Train Dice: 0.8462 | Val Dice: 0.8467
[Seed 42] Epoch 49/50 | Train Dice: 0.8451 | Val Dice: 0.8519
[Seed 42] Epoch 50/50 | Train Dice: 0.8463 | Val Dice: 0.8514

======================================================================
STARTING RANK-64 PROBE — SEED 123
======================================================================
[Seed 123] Epoch 01/50 | Train Dice: 0.8473 | Val Dice: 0.8545
[Seed 123] Epoch 02/50 | Train Dice: 0.8605 | Val Dice: 0.8491
[Seed 123] Epoch 03/50 | Train Dice: 0.8533 | Val Dice: 0.8503
[Seed 123] Epoch 04/50 | Train Dice: 0.8462 | Val Dice: 0.8428
[Seed 123] Epoch 05/50 | Train Dice: 0.8525 | Val Dice: 0.8526
[Seed 123] Epoch 06/50 | Train Dice: 0.8472 | Val Dice: 0.8540
[Seed 123] Epoch 07/50 | Train Dice: 0.8376 | Val Dice: 0.8507
[Seed 123] Epoch 08/50 | Train Dice: 0.8500 | Val Dice: 0.8494
[Seed 123] Epoch 09/50 | Train Dice: 0.8529 | Val Dice: 0.8500
[Seed 123] Epoch 10/50 | Train Dice: 0.8502 | Val Dice: 0.8441
[Seed 123] Epoch 11/50 | Train Dice: 0.8579 | Val Dice: 0.8512
[Seed 123] Epoch 12/50 | Train Dice: 0.8587 | Val Dice: 0.8515
[Seed 123] Epoch 13/50 | Train Dice: 0.8319 | Val Dice: 0.8342
[Seed 123] Epoch 14/50 | Train Dice: 0.8531 | Val Dice: 0.8509
[Seed 123] Epoch 15/50 | Train Dice: 0.8498 | Val Dice: 0.8511
[Seed 123] Epoch 16/50 | Train Dice: 0.8595 | Val Dice: 0.8522
[Seed 123] Epoch 17/50 | Train Dice: 0.8602 | Val Dice: 0.8461
[Seed 123] Epoch 18/50 | Train Dice: 0.8570 | Val Dice: 0.8456
[Seed 123] Epoch 19/50 | Train Dice: 0.8540 | Val Dice: 0.8445
[Seed 123] Epoch 20/50 | Train Dice: 0.8485 | Val Dice: 0.8475
[Seed 123] Epoch 21/50 | Train Dice: 0.8587 | Val Dice: 0.8459
[Seed 123] Epoch 22/50 | Train Dice: 0.8561 | Val Dice: 0.8408
[Seed 123] Epoch 23/50 | Train Dice: 0.8553 | Val Dice: 0.8504
[Seed 123] Epoch 24/50 | Train Dice: 0.8510 | Val Dice: 0.8452
[Seed 123] Epoch 25/50 | Train Dice: 0.8449 | Val Dice: 0.8449
[Seed 123] Epoch 26/50 | Train Dice: 0.8487 | Val Dice: 0.8466
[Seed 123] Epoch 27/50 | Train Dice: 0.8565 | Val Dice: 0.8534
[Seed 123] Epoch 28/50 | Train Dice: 0.8486 | Val Dice: 0.8528
[Seed 123] Epoch 29/50 | Train Dice: 0.8522 | Val Dice: 0.8512
[Seed 123] Epoch 30/50 | Train Dice: 0.8418 | Val Dice: 0.8525
[Seed 123] Epoch 31/50 | Train Dice: 0.8497 | Val Dice: 0.8518
[Seed 123] Epoch 32/50 | Train Dice: 0.8414 | Val Dice: 0.8545
[Seed 123] Epoch 33/50 | Train Dice: 0.8502 | Val Dice: 0.8528
[Seed 123] Epoch 34/50 | Train Dice: 0.8427 | Val Dice: 0.8464
[Seed 123] Epoch 35/50 | Train Dice: 0.8555 | Val Dice: 0.8464
[Seed 123] Epoch 36/50 | Train Dice: 0.8483 | Val Dice: 0.8511
[Seed 123] Epoch 37/50 | Train Dice: 0.8536 | Val Dice: 0.8531
[Seed 123] Epoch 38/50 | Train Dice: 0.8556 | Val Dice: 0.8501
[Seed 123] Epoch 39/50 | Train Dice: 0.8556 | Val Dice: 0.8535
[Seed 123] Epoch 40/50 | Train Dice: 0.8510 | Val Dice: 0.8464
[Seed 123] Epoch 41/50 | Train Dice: 0.8594 | Val Dice: 0.8420
[Seed 123] Epoch 42/50 | Train Dice: 0.8524 | Val Dice: 0.8504
[Seed 123] Epoch 43/50 | Train Dice: 0.8516 | Val Dice: 0.8498
[Seed 123] Epoch 44/50 | Train Dice: 0.8516 | Val Dice: 0.8500
[Seed 123] Epoch 45/50 | Train Dice: 0.8554 | Val Dice: 0.8537
[Seed 123] Epoch 46/50 | Train Dice: 0.8536 | Val Dice: 0.8524
[Seed 123] Epoch 47/50 | Train Dice: 0.8543 | Val Dice: 0.8484
[Seed 123] Epoch 48/50 | Train Dice: 0.8649 | Val Dice: 0.8522
[Seed 123] Epoch 49/50 | Train Dice: 0.8512 | Val Dice: 0.8517
[Seed 123] Epoch 50/50 | Train Dice: 0.8474 | Val Dice: 0.8513

======================================================================
STARTING RANK-64 PROBE — SEED 2026
======================================================================
[Seed 2026] Epoch 01/50 | Train Dice: 0.8474 | Val Dice: 0.8492
[Seed 2026] Epoch 02/50 | Train Dice: 0.8500 | Val Dice: 0.8487
[Seed 2026] Epoch 03/50 | Train Dice: 0.8509 | Val Dice: 0.8478
[Seed 2026] Epoch 04/50 | Train Dice: 0.8446 | Val Dice: 0.8450
[Seed 2026] Epoch 05/50 | Train Dice: 0.8487 | Val Dice: 0.8522
[Seed 2026] Epoch 06/50 | Train Dice: 0.8413 | Val Dice: 0.8519
[Seed 2026] Epoch 07/50 | Train Dice: 0.8561 | Val Dice: 0.8541
[Seed 2026] Epoch 08/50 | Train Dice: 0.8493 | Val Dice: 0.8512
[Seed 2026] Epoch 09/50 | Train Dice: 0.8445 | Val Dice: 0.8512
[Seed 2026] Epoch 10/50 | Train Dice: 0.8579 | Val Dice: 0.8517
[Seed 2026] Epoch 11/50 | Train Dice: 0.8550 | Val Dice: 0.8538
[Seed 2026] Epoch 12/50 | Train Dice: 0.8560 | Val Dice: 0.8511
[Seed 2026] Epoch 13/50 | Train Dice: 0.8587 | Val Dice: 0.8517
[Seed 2026] Epoch 14/50 | Train Dice: 0.8546 | Val Dice: 0.8520
[Seed 2026] Epoch 15/50 | Train Dice: 0.8500 | Val Dice: 0.8535
[Seed 2026] Epoch 16/50 | Train Dice: 0.8449 | Val Dice: 0.8459
[Seed 2026] Epoch 17/50 | Train Dice: 0.8553 | Val Dice: 0.8503
[Seed 2026] Epoch 18/50 | Train Dice: 0.8511 | Val Dice: 0.8450
[Seed 2026] Epoch 19/50 | Train Dice: 0.8439 | Val Dice: 0.8515
[Seed 2026] Epoch 20/50 | Train Dice: 0.8466 | Val Dice: 0.8514
[Seed 2026] Epoch 21/50 | Train Dice: 0.8434 | Val Dice: 0.8539
[Seed 2026] Epoch 22/50 | Train Dice: 0.8556 | Val Dice: 0.8529
[Seed 2026] Epoch 23/50 | Train Dice: 0.8476 | Val Dice: 0.8497
[Seed 2026] Epoch 24/50 | Train Dice: 0.8475 | Val Dice: 0.8533
[Seed 2026] Epoch 25/50 | Train Dice: 0.8553 | Val Dice: 0.8497
[Seed 2026] Epoch 26/50 | Train Dice: 0.8574 | Val Dice: 0.8497
[Seed 2026] Epoch 27/50 | Train Dice: 0.8576 | Val Dice: 0.8388
[Seed 2026] Epoch 28/50 | Train Dice: 0.8445 | Val Dice: 0.8412
[Seed 2026] Epoch 29/50 | Train Dice: 0.8469 | Val Dice: 0.8500
[Seed 2026] Epoch 30/50 | Train Dice: 0.8476 | Val Dice: 0.8492
[Seed 2026] Epoch 31/50 | Train Dice: 0.8506 | Val Dice: 0.8533
[Seed 2026] Epoch 32/50 | Train Dice: 0.8560 | Val Dice: 0.8529
[Seed 2026] Epoch 33/50 | Train Dice: 0.8392 | Val Dice: 0.8544
[Seed 2026] Epoch 34/50 | Train Dice: 0.8356 | Val Dice: 0.8509
[Seed 2026] Epoch 35/50 | Train Dice: 0.8555 | Val Dice: 0.8505
[Seed 2026] Epoch 36/50 | Train Dice: 0.8573 | Val Dice: 0.8520
[Seed 2026] Epoch 37/50 | Train Dice: 0.8602 | Val Dice: 0.8487
[Seed 2026] Epoch 38/50 | Train Dice: 0.8474 | Val Dice: 0.8493
[Seed 2026] Epoch 39/50 | Train Dice: 0.8598 | Val Dice: 0.8497
[Seed 2026] Epoch 40/50 | Train Dice: 0.8550 | Val Dice: 0.8500
[Seed 2026] Epoch 41/50 | Train Dice: 0.8588 | Val Dice: 0.8508
[Seed 2026] Epoch 42/50 | Train Dice: 0.8541 | Val Dice: 0.8520
[Seed 2026] Epoch 43/50 | Train Dice: 0.8574 | Val Dice: 0.8484
[Seed 2026] Epoch 44/50 | Train Dice: 0.8402 | Val Dice: 0.8475
[Seed 2026] Epoch 45/50 | Train Dice: 0.8495 | Val Dice: 0.8514
[Seed 2026] Epoch 46/50 | Train Dice: 0.8502 | Val Dice: 0.8471
[Seed 2026] Epoch 47/50 | Train Dice: 0.8494 | Val Dice: 0.8510
[Seed 2026] Epoch 48/50 | Train Dice: 0.8550 | Val Dice: 0.8498
[Seed 2026] Epoch 49/50 | Train Dice: 0.8518 | Val Dice: 0.8439
[Seed 2026] Epoch 50/50 | Train Dice: 0.8548 | Val Dice: 0.8489

In [115]:
# Summary of Lowrank model result
def get_summary(results, split, metric):

    values = np.array([result[split][metric]for result in results.values()])
    return (values.mean(),values.std(ddof=1),)


for split in ["testA", "testB"]:
    print(f"\n===== {split.upper()} =====")
    for metric in ["gland_dice","gland_iou","miou",]:
        mean, std = get_summary( rank64_results,split,metric,)
        print(f"{metric:15s} | {mean:.4f} ± {std:.4f}")

===== TESTA =====
gland_dice      | 0.8407 ± 0.0025
gland_iou       | 0.7252 ± 0.0037
miou            | 0.7244 ± 0.0022

===== TESTB =====
gland_dice      | 0.8400 ± 0.0017
gland_iou       | 0.7242 ± 0.0025
miou            | 0.6652 ± 0.0013

Despite reducing the representation rank from 196 to 64 (67.35% dimensionality reduction), the Rank-64 model retains performance close to the dense baseline across both held-out test sets. On TestA, gland Dice decreases by only 0.0066 (0.78%), while gland IoU and mIoU decrease by 0.0081 (1.10%) and 0.0052 (0.71%), respectively. On TestB, the corresponding decreases are 0.0083 (0.98%), 0.0124 (1.68%), and 0.0127 (1.87%). These results indicate that substantial representation compression can be achieved with only a minor degradation in segmentation performance.